using System;

namespace Japanese_Review
{
    /*
     * The Japanese Word class holds the following information:
     * japanese - the word written in japanese
     * romaji - conversion of the japanese word to latin
     * english - a list of english definitions of the word
     * writing - the syllabic writing for the word (hiragana or katakana)
     * kanji - 0 if not kanji, 1 if it is kanji
     */
    public class JapaneseWord
    {
        private String japanese;
        private String romaji;
        private String[] english;
        private String writing;
        private String adjective;
        private String kanji;

        public JapaneseWord(String japanese, String romaji, String[] english, String writing, String adjective,
            String kanji)
        {
            this.japanese = japanese;
            this.romaji = romaji;
            this.english = english;
            this.writing = writing;
            this.adjective = adjective;
            this.kanji = kanji;
        }

        /*
         *  Initialize 20 chapters of vocab from the Genki I & II textbooks
         *
            var chapter = new JapaneseWord[]
            {
                new JapaneseWord("", new String[]{""}, "hiragana", "", ""), 
                new JapaneseWord("", new String[]{""}, "katakana", "", ""), 
            };
         */
        public void initGenki()
        {
            var chapter1 = new JapaneseWord[]
            {
                new JapaneseWord("あの", "ano", new String[] {"um..."}, "hiragana", "", ""),
                new JapaneseWord("いま", "ima", new String[] {"now"}, "hiragana", "", ""),
                new JapaneseWord("えいご", "eigo", new String[] {"English"}, "hiragana", "", ""),
                new JapaneseWord("ええ", "ee", new String[] {"yes"}, "hiragana", "", ""),
                new JapaneseWord("がくせい", "gakusei", new String[] {"student"}, "hiragana", "", ""),
                new JapaneseWord("~ご", "~go", new String[] {"language"}, "hiragana", "", ""),
                new JapaneseWord("こうこう", "koukou", new String[] {"high school"}, "hiragana", "", ""),
                new JapaneseWord("ごご", "gogo", new String[] {"P.M."}, "hiragana", "", ""),
                new JapaneseWord("ごぜん", "gozen", new String[] {"A.M"}, "hiragana", "", ""),
                new JapaneseWord("~さい", "~sai", new String[] {"~years old"}, "hiragana", "", ""),
                new JapaneseWord("~さん", "~san", new String[] {"Mr.", "Mrs."}, "hiragana", "", ""),
                new JapaneseWord("~じ", "~ji", new String[] {"o'clock"}, "hiragana", "", ""),
                new JapaneseWord("~じん", "~jin", new String[] {"~people"}, "hiragana", "", ""),
                new JapaneseWord("せんこう", "senkou", new String[] {"major"}, "hiragana", "", ""),
                new JapaneseWord("せんせい", "sensei", new String[] {"teacher", "professor"}, "hiragana", "", ""),
                new JapaneseWord("そうです", "sou desu", new String[] {"that's right"}, "hiragana", "", ""),
                new JapaneseWord("そうですか", "sou desu ka", new String[] {"I see", "is that so?"}, "hiragana", "", ""),
                new JapaneseWord("だいがく", "daigaku", new String[] {"college", "university"}, "hiragana", "", ""),
                new JapaneseWord("でんわ", "denwa", new String[] {"telephone"}, "hiragana", "", ""),
                new JapaneseWord("ともだち", "tomodachi", new String[] {"friend"}, "hiragana", "", ""),
                new JapaneseWord("まなえ", "namae", new String[] {"name"}, "hiragana", "", ""),
                new JapaneseWord("にほん", "nihon", new String[] {"Japan"}, "hiragana", "", ""),
                new JapaneseWord("~ねんせい", "~nensei", new String[] {"~year student"}, "hiragana", "", ""),
                new JapaneseWord("はい", "hai", new String[] {"yes"}, "hiragana", "", ""),
                new JapaneseWord("はん", "han", new String[] {"half"}, "hiragana", "", ""),
                new JapaneseWord("ばんごう", "bangou", new String[] {"number"}, "hiragana", "", ""),
                new JapaneseWord("りゅうがくせい", "ryuugakusei", new String[] {"international student"}, "hiragana", "", ""),
                new JapaneseWord("わたし", "watashi", new String[] {"I"}, "hiragana", "", ""),
                new JapaneseWord("ちゅうごく", "Chuugoku", new String[] {"China"}, "hiragana", "", ""),
                new JapaneseWord("かんこく", "Kankoku", new String[] {"Korea"}, "hiragana", "", ""),
                new JapaneseWord("かがく", "kagaku", new String[] {"science"}, "hiragana", "", ""),
                new JapaneseWord("けいざい", "keizai", new String[] {"economics"}, "hiragana", "", ""),
                new JapaneseWord("こくさいかんけい", "kokusaikankei", new String[] {"international relations"}, "hiragana", "", ""),
                new JapaneseWord("じんるいがく", "jinruigaku", new String[] {"anthropology"}, "hiragana", "", ""),
                new JapaneseWord("せいじ", "seeji", new String[] {"politics"}, "hiragana", "", ""),
                new JapaneseWord("ぶんがく", "bungaku", new String[] {"literature"}, "hiragana", "", ""),
                new JapaneseWord("れきし", "rekishi", new String[] {"history"}, "hiragana", "", ""),
                new JapaneseWord("しごと", "shigoto", new String[] {"job", "work", "occupation"}, "hiragana", "", ""),
                new JapaneseWord("いしゃ", "isha", new String[] {"doctor"}, "hiragana", "", ""),
                new JapaneseWord("かいしゃいん", "kaishain", new String[] {"office worker"}, "hiragana", "", ""),
                new JapaneseWord("こうこうせい", "koukousei", new String[] {"high school student"}, "hiragana", "", ""),
                new JapaneseWord("しゅふ", "shufu", new String[] {"housewife"}, "hiragana", "", ""),
                new JapaneseWord("だいがくいんせい", "daigakuinsei", new String[] {"graduate student"}, "hiragana", "", ""),
                new JapaneseWord("だいがくせい", "daigakusei", new String[] {"college student"}, "hiragana", "", ""),
                new JapaneseWord("べんごし", "bengoshi", new String[] {"lawyer"}, "hiragana", "", ""),
                new JapaneseWord("おかあさん", "okaasan", new String[] {"mother"}, "hiragana", "", ""),
                new JapaneseWord("おとうさん", "otousan", new String[] {"father"}, "hiragana", "", ""),
                new JapaneseWord("おねえさん", "oneesan", new String[] {"older sister"}, "hiragana", "", ""),
                new JapaneseWord("おにいさん", "oniisan", new String[] {"older brother"}, "hiragana", "", ""),
                new JapaneseWord("いもうと", "imouto", new String[] {"younger sister"}, "hiragana", "", ""),
                new JapaneseWord("おとうと", "otouto", new String[] {"younger brother"}, "hiragana", "", ""),
                new JapaneseWord(" ", "Amerika", new String[] {"U.S.A."}, "katakana", "", ""),
                new JapaneseWord(" ", "Igirisu", new String[] {"Britain"}, "katakana", "", ""),
                new JapaneseWord(" ", "Oosutoraria", new String[] {"Australia"}, "katakana", "", ""),
                new JapaneseWord(" ", "Suweeden", new String[] {"Sweden"}, "katakana", "", ""),
                new JapaneseWord(" ", "konpyuutaa", new String[] {"computer"}, "katakana", "", ""),
                new JapaneseWord(" ", "bijinesu", new String[] {"business"}, "katakana", "", "")
            };

            var chapter2 = new JapaneseWord[]
            {
                new JapaneseWord("これ", "kore", new String[] {"this one"}, "hiragana", "", ""),
                new JapaneseWord("それ", "sore", new String[] {"that one"}, "hiragana", "", ""),
                new JapaneseWord("あれ", "are", new String[] {"that one over there"}, "hiragana", "", ""),
                new JapaneseWord("どれ", "dore", new String[] {"which one"}, "hiragana", "", ""),
                new JapaneseWord("この", "kono", new String[] {"this..."}, "hiragana", "", ""),
                new JapaneseWord("その", "sono", new String[] {"that..."}, "hiragana", "", ""),
                new JapaneseWord("あの", "ano", new String[] {"that... over there"}, "hiragana", "", ""),
                new JapaneseWord("どの", "dono", new String[] {"which..."}, "hiragana", "", ""),
                new JapaneseWord("ここ", "koko", new String[] {"here"}, "hiragana", "", ""),
                new JapaneseWord("そこ", "soko", new String[] {"there"}, "hiragana", "", ""),
                new JapaneseWord("あそこ", "asoko", new String[] {"over there"}, "hiragana", "", ""),
                new JapaneseWord("どこ", "doko", new String[] {"where"}, "hiragana", "", ""),
                new JapaneseWord("だれ", "dare", new String[] {"who"}, "hiragana", "", ""),
                new JapaneseWord("おいしい", "oishii", new String[] {"delicious"}, "hiragana", "i", ""),
                new JapaneseWord("さかな", "sakana", new String[] {"fish"}, "hiragana", "", ""),
                new JapaneseWord("とんかつ", "tonkatsu", new String[] {"pork cutlet"}, "hiragana", "", ""),
                new JapaneseWord("にく", "niku", new String[] {"meat"}, "hiragana", "", ""),
                new JapaneseWord("やさい", "yasai", new String[] {"vegetable"}, "hiragana", "", ""),
                new JapaneseWord("えんぴつ", "enpitsu", new String[] {"pencil"}, "hiragana", "", ""),
                new JapaneseWord("かさ", "kasa", new String[] {"umbrella"}, "hiragana", "", ""),
                new JapaneseWord("かばん", "kaban", new String[] {"bag"}, "hiragana", "", ""),
                new JapaneseWord("くつ", "kutsu", new String[] {"shoes"}, "hiragana", "", ""),
                new JapaneseWord("さいふ", "saifu", new String[] {"wallet"}, "hiragana", "", ""),
                new JapaneseWord("じしょ", "jisho", new String[] {"dictionary"}, "hiragana", "", ""),
                new JapaneseWord("じてんしゃ", "jitensha", new String[] {"bicycle"}, "hiragana", "", ""),
                new JapaneseWord("しんぶん", "shinbun", new String[] {"newspaper"}, "hiragana", "", ""),
                new JapaneseWord("とけい", "tokei", new String[] {"watch", "clock"}, "hiragana", "", ""),
                new JapaneseWord("ぼうし", "boushi", new String[] {"hat", "cap"}, "hiragana", "", ""),
                new JapaneseWord("ほん", "hon", new String[] {"book"}, "hiragana", "", ""),
                new JapaneseWord("きっさてん", "kissaten", new String[] {"cafe"}, "hiragana", "", ""),
                new JapaneseWord("ぎんこう", "ginkou", new String[] {"bank"}, "hiragana", "", ""),
                new JapaneseWord("としょかん", "toshokan", new String[] {"library"}, "hiragana", "", ""),
                new JapaneseWord("ゆうびんきょく", "yuubinkyoku", new String[] {"post office"}, "hiragana", "", ""),
                new JapaneseWord("いくら", "ikura", new String[] {"how much"}, "hiragana", "", ""),
                new JapaneseWord("~えん", "~en", new String[] {"~yen"}, "hiragana", "", ""),
                new JapaneseWord("たかい", "takai", new String[] {"expensive", "high"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "menyuu", new String[] {"menu"}, "katakana", "", ""),
                new JapaneseWord(" ", "jiinzu", new String[] {"jeans"}, "katakana", "", ""),
                new JapaneseWord(" ", "tiishatsu", new String[] {"T-shirt"}, "katakana", "", ""),
                new JapaneseWord(" ", "nooto", new String[] {"notebook"}, "katakana", "", ""),
                new JapaneseWord(" ", "pen", new String[] {"pen"}, "katakana", "", ""),
                new JapaneseWord(" ", "toire", new String[] {"toilet", "restroom"}, "katakana", "", "")
            };

            var chapter3 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "eiga", new String[] {"movie"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ongaku", new String[] {"music"}, "hiragana", "", ""),
                new JapaneseWord(" ", "zasshi", new String[] {"magazine"}, "hiragana", "", ""),
                new JapaneseWord(" ", "asagohan", new String[] {"breakfast"}, "hiragana", "", ""),
                new JapaneseWord(" ", "osake", new String[] {"sake", "alcohol"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ochya", new String[] {"tea"}, "hiragana", "", ""),
                new JapaneseWord(" ", "bangohan", new String[] {"dinner"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hirugohan", new String[] {"lunch"}, "hiragana", "", ""),
                new JapaneseWord(" ", "mizu", new String[] {"water"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ie", new String[] {"home", "house"}, "hiragana", "", ""),
                new JapaneseWord(" ", "uchi", new String[] {"home", "house", "my place"}, "hiragana", "", ""),
                new JapaneseWord(" ", "gakkou", new String[] {"school"}, "hiragana", "", ""),
                new JapaneseWord(" ", "asa", new String[] {"morning"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ashita", new String[] {"tomorrow"}, "hiragana", "", ""),
                new JapaneseWord(" ", "itsu", new String[] {"when"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kyou", new String[] {"today"}, "hiragana", "", ""),
                new JapaneseWord(" ", "~goro", new String[] {"at about..."}, "hiragana", "", ""),
                new JapaneseWord(" ", "konban", new String[] {"tonight"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shuumatsu", new String[] {"weekend"}, "hiragana", "", ""),
                new JapaneseWord(" ", "doyoubi", new String[] {"Saturday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "nichiyoubi", new String[] {"Sunday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "mainichi", new String[] {"every day"}, "hiragana", "", ""),
                new JapaneseWord(" ", "maiban", new String[] {"every night"}, "hiragana", "", ""),
                new JapaneseWord(" ", "iku", new String[] {"to go"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kaeru", new String[] {"to go back", "to return"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kiku", new String[] {"to listen", "to hear"}, "hiragana", "", ""),
                new JapaneseWord(" ", "nomu", new String[] {"to drink"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hanasu", new String[] {"to speak", "to talk"}, "hiragana", "", ""),
                new JapaneseWord(" ", "yomu", new String[] {"to read"}, "hiragana", "", ""),
                new JapaneseWord(" ", "okiru", new String[] {"to get up"}, "hiragana", "", ""),
                new JapaneseWord(" ", "taberu", new String[] {"to eat"}, "hiragana", "", ""),
                new JapaneseWord(" ", "neru", new String[] {"to sleep", "to go to sleep"}, "hiragana", "", ""),
                new JapaneseWord(" ", "miru", new String[] {"to see", "to look at", "to watch"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kuru", new String[] {"to come"}, "hiragana", "", ""),
                new JapaneseWord(" ", "suru", new String[] {"to do"}, "hiragana", "", ""),
                new JapaneseWord(" ", "benkyousuru", new String[] {"to study"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ii", new String[] {"good"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hayai", new String[] {"early"}, "hiragana", "", ""),
                new JapaneseWord(" ", "amari", new String[] {"not much"}, "hiragana", "", ""),
                new JapaneseWord(" ", "zenzen", new String[] {"not at all"}, "hiragana", "", ""),
                new JapaneseWord(" ", "taitei", new String[] {"usually"}, "hiragana", "", ""),
                new JapaneseWord(" ", "chotto", new String[] {"a little"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tokidoki", new String[] {"sometimes"}, "hiragana", "", ""),
                new JapaneseWord(" ", "yoku", new String[] {"often", "much"}, "hiragana", "", ""),
                new JapaneseWord(" ", "supotsu", new String[] {"sports"}, "katakana", "", ""),
                new JapaneseWord(" ", "deeto", new String[] {"date"}, "katakana", "", ""),
                new JapaneseWord(" ", "tenisu", new String[] {"tennis"}, "katakana", "", ""),
                new JapaneseWord(" ", "terebi", new String[] {"TV"}, "katakana", "", ""),
                new JapaneseWord(" ", "aisukureemu", new String[] {"ice cream"}, "katakana", "", ""),
                new JapaneseWord(" ", "koohii", new String[] {"coffee"}, "katakana", "", ""),
                new JapaneseWord(" ", "hanbaagaa", new String[] {"hamburger"}, "katakana", "", "")
            };

            var chapter4 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "kaimono", new String[] {"shopping"}, "hiragana", "", ""),
                new JapaneseWord(" ", "anata", new String[] {"you"}, "hiragana", "", ""),
                new JapaneseWord(" ", "isu", new String[] {"chair"}, "hiragana", "", ""),
                new JapaneseWord(" ", "inu", new String[] {"dog"}, "hiragana", "", ""),
                new JapaneseWord(" ", "omiyage", new String[] {"souvenir"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kodomo", new String[] {"child"}, "hiragana", "", ""),
                new JapaneseWord(" ", "gohan", new String[] {"rice", "meal"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shashin", new String[] {"picture", "photo", "photograph"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tsukue", new String[] {"desk"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tegami", new String[] {"letter"}, "hiragana", "", ""),
                new JapaneseWord(" ", "neko", new String[] {"cat"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hito", new String[] {"person"}, "hiragana", "", ""),
                new JapaneseWord(" ", "otera", new String[] {"temple"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kouen", new String[] {"park"}, "hiragana", "", ""),
                new JapaneseWord(" ", "byouin", new String[] {"hospital"}, "hiragana", "", ""),
                new JapaneseWord(" ", "honya", new String[] {"bookstore"}, "hiragana", "", ""),
                new JapaneseWord(" ", "machi", new String[] {"town", "city"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kinou", new String[] {"yesterday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "~jikan", new String[] {"~hours"}, "hiragana", "", ""),
                new JapaneseWord(" ", "senshuu", new String[] {"last week"}, "hiragana", "", ""),
                new JapaneseWord(" ", "toki", new String[] {"when...", "at the time of..."}, "hiragana", "", ""),
                new JapaneseWord(" ", "getsuyoubi", new String[] {"Monday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kayoubi", new String[] {"Tuesday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "suiyoubi", new String[] {"Wednesday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "mokuyoubi", new String[] {"Thursday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kinyoubi", new String[] {"Friday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "au", new String[] {"to meet", "to see a person"}, "hiragana", "", ""),
                new JapaneseWord(" ", "aru", new String[] {"to exist", "there is..."}, "hiragana", "", ""),
                new JapaneseWord(" ", "kau", new String[] {"to buy"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kaku", new String[] {"to write", "to paint"}, "hiragana", "", ""),
                new JapaneseWord(" ", "toru", new String[] {"to take", "to get a grade"}, "hiragana", "", ""),
                new JapaneseWord(" ", "matsu", new String[] {"to wait"}, "hiragana", "", ""),
                new JapaneseWord(" ", "wakaru", new String[] {"to understand"}, "hiragana", "", ""),
                new JapaneseWord(" ", "iru", new String[] {"to exist", "is in...", "stays at..."}, "hiragana", "", ""),
                new JapaneseWord(" ", "arubaito", new String[] {"part-time job"}, "katakana", "", ""),
                new JapaneseWord(" ", "kurasu", new String[] {"class"}, "katakana", "", ""),
                new JapaneseWord(" ", "pan", new String[] {"bread"}, "katakana", "", ""),
                new JapaneseWord(" ", "meeru", new String[] {"e-mail"}, "katakana", "", ""),
                new JapaneseWord(" ", "suupaa", new String[] {"supermarket"}, "katakana", "", ""),
                new JapaneseWord(" ", "depaato", new String[] {"department store"}, "katakana", "", ""),
                new JapaneseWord(" ", "basutei", new String[] {"bus stop"}, "katakana", "", ""),
                new JapaneseWord(" ", "hoteru", new String[] {"hotel"}, "katakana", "", ""),
                new JapaneseWord(" ", "resutoran", new String[] {"restaurant"}, "katakana", "", "")
            };

            var chapter5 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "umi", new String[] {"sea"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kitte", new String[] {"postal stamps"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kippu", new String[] {"ticket"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shukudai", new String[] {"homework"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tabemono", new String[] {"food"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tanjoubi", new String[] {"birthday"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tenki", new String[] {"weather"}, "hiragana", "", ""),
                new JapaneseWord(" ", "nomimono", new String[] {"drink"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hagaki", new String[] {"postcard"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hikouki", new String[] {"airplane"}, "hiragana", "", ""),
                new JapaneseWord(" ", "heya", new String[] {"room"}, "hiragana", "", ""),
                new JapaneseWord(" ", "boku", new String[] {"I"}, "hiragana", "", ""),
                new JapaneseWord(" ", "yasumi", new String[] {"holiday", "day off", "absence"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ryokou", new String[] {"travel"}, "hiragana", "", ""),
                new JapaneseWord(" ", "atarashii", new String[] {"new"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "atsui", new String[] {"hot"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "isogashii", new String[] {"busy"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "ookii", new String[] {"large"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "omoshiroi", new String[] {"interesting", "funny"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "kakkoii", new String[] {"cool", "good-looking"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "kowai", new String[] {"frightening"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "samui", new String[] {"cold"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "tanoshii", new String[] {"fun"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "chiisai", new String[] {"small"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "tsumaranai", new String[] {"boring"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "furui", new String[] {"old"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "muzukashii", new String[] {"difficult"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "yasashii", new String[] {"easy", "kind"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "yasui", new String[] {"inexpensive", "cheap"}, "hiragana", "i", ""),
                new JapaneseWord(" ", "kirai", new String[] {"to dislike", "disgusted with"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "kirei", new String[] {"beautiful", "clean"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "genki", new String[] {"healthy", "energetic"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "shizuka", new String[] {"quiet"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "suki", new String[] {"to like", "fond of"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "daikirai", new String[] {"to hate"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "daisuki", new String[] {"to love", "very fond of"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "nigiyaka", new String[] {"lively"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "hima", new String[] {"not busy", "free"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "oyogu", new String[] {"to swim"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kiku", new String[] {"to ask"}, "hiragana", "", ""),
                new JapaneseWord(" ", "noru", new String[] {"to ride", "to board"}, "hiragana", "", ""),
                new JapaneseWord(" ", "yaru", new String[] {"to do", "to perform"}, "hiragana", "", ""),
                new JapaneseWord(" ", "dekakeru", new String[] {"to go out"}, "hiragana", "", ""),
                new JapaneseWord(" ", "saafin", new String[] {"surfing"}, "katakana", "", ""),
                new JapaneseWord(" ", "basu", new String[] {"bus"}, "katakana", "", "")
            };

            var chapter6 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "okane", new String[] {"money"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ofuro", new String[] {"bath"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kanji", new String[] {"kanji", "Chinese character"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kyoukasho", new String[] {"textbook"}, "hiragana", "", ""),
                new JapaneseWord(" ", "konshuu", new String[] {"this week"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shiminbyouin", new String[] {"municipal hospital"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tsugi", new String[] {"next"}, "hiragana", "", ""),
                new JapaneseWord(" ", "denki", new String[] {"electricity"}, "hiragana", "", ""),
                new JapaneseWord(" ", "densha", new String[] {"train"}, "hiragana", "", ""),
                new JapaneseWord(" ", "nimotsu", new String[] {"baggage"}, "hiragana", "", ""),
                new JapaneseWord(" ", "mado", new String[] {"window"}, "hiragana", "", ""),
                new JapaneseWord(" ", "yoru", new String[] {"night"}, "hiragana", "", ""),
                new JapaneseWord(" ", "raishuu", new String[] {"next week"}, "hiragana", "", ""),
                new JapaneseWord(" ", "rainen", new String[] {"next year"}, "hiragana", "", ""),
                new JapaneseWord(" ", "taihen", new String[] {"tough"}, "hiragana", "na", ""),
                new JapaneseWord(" ", "asobu", new String[] {"to play", "to spend time pleasantly"}, "hiragana", "", ""),
                new JapaneseWord(" ", "isogu", new String[] {"to hurry"}, "hiragana", "", ""),
                new JapaneseWord(" ", "ofuronihairu", new String[] {"to take a bath"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kaesu", new String[] {"to return"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kesu", new String[] {"to turn off", "to erase"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shinu", new String[] {"to die"}, "hiragana", "", ""),
                new JapaneseWord(" ", "suwaru", new String[] {"to sit down"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tatsu", new String[] {"to stand up"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tabakowosuu", new String[] {"to smoke"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tsukau", new String[] {"to use"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tetsudau", new String[] {"to help"}, "hiragana", "", ""),
                new JapaneseWord(" ", "hairu", new String[] {"to enter"}, "hiragana", "", ""),
                new JapaneseWord(" ", "motsu", new String[] {"to carry", "to hold"}, "hiragana", "", ""),
                new JapaneseWord(" ", "yasumu", new String[] {"to be absent", "to rest"}, "hiragana", "", ""),
                new JapaneseWord(" ", "akeru", new String[] {"to open"}, "hiragana", "", ""),
                new JapaneseWord(" ", "oshieru", new String[] {"to teach", "to instruct"}, "hiragana", "", ""),
                new JapaneseWord(" ", "oriru", new String[] {"to get off"}, "hiragana", "", ""),
                new JapaneseWord(" ", "kariru", new String[] {"to borrow"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shimeru", new String[] {"to close"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shawaawoabiru", new String[] {"to take a shower"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tsukeru", new String[] {"to turn off"}, "hiragana", "", ""),
                new JapaneseWord(" ", "denwawokakeru", new String[] {"to make a phone call"}, "hiragana", "", ""),
                new JapaneseWord(" ", "wasureru", new String[] {"to forget", "to leave behind"}, "hiragana", "", ""),
                new JapaneseWord(" ", "tsuretekuru", new String[] {"to bring (person)"}, "hiragana", "", ""),
                new JapaneseWord(" ", "mottekuru", new String[] {"to bring (thing)"}, "hiragana", "", ""),
                new JapaneseWord(" ", "shawaa", new String[] {"shower"}, "katakana", "", ""),
                new JapaneseWord(" ", "pasokon", new String[] {"computer"}, "katakana", "", ""),
                new JapaneseWord(" ", "peeji", new String[] {"page"}, "katakana", "", "")
            };
            
            var chapter7 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "ane", new String[]{"older sister"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "imouto", new String[]{"younger sister"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "uta", new String[]{"song"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ojiisan", new String[]{"grandfather", "old man"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otouto", new String[]{"younger brother"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otokonohito", new String[]{"man"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oniisan", new String[]{"older brother"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oneesan", new String[]{"older sister"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "obaasan", new String[]{"grandmother", "old woman"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onnanohito", new String[]{"woman"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kaisha", new String[]{"company"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kazoku", new String[]{"family"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kami", new String[]{"hair"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kyoudai", new String[]{"siblings", "brothers and sisters"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kuchi", new String[]{"mouth"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kuni", new String[]{"country"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kuruma", new String[]{"car"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shokudou", new String[]{"cafeteria", "dining commons"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chichi", new String[]{"father"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "haha", new String[]{"mother"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "me", new String[]{"eye"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "megane", new String[]{"glasses"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "atamagaii", new String[]{"smart", "bright", "clever"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kawaii", new String[]{"cute"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "segatakai", new String[]{"tall"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "segahikui", new String[]{"short"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "nagai", new String[]{"long"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "hayai", new String[]{"fast"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "mijikai", new String[]{"short"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "shinsetsu", new String[]{"kind"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "benri", new String[]{"convenient"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "utau", new String[]{"to sing"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kaburu", new String[]{"to put on (a hat)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shiru", new String[]{"to know", "to get to know"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sumu", new String[]{"to live"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "haku", new String[]{"to put on (items below your waist)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "futoru", new String[]{"to gain weight"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "meganewokakeru", new String[]{"to put on glasses"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kiru", new String[]{"to wear", "to put on (clothes above your waist)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsutomeru", new String[]{"to work for"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yaseru", new String[]{"to lose weight"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kekkonsuru", new String[]{"to get married"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "apaato", new String[]{"apartment"}, "katakana", "", ""), 
                new JapaneseWord(" ", "geemu", new String[]{"game"}, "katakana", "", ""), 
                new JapaneseWord(" ", "konbini", new String[]{"convenience store"}, "katakana", "", ""), 
                new JapaneseWord(" ", "saakuru", new String[]{"club activity"}, "katakana", "", "")
            };
            
            var chapter8 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "asatte", new String[]{"the day after tomorrow"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ame", new String[]{"rain"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kaishain", new String[]{"office worker"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kuuki", new String[]{"air"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kesa", new String[]{"this morning"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kokuban", new String[]{"blackboard"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kongetsu", new String[]{"this month"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shigoto", new String[]{"job", "work", "occupation"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "daigakusei", new String[]{"college student"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tenkiyohou", new String[]{"weather forecast"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tokoro", new String[]{"place"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "natsu", new String[]{"summer"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nanika", new String[]{"something"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hashi", new String[]{"chopsticks"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "fuyu", new String[]{"winter"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "maishuu", new String[]{"every week"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "raigetsu", new String[]{"next month"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "jouzu", new String[]{"good at...", "skillful"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "heta", new String[]{"poor at...", "clumsy"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "yuumei", new String[]{"famous"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "amegafuru", new String[]{"it rains"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "arau", new String[]{"to wash"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "iu", new String[]{"to say"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "iru", new String[]{"to need"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "osokunaru", new String[]{"to be late"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "omou", new String[]{"to think"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kiru", new String[]{"to cut"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsukuru", new String[]{"to make"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "motteiku", new String[]{"to take"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "jirojiromiru", new String[]{"to stare (at...)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "suteru", new String[]{"to throw away"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hajimeru", new String[]{"to begin"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "untensuru", new String[]{"to drive"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sentakusuru", new String[]{"to do laundry"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "soujisuru", new String[]{"to clean"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "denwasuru", new String[]{"to call"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryourisuru", new String[]{"to cook"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kamera", new String[]{"camera"}, "katakana", "", ""), 
                new JapaneseWord(" ", "karaoke", new String[]{"karaoke"}, "katakana", "", ""), 
                new JapaneseWord(" ", "tomato", new String[]{"tomato"}, "katakana", "", ""), 
                new JapaneseWord(" ", "paatii", new String[]{"party"}, "katakana", "", ""), 
                new JapaneseWord(" ", "baabekyuu", new String[]{"barbecue"}, "katakana", "", ""), 
                new JapaneseWord(" ", "hoomusutei", new String[]{"homestay", "living with a local family"}, "katakana", "", "")
            };
            
            var chapter9 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "iiko", new String[]{"good child"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "iro", new String[]{"color"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "obentou", new String[]{"boxed lunch"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kabuki", new String[]{"Kabuki", "traditional Japanese theatrical art"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kyonen", new String[]{"last year"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kusuri", new String[]{"medicine"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kondo", new String[]{"near future"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sakubun", new String[]{"essay", "composition"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shiken", new String[]{"exam"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sengetsu", new String[]{"last month"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tango", new String[]{"vocabulary", "word"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "byouki", new String[]{"sickness", "illness"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "aoi", new String[]{"blue"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "akai", new String[]{"red"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kuroi", new String[]{"black"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "shiroi", new String[]{"white"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "wakai", new String[]{"young"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "sabishii", new String[]{"lonely"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "ijiwaru", new String[]{"mean", "mean-spirited"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "odoru", new String[]{"to dance"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "owaru", new String[]{"something ends"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ninkigaaru", new String[]{"to be popular"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hajimaru", new String[]{"something begins"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hiku", new String[]{"to play (a string instrument or piano)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "morau", new String[]{"to receive", "to get (from somebody)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oboeru", new String[]{"to memorize"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "deru", new String[]{"to appear", "to exit", "to attend"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "undousuru", new String[]{"to exercise"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sanposuru", new String[]{"to take a walk"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gitaa", new String[]{"guitar"}, "katakana", "", ""), 
                new JapaneseWord(" ", "konsaato", new String[]{"concert"}, "katakana", "", ""), 
                new JapaneseWord(" ", "sukii", new String[]{"ski"}, "katakana", "", ""), 
                new JapaneseWord(" ", "piano", new String[]{"piano"}, "katakana", "", ""), 
                new JapaneseWord(" ", "piza", new String[]{"pizza"}, "katakana", "", "")
            };
            
            var chapter10 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "aki", new String[]{"fall"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "isha", new String[]{"doctor"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "eki", new String[]{"station"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okanemochi", new String[]{"rich person"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kao", new String[]{"face"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kisetsu", new String[]{"season"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gyuunyuu", new String[]{"milk"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kotoshi", new String[]{"this year"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shinkansen", new String[]{"bullet train", "Shinkansen"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sushi", new String[]{"sushi"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "seikatsu", new String[]{"life", "living"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sekai", new String[]{"world"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chikatetsu", new String[]{"subway"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tebukuro", new String[]{"gloves"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tenpura", new String[]{"tempura"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tokoya", new String[]{"barber shop", "barber's"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "haru", new String[]{"spring"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "biyouin", new String[]{"beauty parlor"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "bin", new String[]{"flight"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "fune", new String[]{"ship", "boat"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yakyuu", new String[]{"baseball"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yoyaku", new String[]{"reservation"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "raigakki", new String[]{"next semester"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ringo", new String[]{"apple"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "atatakai", new String[]{"warm"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "osoi", new String[]{"slow", "late"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "suzushii", new String[]{"cool (weather)"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "tsumetai", new String[]{"cold (things)", "cold personality"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "nemui", new String[]{"sleepy"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kantan", new String[]{"simple", "easy"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "kakaru", new String[]{"to take (time)", "to take (money)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tomaru", new String[]{"to stay"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "naru", new String[]{"to become"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "harau", new String[]{"to pay"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kimeru", new String[]{"to decide"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryokousuru", new String[]{"to travel"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "renshuusuru", new String[]{"to practice"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kurejittokaado", new String[]{"credit card"}, "katakana", "", ""), 
                new JapaneseWord(" ", "keeki", new String[]{"cake"}, "katakana", "", ""), 
                new JapaneseWord(" ", "sakkaa", new String[]{"soccer"}, "katakana", "", ""), 
                new JapaneseWord(" ", "pantsu", new String[]{"pants"}, "katakana", "", "")
            };
            
            var chapter11 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "okashi", new String[]{"sweets", "snacks"}, "hiragana", "", ""),
                new JapaneseWord(" ", "oshougatsu", new String[]{"New Year's"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otokonoko", new String[]{"boy"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "omatsuri", new String[]{"festival"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "omochya", new String[]{"toy"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onsen", new String[]{"hot spring", "spa"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onnanoko", new String[]{"girl"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gaikoku", new String[]{"foreign country"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kashu", new String[]{"singer"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kawa", new String[]{"river"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kochira", new String[]{"this person (polite)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kongakki", new String[]{"this semester"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shachou", new String[]{"president of a company"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "jugyou", new String[]{"class"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shourai", new String[]{"future"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "jinja", new String[]{"shrine"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsuri", new String[]{"fishing"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "bijutsukan", new String[]{"art museum"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mizuumi", new String[]{"lake"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yama", new String[]{"mountain"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yume", new String[]{"dream"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "usowotsuku", new String[]{"to lie", "to tell a lie"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onakagasuku", new String[]{"to become hungry"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kau", new String[]{"to own (a pet)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "narau", new String[]{"to learn"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "noboru", new String[]{"to climb"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hataraku", new String[]{"to work"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsukareru", new String[]{"to get tired"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yameru", new String[]{"to quit"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kenkasuru", new String[]{"to have a fight", "to quarrel"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shoukaisuru", new String[]{"to introduce"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chikokusuru", new String[]{"to be late (for an appointment)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryuugakusuru", new String[]{"to study abroad"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kyanpu", new String[]{"camp"}, "katakana", "", ""), 
                new JapaneseWord(" ", "doraibu", new String[]{"drive"}, "katakana", "", ""), 
                new JapaneseWord(" ", "biiru", new String[]{"beer"}, "katakana", "", ""), 
                new JapaneseWord(" ", "hosutofamirii", new String[]{"host family"}, "katakana", "", ""), 
                new JapaneseWord(" ", "ruumumeeto", new String[]{"roommate"}, "katakana", "", ""), 
                new JapaneseWord(" ", "saboru", new String[]{"to cut class", "to skip"}, "katakana", "", "")
            };
            
            var chapter12 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "ashi", new String[]{"leg", "foot"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "imi", new String[]{"meaning"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otearai", new String[]{"restroom"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onaka", new String[]{"stomach"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kaze", new String[]{"cold"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kanojo", new String[]{"girlfriend", "she"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kare", new String[]{"boyfriend", "he"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kion", new String[]{"temperature (of the weather)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kumori", new String[]{"cloudy weather"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shiai", new String[]{"match", "game"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "seiji", new String[]{"politics"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "seiseki", new String[]{"grade"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "seki", new String[]{"cough"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nodo", new String[]{"throat"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ha", new String[]{"teeth"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hana", new String[]{"flower"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hare", new String[]{"sunny weather"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "fuku", new String[]{"clothes"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "futsukayoi", new String[]{"hangover"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mono", new String[]{"thing (concrete object)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yuki", new String[]{"snow"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "youji", new String[]{"business to take care of"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "amai", new String[]{"sweet"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "itai", new String[]{"hurt", "painful"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "ooi", new String[]{"many"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "semai", new String[]{"narrow", "not spacious"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "tsugougawarui", new String[]{ "inconvenient", "to have a scheduling conflict"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "warui", new String[]{"bad"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "suteki", new String[]{"nice"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "aruku", new String[]{"to walk"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kazewohiku", new String[]{"to catch a cold"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kyoumigaaru", new String[]{"to be interested in"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nakusu", new String[]{"to lose (something)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "netsugaaru", new String[]{"to have a fever"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nodogakawaku", new String[]{"to become thirsty"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sekigaderu", new String[]{"to cough"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "wakareru", new String[]{"to break up", "to separate"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kinchousuru", new String[]{"to get nervous"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shinpaisuru", new String[]{"to worry"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "juusu", new String[]{"juice"}, "katakana", "", ""), 
                new JapaneseWord(" ", "purezento", new String[]{"present"}, "katakana", "", ""), 
                new JapaneseWord(" ", "hoomushikku", new String[]{"homesick"}, "katakana", "", ""), 
                new JapaneseWord(" ", "mainasu", new String[]{"minus"}, "katakana", "", "")
            };
            
            var chapter13 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "otaku", new String[]{"(someone's) home"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otona", new String[]{"adult"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gaikokugo", new String[]{"foreign language"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gakki", new String[]{"musical instrument"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "karate", new String[]{"karate"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kimono", new String[]{"kimono"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "koukoku", new String[]{"advertisement"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kotoba", new String[]{"language"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "zou", new String[]{"elephant"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "bukka", new String[]{"(consumer) prices"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "bunpou", new String[]{"grammar"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "boshuu", new String[]{"recruitment"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mise", new String[]{"shop", "store"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yakuza", new String[]{"yakuza", "gangster"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yakusoku", new String[]{"to keep a promise"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "watakushi", new String[]{"I (formal)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ureshii", new String[]{"glad"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kanashii", new String[]{"sad"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "karai", new String[]{"hot and spicy", "salty"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "sugoi", new String[]{"awesome", "incredible"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "chikai", new String[]{"close", "near"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "iroiro", new String[]{"various", "different kinds of"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "shiawase", new String[]{"happy (lasting happiness)"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "dame", new String[]{"no good"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "amu", new String[]{"to knit"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kasu", new String[]{"to lend", "to rent"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ganbaru", new String[]{"to do one's best", "to try hard"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "naku", new String[]{"to cry"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "migaku", new String[]{"to brush teeth", "to polish"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yakusokuwomamoru", new String[]{"to keep a promise"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kandousuru", new String[]{"to be moved", "to be touched"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ueitaa", new String[]{"waiter"}, "katakana", "", ""), 
                new JapaneseWord(" ", "karee", new String[]{"curry"}, "katakana", "", ""), 
                new JapaneseWord(" ", "gorufu", new String[]{"golf"}, "katakana", "", ""), 
                new JapaneseWord(" ", "baiorin", new String[]{"violin"}, "katakana", "", ""), 
                new JapaneseWord(" ", "baiku", new String[]{"motorcycle"}, "katakana", "", ""), 
                new JapaneseWord(" ", "repooto", new String[]{"(term) paper"}, "katakana", "", "")
            };
            
            var chapter14 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "ani", new String[]{"older brother"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ooyasan", new String[]{"landlord", "landlady"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okaeshi", new String[]{"return (as a token of gratitude)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okusan", new String[]{"(your/his) wife"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ojisan", new String[]{"uncle", "middle-aged man"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "obasan", new String[]{"aunt", "middle-aged woman"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "goshujin", new String[]{"(your/her) husband"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sara", new String[]{"plate", "dish"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "jikan", new String[]{"time"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nuigurumi", new String[]{"stuffed animal"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "fuufu", new String[]{"married couple", "husband and wife"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "manga", new String[]{"comic book"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mikan", new String[]{"mandarin", "orange"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "minasan", new String[]{"everyone", "all of you"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yubiwa", new String[]{"ring"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryoushin", new String[]{"parents"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "rirekisho", new String[]{"resume"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hoshii", new String[]{"to want"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kechi", new String[]{"stingy", "cheap"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "okuru", new String[]{"to send"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "niau", new String[]{"to look good (on somebody)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "akirameru", new String[]{"to give up"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ageru", new String[]{"to give (to others)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kureru", new String[]{"to give (me)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "dekiru", new String[]{"to come into existence", "to be made"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "soudansuru", new String[]{"to consult"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gurasu", new String[]{"tumbler", "glass"}, "katakana", "", ""), 
                new JapaneseWord(" ", "kurisumasu", new String[]{"Christmas"}, "katakana", "", ""), 
                new JapaneseWord(" ", "chiketto", new String[]{"ticket"}, "katakana", "", ""), 
                new JapaneseWord(" ", "chokoreeto", new String[]{"chocolate"}, "katakana", "", ""), 
                new JapaneseWord(" ", "toreenaa", new String[]{"sweat shirt"}, "katakana", "", ""), 
                new JapaneseWord(" ", "nekutai", new String[]{"necktie"}, "katakana", "", ""), 
                new JapaneseWord(" ", "barentaindee", new String[]{"st. Valentine's Day"}, "katakana", "", ""), 
                new JapaneseWord(" ", "bideokamera", new String[]{"camcorder"}, "katakana", "", ""), 
                new JapaneseWord(" ", "howaitodee", new String[]{"White Day"}, "katakana", "", ""), 
                new JapaneseWord(" ", "mafuraa", new String[]{"winter scarf"}, "katakana", "", ""), 
                new JapaneseWord(" ", "manshon", new String[]{"multistory apartment building", "condominium"}, "katakana", "", ""), 
                new JapaneseWord(" ", "rajio", new String[]{"radio"}, "katakana", "", "")
            };
            
            var chapter15 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "e", new String[]{"painting", "picture", "drawing"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "eigakan", new String[]{"movie theater"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gaikokujin", new String[]{"foreigner"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kagu", new String[]{"furniture"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "keiken", new String[]{"experience"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kekkonshiki", new String[]{"wedding"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "jishin", new String[]{"earthquake"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shimekiri", new String[]{"deadline"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shuukan", new String[]{"custom"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "zeikin", new String[]{"tax"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sotsugyoushiki", new String[]{"graduation ceremony"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "soba", new String[]{"soba", "Japanese buckwheat noodle"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chizu", new String[]{"map"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "denchi", new String[]{"battery"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "niwa", new String[]{"garden"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "bangumi", new String[]{"broadcast program"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "happyou", new String[]{"presentation"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hoken", new String[]{"insurance"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yotei", new String[]{"yotei"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryokan", new String[]{"Japanese inn"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "waribikiken", new String[]{"discount coupon"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hiroi", new String[]{"spacious", "wide"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "uru", new String[]{"to sell"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "orosu", new String[]{"to withdraw (money)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sagasu", new String[]{"to look for"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sasou", new String[]{"to invite"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shaberu", new String[]{"to chat"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsukiau", new String[]{"to date (someone)", "to keep company"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsuku", new String[]{"to arrive"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hokennihairu", new String[]{"to buy insurance"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kiwotsukeru", new String[]{"to be careful", "to be cautious"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shiraberu", new String[]{"to look into (a matter)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mieru", new String[]{"to be visible"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kankousuru", new String[]{"to do sightseeing"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "suru", new String[]{"to decide on (an item)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sotsugyousuru", new String[]{"to graduate"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yoyakusuru", new String[]{"to reserve"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "intaanetto", new String[]{"Internet"}, "katakana", "", ""), 
                new JapaneseWord(" ", "night club", new String[]{"kurabu"}, "katakana", "", ""), 
                new JapaneseWord(" ", "jaketto", new String[]{"jacket"}, "katakana", "", ""), 
                new JapaneseWord(" ", "puuru", new String[]{"swimming pool"}, "katakana", "", ""), 
                new JapaneseWord(" ", "petto", new String[]{"pet"}, "katakana", "", "")
            };
            
            var chapter16 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "ekiin", new String[]{"station attendant"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ookisa", new String[]{"size"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oya", new String[]{"parent"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kimatsushiken", new String[]{"final exam"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kenkyuu", new String[]{"research"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gomi", new String[]{"garbage"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "satou", new String[]{"sugar"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shougakukin", new String[]{"scholarship"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shinseki", new String[]{"relatives"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "suisenjou", new String[]{"letter of recommendation"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "daigakuin", new String[]{"graduate school"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "taifuu", new String[]{"typhoon"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hi", new String[]{"day"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "michi", new String[]{"road", "way", "directions"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mezamashidokei", new String[]{"alarm clock"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kitanai", new String[]{"dirty"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "okosu", new String[]{"to wake (someone) up"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ogoru", new String[]{"to treat (someone) to a meal"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ochikomu", new String[]{"to get depressed"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "komaru", new String[]{"to have difficulty"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "dasu", new String[]{"to hand in (something)", "to take (something) out"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsureteiku", new String[]{"to take (someone) to (a place)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "naosu", new String[]{"to correct", "to fix"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "michinimayou", new String[]{"to become lost", "to lose one's way"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mitsukaru", new String[]{"to be found"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mukaeniiku", new String[]{"to go to pick up"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yakusu", new String[]{"to translate"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "warau", new String[]{"to laugh"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "aironwokakeru", new String[]{"to iron (clothes)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "atsumeru", new String[]{"to collect"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ireru", new String[]{"to put (something) in"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "noriokureru", new String[]{"to miss (a train, bus, etc.)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "miseru", new String[]{"to show"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "asanebousuru", new String[]{"to oversleep"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "annaisuru", new String[]{"to show (someone) around"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "setsumeisuru", new String[]{"to explain"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mukaenikuru", new String[]{"to come to pick up"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "fairu", new String[]{"file", "portfolio"}, "katakana", "", "")
            };
            
            var chapter17 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "okyakusan", new String[]{"guest", "visitor", "client", "customer"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otoko", new String[]{"man"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oyu", new String[]{"hot water"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onna", new String[]{"woman"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kagi", new String[]{"lock", "key"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kaji", new String[]{"fire"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kami", new String[]{"paper"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kyuuryou", new String[]{"salary"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "saitei", new String[]{"the lowest", "the worst"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "zangyou", new String[]{"overtime work"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shushou", new String[]{"prime minister"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "takarakuji", new String[]{"lottery"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chigai", new String[]{"difference"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "doubutsuen", new String[]{"zoo"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hige", new String[]{"beard"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "himitsu", new String[]{"secret"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryou", new String[]{"dormitory"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ryokougaisha", new String[]{"travel agency"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "abunai", new String[]{"dangerous"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "urayamashii", new String[]{"envious"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "sukunai", new String[]{"a little", "a few"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "tsuyoi", new String[]{"strong"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "erabu", new String[]{"to choose", "to select"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oyuwowakasu", new String[]{"to boil water"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kamiwotokasu", new String[]{"to comb one's hair"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "komu", new String[]{"to get crowded"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "takarakujiniataru", new String[]{"to win a lottery"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nugu", new String[]{"to take off (clothes)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "higewosoru", new String[]{"to shave one's beard"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ireru", new String[]{"to make tea, coffee, etc."}, "hiragana", "", ""), 
                new JapaneseWord(" ", "umareru", new String[]{"to be born"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kagiwokakeru", new String[]{"to lock"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tariru", new String[]{"to be sufficient", "to be enough"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nareru", new String[]{"to get used to..."}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oinorisuru", new String[]{"to pray"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "keshousuru", new String[]{"to put makeup on"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shuushokusuru", new String[]{"to get a full-time job (at...)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "suru", new String[]{"to wear small items (necktie, watch, etc.)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "rikonsuru", new String[]{"to get a divorce"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kontakuto", new String[]{"contact lenses"}, "katakana", "", ""), 
                new JapaneseWord(" ", "sarariiman", new String[]{"salary man"}, "katakana", "", ""), 
                new JapaneseWord(" ", "shoppingumooru", new String[]{"shopping mall"}, "katakana", "", ""), 
                new JapaneseWord(" ", "supuun", new String[]{"spoon"}, "katakana", "", ""), 
                new JapaneseWord(" ", "nyuusu", new String[]{"news"}, "katakana", "", ""), 
                new JapaneseWord(" ", "panda", new String[]{"panda"}, "katakana", "", ""), 
                new JapaneseWord(" ", "buutsu", new String[]{"boots"}, "katakana", "", ""), 
                new JapaneseWord(" ", "hiitaa", new String[]{"heater"}, "katakana", "", "")
            };
            
            var chapter18 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "ato", new String[]{"the rest"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shoyuu", new String[]{"soy sauce"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "soto", new String[]{"outside"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nikki", new String[]{"diary"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mushi", new String[]{"insect"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yachin", new String[]{"rent"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yuugata", new String[]{"evening"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "rusubandenwa", new String[]{"answering machine"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "reizouko", new String[]{"refrigerator"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "rousoku", new String[]{"candle"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "akarui", new String[]{"bright"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kibungawarui", new String[]{"to feel sick"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "kurai", new String[]{"dark"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "hazukashii", new String[]{"embarassing", "to feel embarassed"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "aku", new String[]{"(something) opens"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ayamaru", new String[]{"to apologize"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "osu", new String[]{"to press", "to push"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "otosu", new String[]{"to drop (something)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oyugawaku", new String[]{"water boils"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "korobu", new String[]{"to fall down"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kowasu", new String[]{"to break (something)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "saku", new String[]{"to bloom"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shimaru", new String[]{"(something) closes"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tasukaru", new String[]{"to be saved", "to be helped"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tanomu", new String[]{"to ask (a favor)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsuku", new String[]{"(something) turns on"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yogosu", new String[]{"to make dirty"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ochiru", new String[]{"(something) drops"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "katatzukeru", new String[]{"to tidy up"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kangaeru", new String[]{"to think (about)", "to consider"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kieru", new String[]{"(something) goes off", "(something) disappears"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kowareru", new String[]{"(something) breaks"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yogoreru", new String[]{"to become dirty"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chuumonsuru", new String[]{"to place an order"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "eakon", new String[]{"air conditioner"}, "katakana", "", ""), 
                new JapaneseWord(" ", "kaatin", new String[]{"curtain"}, "katakana", "", ""), 
                new JapaneseWord(" ", "kusshon", new String[]{"cushion"}, "katakana", "", ""), 
                new JapaneseWord(" ", "shanpuu", new String[]{"shampoo"}, "katakana", "", ""), 
                new JapaneseWord(" ", "suicchi", new String[]{"switch"}, "katakana", "", ""), 
                new JapaneseWord(" ", "suupu", new String[]{"soup"}, "katakana", "", ""), 
                new JapaneseWord(" ", "sukaato", new String[]{"skirt"}, "katakana", "", ""), 
                new JapaneseWord(" ", "sofa", new String[]{"sofa"}, "katakana", "", ""), 
                new JapaneseWord(" ", "taoru", new String[]{"towel"}, "katakana", "", ""), 
                new JapaneseWord(" ", "poppukoon", new String[]{"popcorn"}, "katakana", "", "") 
            };
            
            var chapter19 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "okusama", new String[]{"(your/his) wife"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okosan", new String[]{"(your/their) child"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "orei", new String[]{"expression of gratitude"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "keigo", new String[]{"honorific language"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kochira", new String[]{"this way (polite)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shucchou", new String[]{"business trip"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shurui", new String[]{"a kind", "a sort"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "seikaku", new String[]{"personality"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chuugakusei", new String[]{"junior high school student"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "dochira", new String[]{"where (polite)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "namakemono", new String[]{"lazy person"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nayami", new String[]{"worry"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hazukashigariya", new String[]{"shy person"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hanashi", new String[]{"chat", "talk"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "buchou", new String[]{"department manager"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "bunka", new String[]{"culture"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "machigai", new String[]{"mistake"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nakagaii", new String[]{"be on good terms", "to be close with", "to get along well"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "majime", new String[]{"serious", "sober", "diligent"}, "hiragana", "na", ""), 
                new JapaneseWord(" ", "irassharu", new String[]{"honorific expression for iku, kuru, and iru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okuru", new String[]{"to walk/drive (someone)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okoru", new String[]{"to get angry"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ossharu", new String[]{"honorific expression for iu"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oyasumininaru", new String[]{"honorific expression for neru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kimaru", new String[]{"to be decided"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kudasaru", new String[]{"honorific expression for kureru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "goranninaru", new String[]{"honorific expression for miru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shiriau", new String[]{"to get acquainted with"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "~teirassharu", new String[]{"honoritic expression for ~teiru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "nasaru", new String[]{"honorific expression for suru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hikkosu", new String[]{"to move (to another place to live)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "meshiagaru", new String[]{"honorific expression for taberu and nomu"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yobu", new String[]{"to call (one's name)", "to invite"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "yoru", new String[]{"to stop by"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "okureru", new String[]{"to become late"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kakeru", new String[]{"to sit down"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hareru", new String[]{"to become sunny"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "moteru", new String[]{"to be popular (in terms of romantic interest)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "enryosuru", new String[]{"to hold back for the time being", "to refrain from"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gochisousuru", new String[]{"to treat/invite (someone) to a meal"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shoutaisuru", new String[]{"to invite someone (to an event/place)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "chuuisuru", new String[]{"to watch out", "to give warning"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "hanashiwosuru", new String[]{"to have a talk"}, "hiragana", "", "")
            };
            
            var chapter20 = new JapaneseWord[]
            {
                new JapaneseWord(" ", "achira", new String[]{"that way (polite)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "uchuujin", new String[]{"space alien"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oto", new String[]{"sound"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "onigiri", new String[]{"rice ball"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kakarinomono", new String[]{"our person in charge"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kado", new String[]{"corner"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kuukou", new String[]{"airport"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ji", new String[]{"letter", "character"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shiten", new String[]{"branch office"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shumi", new String[]{"hobby", "pastime"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shousetsu", new String[]{"novel"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "shingou", new String[]{"traffic light"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sensu", new String[]{"fan"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsuki", new String[]{"moon"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "denshijisho", new String[]{"electronic dictionary"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "~ya", new String[]{"~shop"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "omoi", new String[]{"heavy", "serious (illness)"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "karui", new String[]{"light"}, "hiragana", "i", ""), 
                new JapaneseWord(" ", "itasu", new String[]{"extra-modest expression for suru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "itadaku", new String[]{"extra-modest expression for taberu and nomu"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "itadaku", new String[]{"humble expression for morau"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "ukagau", new String[]{"to humbly visit", "to humbly ask"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "oru", new String[]{"extra-modest expression for iru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "gozaru", new String[]{"extra-modest expression for aru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "~teoru", new String[]{"extra-modest expression for ~teiru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "~degozaru", new String[]{"extra-modest expression for desu"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mairu", new String[]{"extra-modest expression for iku and kuru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "magaru", new String[]{"to turn (right/left)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mousu", new String[]{"extra-modest expression for iu"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "modoru", new String[]{"to return", "to come back"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "kikoeru", new String[]{"to be audible"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "sashiageru", new String[]{"humble expression for ageru"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "tsutaeru", new String[]{"to convey (message)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "mataseru", new String[]{"to keep (someone) waiting"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "koukansuru", new String[]{"to exchange"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "seikatsusuru", new String[]{"to lead a life"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "henpinsuru", new String[]{"to return (merchandise)"}, "hiragana", "", ""), 
                new JapaneseWord(" ", "anime", new String[]{"animation"}, "katakana", "", ""), 
                new JapaneseWord(" ", "suniikaa", new String[]{"sneakers"}, "katakana", "", ""), 
                new JapaneseWord(" ", "doitsu", new String[]{"Germany"}, "katakana", "", ""), 
                new JapaneseWord(" ", "haihiiru", new String[]{"high heels"}, "katakana", "", "")
            };

        }
    }
}