using System;
using System.Collections;

namespace Japanese_Review
{
    /*
     * The Japanese Word class holds the following information:
     * japanese - the word written in japanese
     * romaji - conversion of the japanese word to latin
     * english - a list of english definitions of the word
     * writing - the syllabic writing for the word (hiragana or katakana)
     * kanji - how the word is represented with kanji, if I have learned it
     */
    public class JapaneseWord
    {
        private string japanese;
        private string romaji;
        private string[] english;
        private string writing;
        private string adjective;
        private string kanji;

        /* JapaneseWord constructor */
        public JapaneseWord(string japanese, string romaji, string[] english, string writing, string adjective,
            string kanji)
        {
            this.japanese = japanese;
            this.romaji = romaji;
            this.english = english;
            this.writing = writing;
            this.adjective = adjective;
            this.kanji = kanji;
        }

        /* public gets */
        public string Japanese => japanese;
        public string Romaji => romaji;
        public string[] English => english;
        public string Writing => writing;
        public string Adjective => adjective;
        public string Kanji => kanji;

        /*
         *  Initialize 20 chapters of vocab from the Genki I & II textbooks
         *
            var chapter = new JapaneseWord[]
            {
                new JapaneseWord("", new string[]{""}, "hiragana", "", ""), 
                new JapaneseWord("", new string[]{""}, "katakana", "", ""), 
            };
         */
        public static Hashtable initGenki()
        {
            var genkiVocab = new Hashtable();
            
            
            var chapter1 = new JapaneseWord[]
            {
                new JapaneseWord("あの", "ano", new string[] {"um..."}, "hiragana", "", ""),
                new JapaneseWord("いま", "ima", new string[] {"now"}, "hiragana", "", ""),
                new JapaneseWord("えいご", "eigo", new string[] {"English"}, "hiragana", "", ""),
                new JapaneseWord("ええ", "ee", new string[] {"yes"}, "hiragana", "", ""),
                new JapaneseWord("がくせい", "gakusei", new string[] {"student"}, "hiragana", "", ""),
                new JapaneseWord("~ご", "~go", new string[] {"language"}, "hiragana", "", ""),
                new JapaneseWord("こうこう", "koukou", new string[] {"high school"}, "hiragana", "", ""),
                new JapaneseWord("ごご", "gogo", new string[] {"P.M."}, "hiragana", "", ""),
                new JapaneseWord("ごぜん", "gozen", new string[] {"A.M"}, "hiragana", "", ""),
                new JapaneseWord("~さい", "~sai", new string[] {"~years old"}, "hiragana", "", ""),
                new JapaneseWord("~さん", "~san", new string[] {"Mr.", "Mrs."}, "hiragana", "", ""),
                new JapaneseWord("~じ", "~ji", new string[] {"o'clock"}, "hiragana", "", ""),
                new JapaneseWord("~じん", "~jin", new string[] {"~people"}, "hiragana", "", ""),
                new JapaneseWord("せんこう", "senkou", new string[] {"major"}, "hiragana", "", ""),
                new JapaneseWord("せんせい", "sensei", new string[] {"teacher", "professor"}, "hiragana", "", ""),
                new JapaneseWord("そうです", "sou desu", new string[] {"that's right"}, "hiragana", "", ""),
                new JapaneseWord("そうですか", "sou desu ka", new string[] {"I see", "is that so?"}, "hiragana", "", ""),
                new JapaneseWord("だいがく", "daigaku", new string[] {"college", "university"}, "hiragana", "", ""),
                new JapaneseWord("でんわ", "denwa", new string[] {"telephone"}, "hiragana", "", ""),
                new JapaneseWord("ともだち", "tomodachi", new string[] {"friend"}, "hiragana", "", ""),
                new JapaneseWord("まなえ", "namae", new string[] {"name"}, "hiragana", "", ""),
                new JapaneseWord("にほん", "nihon", new string[] {"Japan"}, "hiragana", "", ""),
                new JapaneseWord("~ねんせい", "~nensei", new string[] {"~year student"}, "hiragana", "", ""),
                new JapaneseWord("はい", "hai", new string[] {"yes"}, "hiragana", "", ""),
                new JapaneseWord("はん", "han", new string[] {"half"}, "hiragana", "", ""),
                new JapaneseWord("ばんごう", "bangou", new string[] {"number"}, "hiragana", "", ""),
                new JapaneseWord("りゅうがくせい", "ryuugakusei", new string[] {"international student"}, "hiragana", "", ""),
                new JapaneseWord("わたし", "watashi", new string[] {"I"}, "hiragana", "", ""),
                new JapaneseWord("ちゅうごく", "Chuugoku", new string[] {"China"}, "hiragana", "", ""),
                new JapaneseWord("かんこく", "Kankoku", new string[] {"Korea"}, "hiragana", "", ""),
                new JapaneseWord("かがく", "kagaku", new string[] {"science"}, "hiragana", "", ""),
                new JapaneseWord("けいざい", "keizai", new string[] {"economics"}, "hiragana", "", ""),
                new JapaneseWord("こくさいかんけい", "kokusaikankei", new string[] {"international relations"}, "hiragana", "", ""),
                new JapaneseWord("じんるいがく", "jinruigaku", new string[] {"anthropology"}, "hiragana", "", ""),
                new JapaneseWord("せいじ", "seeji", new string[] {"politics"}, "hiragana", "", ""),
                new JapaneseWord("ぶんがく", "bungaku", new string[] {"literature"}, "hiragana", "", ""),
                new JapaneseWord("れきし", "rekishi", new string[] {"history"}, "hiragana", "", ""),
                new JapaneseWord("しごと", "shigoto", new string[] {"job", "work", "occupation"}, "hiragana", "", ""),
                new JapaneseWord("いしゃ", "isha", new string[] {"doctor"}, "hiragana", "", ""),
                new JapaneseWord("かいしゃいん", "kaishain", new string[] {"office worker"}, "hiragana", "", ""),
                new JapaneseWord("こうこうせい", "koukousei", new string[] {"high school student"}, "hiragana", "", ""),
                new JapaneseWord("しゅふ", "shufu", new string[] {"housewife"}, "hiragana", "", ""),
                new JapaneseWord("だいがくいんせい", "daigakuinsei", new string[] {"graduate student"}, "hiragana", "", ""),
                new JapaneseWord("だいがくせい", "daigakusei", new string[] {"college student"}, "hiragana", "", ""),
                new JapaneseWord("べんごし", "bengoshi", new string[] {"lawyer"}, "hiragana", "", ""),
                new JapaneseWord("おかあさん", "okaasan", new string[] {"mother"}, "hiragana", "", ""),
                new JapaneseWord("おとうさん", "otousan", new string[] {"father"}, "hiragana", "", ""),
                new JapaneseWord("おねえさん", "oneesan", new string[] {"older sister"}, "hiragana", "", ""),
                new JapaneseWord("おにいさん", "oniisan", new string[] {"older brother"}, "hiragana", "", ""),
                new JapaneseWord("いもうと", "imouto", new string[] {"younger sister"}, "hiragana", "", ""),
                new JapaneseWord("おとうと", "otouto", new string[] {"younger brother"}, "hiragana", "", ""),
                new JapaneseWord("アメリカ", "Amerika", new string[] {"U.S.A."}, "katakana", "", ""),
                new JapaneseWord("イギリス", "Igirisu", new string[] {"Britain"}, "katakana", "", ""),
                new JapaneseWord("オーストラリア", "Oosutoraria", new string[] {"Australia"}, "katakana", "", ""),
                new JapaneseWord("スウェーデン", "Suweeden", new string[] {"Sweden"}, "katakana", "", ""),
                new JapaneseWord("コンピューター", "konpyuutaa", new string[] {"computer"}, "katakana", "", ""),
                new JapaneseWord("ビジネス", "bijinesu", new string[] {"business"}, "katakana", "", "")
            };

            var chapter2 = new JapaneseWord[]
            {
                new JapaneseWord("これ", "kore", new string[] {"this one"}, "hiragana", "", ""),
                new JapaneseWord("それ", "sore", new string[] {"that one"}, "hiragana", "", ""),
                new JapaneseWord("あれ", "are", new string[] {"that one over there"}, "hiragana", "", ""),
                new JapaneseWord("どれ", "dore", new string[] {"which one"}, "hiragana", "", ""),
                new JapaneseWord("この", "kono", new string[] {"this..."}, "hiragana", "", ""),
                new JapaneseWord("その", "sono", new string[] {"that..."}, "hiragana", "", ""),
                new JapaneseWord("あの", "ano", new string[] {"that... over there"}, "hiragana", "", ""),
                new JapaneseWord("どの", "dono", new string[] {"which..."}, "hiragana", "", ""),
                new JapaneseWord("ここ", "koko", new string[] {"here"}, "hiragana", "", ""),
                new JapaneseWord("そこ", "soko", new string[] {"there"}, "hiragana", "", ""),
                new JapaneseWord("あそこ", "asoko", new string[] {"over there"}, "hiragana", "", ""),
                new JapaneseWord("どこ", "doko", new string[] {"where"}, "hiragana", "", ""),
                new JapaneseWord("だれ", "dare", new string[] {"who"}, "hiragana", "", ""),
                new JapaneseWord("おいしい", "oishii", new string[] {"delicious"}, "hiragana", "i", ""),
                new JapaneseWord("さかな", "sakana", new string[] {"fish"}, "hiragana", "", ""),
                new JapaneseWord("とんかつ", "tonkatsu", new string[] {"pork cutlet"}, "hiragana", "", ""),
                new JapaneseWord("にく", "niku", new string[] {"meat"}, "hiragana", "", ""),
                new JapaneseWord("やさい", "yasai", new string[] {"vegetable"}, "hiragana", "", ""),
                new JapaneseWord("えんぴつ", "enpitsu", new string[] {"pencil"}, "hiragana", "", ""),
                new JapaneseWord("かさ", "kasa", new string[] {"umbrella"}, "hiragana", "", ""),
                new JapaneseWord("かばん", "kaban", new string[] {"bag"}, "hiragana", "", ""),
                new JapaneseWord("くつ", "kutsu", new string[] {"shoes"}, "hiragana", "", ""),
                new JapaneseWord("さいふ", "saifu", new string[] {"wallet"}, "hiragana", "", ""),
                new JapaneseWord("じしょ", "jisho", new string[] {"dictionary"}, "hiragana", "", ""),
                new JapaneseWord("じてんしゃ", "jitensha", new string[] {"bicycle"}, "hiragana", "", ""),
                new JapaneseWord("しんぶん", "shinbun", new string[] {"newspaper"}, "hiragana", "", ""),
                new JapaneseWord("とけい", "tokei", new string[] {"watch", "clock"}, "hiragana", "", ""),
                new JapaneseWord("ぼうし", "boushi", new string[] {"hat", "cap"}, "hiragana", "", ""),
                new JapaneseWord("ほん", "hon", new string[] {"book"}, "hiragana", "", ""),
                new JapaneseWord("きっさてん", "kissaten", new string[] {"cafe"}, "hiragana", "", ""),
                new JapaneseWord("ぎんこう", "ginkou", new string[] {"bank"}, "hiragana", "", ""),
                new JapaneseWord("としょかん", "toshokan", new string[] {"library"}, "hiragana", "", ""),
                new JapaneseWord("ゆうびんきょく", "yuubinkyoku", new string[] {"post office"}, "hiragana", "", ""),
                new JapaneseWord("いくら", "ikura", new string[] {"how much"}, "hiragana", "", ""),
                new JapaneseWord("~えん", "~en", new string[] {"~yen"}, "hiragana", "", ""),
                new JapaneseWord("たかい", "takai", new string[] {"expensive", "high"}, "hiragana", "i", ""),
                new JapaneseWord("メニュー", "menyuu", new string[] {"menu"}, "katakana", "", ""),
                new JapaneseWord("ジーンズ", "jiinzu", new string[] {"jeans"}, "katakana", "", ""),
                new JapaneseWord("Tシャツ", "tiishatsu", new string[] {"T-shirt"}, "katakana", "", ""),
                new JapaneseWord("ノート", "nooto", new string[] {"notebook"}, "katakana", "", ""),
                new JapaneseWord("ペン", "pen", new string[] {"pen"}, "katakana", "", ""),
                new JapaneseWord("トイレ", "toire", new string[] {"toilet", "restroom"}, "katakana", "", "")
            };

            var chapter3 = new JapaneseWord[]
            {
                new JapaneseWord("えいが", "eiga", new string[] {"movie"}, "hiragana", "", ""),
                new JapaneseWord("おんがく", "ongaku", new string[] {"music"}, "hiragana", "", ""),
                new JapaneseWord("ざっし", "zasshi", new string[] {"magazine"}, "hiragana", "", ""),
                new JapaneseWord("あさごはん", "asagohan", new string[] {"breakfast"}, "hiragana", "", ""),
                new JapaneseWord("おさけ", "osake", new string[] {"sake", "alcohol"}, "hiragana", "", ""),
                new JapaneseWord("おちゃ", "ocha", new string[] {"tea"}, "hiragana", "", ""),
                new JapaneseWord("ばんごはん", "bangohan", new string[] {"dinner"}, "hiragana", "", ""),
                new JapaneseWord("ひるごはん", "hirugohan", new string[] {"lunch"}, "hiragana", "", ""),
                new JapaneseWord("みず", "mizu", new string[] {"water"}, "hiragana", "", ""),
                new JapaneseWord("いえ", "ie", new string[] {"home", "house"}, "hiragana", "", ""),
                new JapaneseWord("うち", "uchi", new string[] {"home", "house", "my place"}, "hiragana", "", ""),
                new JapaneseWord("がっこう", "gakkou", new string[] {"school"}, "hiragana", "", ""),
                new JapaneseWord("あさ", "asa", new string[] {"morning"}, "hiragana", "", ""),
                new JapaneseWord("あした", "ashita", new string[] {"tomorrow"}, "hiragana", "", ""),
                new JapaneseWord("いつ", "itsu", new string[] {"when"}, "hiragana", "", ""),
                new JapaneseWord("きょう", "kyou", new string[] {"today"}, "hiragana", "", ""),
                new JapaneseWord("~ごろ", "~goro", new string[] {"at about..."}, "hiragana", "", ""),
                new JapaneseWord("こんばん", "konban", new string[] {"tonight"}, "hiragana", "", ""),
                new JapaneseWord("しゅうまつ", "shuumatsu", new string[] {"weekend"}, "hiragana", "", ""),
                new JapaneseWord("どようび", "doyoubi", new string[] {"Saturday"}, "hiragana", "", ""),
                new JapaneseWord("にちようび", "nichiyoubi", new string[] {"Sunday"}, "hiragana", "", ""),
                new JapaneseWord("まいにち", "mainichi", new string[] {"every day"}, "hiragana", "", ""),
                new JapaneseWord("まいばん", "maiban", new string[] {"every night"}, "hiragana", "", ""),
                new JapaneseWord("いく", "iku", new string[] {"to go"}, "hiragana", "", ""),
                new JapaneseWord("かえる", "kaeru", new string[] {"to go back", "to return"}, "hiragana", "", ""),
                new JapaneseWord("きく", "kiku", new string[] {"to listen", "to hear"}, "hiragana", "", ""),
                new JapaneseWord("のむ", "nomu", new string[] {"to drink"}, "hiragana", "", ""),
                new JapaneseWord("はなす", "hanasu", new string[] {"to speak", "to talk"}, "hiragana", "", ""),
                new JapaneseWord("よむ", "yomu", new string[] {"to read"}, "hiragana", "", ""),
                new JapaneseWord("おきる", "okiru", new string[] {"to get up"}, "hiragana", "", ""),
                new JapaneseWord("たべる", "taberu", new string[] {"to eat"}, "hiragana", "", ""),
                new JapaneseWord("ねる", "neru", new string[] {"to sleep", "to go to sleep"}, "hiragana", "", ""),
                new JapaneseWord("みる", "miru", new string[] {"to see", "to look at", "to watch"}, "hiragana", "", ""),
                new JapaneseWord("くる", "kuru", new string[] {"to come"}, "hiragana", "", ""),
                new JapaneseWord("する", "suru", new string[] {"to do"}, "hiragana", "", ""),
                new JapaneseWord("べんきょうする", "benkyousuru", new string[] {"to study"}, "hiragana", "", ""),
                new JapaneseWord("いい", "ii", new string[] {"good"}, "hiragana", "i", ""),
                new JapaneseWord("はやい", "hayai", new string[] {"early"}, "hiragana", "i", ""),
                new JapaneseWord("あまり", "amari", new string[] {"not much"}, "hiragana", "", ""),
                new JapaneseWord("ぜんぜん", "zenzen", new string[] {"not at all"}, "hiragana", "", ""),
                new JapaneseWord("たいてい", "taitei", new string[] {"usually"}, "hiragana", "", ""),
                new JapaneseWord("ちょっと", "chotto", new string[] {"a little"}, "hiragana", "", ""),
                new JapaneseWord("ときどき", "tokidoki", new string[] {"sometimes"}, "hiragana", "", ""),
                new JapaneseWord("よく", "yoku", new string[] {"often", "much"}, "hiragana", "", ""),
                new JapaneseWord("スポツ", "supotsu", new string[] {"sports"}, "katakana", "", ""),
                new JapaneseWord("デート", "deeto", new string[] {"date"}, "katakana", "", ""),
                new JapaneseWord("テニス", "tenisu", new string[] {"tennis"}, "katakana", "", ""),
                new JapaneseWord("テレビ", "terebi", new string[] {"TV"}, "katakana", "", ""),
                new JapaneseWord("アイスクレーム", "aisukureemu", new string[] {"ice cream"}, "katakana", "", ""),
                new JapaneseWord("コーヒー", "koohii", new string[] {"coffee"}, "katakana", "", ""),
                new JapaneseWord("ハンバーガー", "hanbaagaa", new string[] {"hamburger"}, "katakana", "", "")
            };

            var chapter4 = new JapaneseWord[]
            {
                new JapaneseWord("かいもの", "kaimono", new string[] {"shopping"}, "hiragana", "", ""),
                new JapaneseWord("あなた", "anata", new string[] {"you"}, "hiragana", "", ""),
                new JapaneseWord("いす", "isu", new string[] {"chair"}, "hiragana", "", ""),
                new JapaneseWord("いぬ", "inu", new string[] {"dog"}, "hiragana", "", ""),
                new JapaneseWord("おみやげ", "omiyage", new string[] {"souvenir"}, "hiragana", "", ""),
                new JapaneseWord("こども", "kodomo", new string[] {"child"}, "hiragana", "", ""),
                new JapaneseWord("ごはん", "gohan", new string[] {"rice", "meal"}, "hiragana", "", ""),
                new JapaneseWord("しゃしん", "shashin", new string[] {"picture", "photo", "photograph"}, "hiragana", "", ""),
                new JapaneseWord("つくえ", "tsukue", new string[] {"desk"}, "hiragana", "", ""),
                new JapaneseWord("てがみ", "tegami", new string[] {"letter"}, "hiragana", "", ""),
                new JapaneseWord("ねこ", "neko", new string[] {"cat"}, "hiragana", "", ""),
                new JapaneseWord("ひと", "hito", new string[] {"person"}, "hiragana", "", ""),
                new JapaneseWord("おてら", "otera", new string[] {"temple"}, "hiragana", "", ""),
                new JapaneseWord("こうえん", "kouen", new string[] {"park"}, "hiragana", "", ""),
                new JapaneseWord("びょういん", "byouin", new string[] {"hospital"}, "hiragana", "", ""),
                new JapaneseWord("ほんや", "honya", new string[] {"bookstore"}, "hiragana", "", ""),
                new JapaneseWord("まち", "machi", new string[] {"town", "city"}, "hiragana", "", ""),
                new JapaneseWord("きのう", "kinou", new string[] {"yesterday"}, "hiragana", "", ""),
                new JapaneseWord("~じかん", "~jikan", new string[] {"~hours"}, "hiragana", "", ""),
                new JapaneseWord("せんしゅう", "senshuu", new string[] {"last week"}, "hiragana", "", ""),
                new JapaneseWord("とき", "toki", new string[] {"when...", "at the time of..."}, "hiragana", "", ""),
                new JapaneseWord("げつようび", "getsuyoubi", new string[] {"Monday"}, "hiragana", "", ""),
                new JapaneseWord("かようび", "kayoubi", new string[] {"Tuesday"}, "hiragana", "", ""),
                new JapaneseWord("すいようび", "suiyoubi", new string[] {"Wednesday"}, "hiragana", "", ""),
                new JapaneseWord("もくようび", "mokuyoubi", new string[] {"Thursday"}, "hiragana", "", ""),
                new JapaneseWord("きにょうび", "kinyoubi", new string[] {"Friday"}, "hiragana", "", ""),
                new JapaneseWord("あう", "au", new string[] {"to meet", "to see a person"}, "hiragana", "", ""),
                new JapaneseWord("ある", "aru", new string[] {"to exist", "there is..."}, "hiragana", "", ""),
                new JapaneseWord("かう", "kau", new string[] {"to buy"}, "hiragana", "", ""),
                new JapaneseWord("かく", "kaku", new string[] {"to write", "to paint"}, "hiragana", "", ""),
                new JapaneseWord("とる", "toru", new string[] {"to take", "to get a grade"}, "hiragana", "", ""),
                new JapaneseWord("まつ", "matsu", new string[] {"to wait"}, "hiragana", "", ""),
                new JapaneseWord("わかる", "wakaru", new string[] {"to understand"}, "hiragana", "", ""),
                new JapaneseWord("いる", "iru", new string[] {"to exist", "is in...", "stays at..."}, "hiragana", "", ""),
                new JapaneseWord("あるばいと", "arubaito", new string[] {"part-time job"}, "katakana", "", ""),
                new JapaneseWord("クラス", "kurasu", new string[] {"class"}, "katakana", "", ""),
                new JapaneseWord("パン", "pan", new string[] {"bread"}, "katakana", "", ""),
                new JapaneseWord("メール", "meeru", new string[] {"e-mail"}, "katakana", "", ""),
                new JapaneseWord("スーパー", "suupaa", new string[] {"supermarket"}, "katakana", "", ""),
                new JapaneseWord("デパート", "depaato", new string[] {"department store"}, "katakana", "", ""),
                new JapaneseWord("バステイ", "basutei", new string[] {"bus stop"}, "katakana", "", ""),
                new JapaneseWord("ホテル", "hoteru", new string[] {"hotel"}, "katakana", "", ""),
                new JapaneseWord("レストラン", "resutoran", new string[] {"restaurant"}, "katakana", "", "")
            };

            var chapter5 = new JapaneseWord[]
            {
                new JapaneseWord("うみ", "umi", new string[] {"sea"}, "hiragana", "", ""),
                new JapaneseWord("きって", "kitte", new string[] {"postal stamps"}, "hiragana", "", ""),
                new JapaneseWord("きっぷ", "kippu", new string[] {"ticket"}, "hiragana", "", ""),
                new JapaneseWord("しゅくだい", "shukudai", new string[] {"homework"}, "hiragana", "", ""),
                new JapaneseWord("たべもの", "tabemono", new string[] {"food"}, "hiragana", "", ""),
                new JapaneseWord("たんじょうぶ", "tanjoubi", new string[] {"birthday"}, "hiragana", "", ""),
                new JapaneseWord("てんき", "tenki", new string[] {"weather"}, "hiragana", "", ""),
                new JapaneseWord("のみもの", "nomimono", new string[] {"drink"}, "hiragana", "", ""),
                new JapaneseWord("はがき", "hagaki", new string[] {"postcard"}, "hiragana", "", ""),
                new JapaneseWord("ひこうき", "hikouki", new string[] {"airplane"}, "hiragana", "", ""),
                new JapaneseWord("へや", "heya", new string[] {"room"}, "hiragana", "", ""),
                new JapaneseWord("ぼく", "boku", new string[] {"I"}, "hiragana", "", ""),
                new JapaneseWord("やすみ", "yasumi", new string[] {"holiday", "day off", "absence"}, "hiragana", "", ""),
                new JapaneseWord("りょこう", "ryokou", new string[] {"travel"}, "hiragana", "", ""),
                new JapaneseWord("あたらしい", "atarashii", new string[] {"new"}, "hiragana", "i", ""),
                new JapaneseWord("あつい", "atsui", new string[] {"hot"}, "hiragana", "i", ""),
                new JapaneseWord("いそがしい", "isogashii", new string[] {"busy"}, "hiragana", "i", ""),
                new JapaneseWord("おおきい", "ookii", new string[] {"large"}, "hiragana", "i", ""),
                new JapaneseWord("おもしろい", "omoshiroi", new string[] {"interesting", "funny"}, "hiragana", "i", ""),
                new JapaneseWord("かっこいい", "kakkoii", new string[] {"cool", "good-looking"}, "hiragana", "i", ""),
                new JapaneseWord("こわい", "kowai", new string[] {"frightening"}, "hiragana", "i", ""),
                new JapaneseWord("さむい", "samui", new string[] {"cold"}, "hiragana", "i", ""),
                new JapaneseWord("たのしい", "tanoshii", new string[] {"fun"}, "hiragana", "i", ""),
                new JapaneseWord("ちいさい", "chiisai", new string[] {"small"}, "hiragana", "i", ""),
                new JapaneseWord("つまらない", "tsumaranai", new string[] {"boring"}, "hiragana", "i", ""),
                new JapaneseWord("ふるい", "furui", new string[] {"old"}, "hiragana", "i", ""),
                new JapaneseWord("むずかしい", "muzukashii", new string[] {"difficult"}, "hiragana", "i", ""),
                new JapaneseWord("やさしい", "yasashii", new string[] {"easy", "kind"}, "hiragana", "i", ""),
                new JapaneseWord("やすい", "yasui", new string[] {"inexpensive", "cheap"}, "hiragana", "i", ""),
                new JapaneseWord("きらい", "kirai", new string[] {"to dislike", "disgusted with"}, "hiragana", "na", ""),
                new JapaneseWord("きれい", "kirei", new string[] {"beautiful", "clean"}, "hiragana", "na", ""),
                new JapaneseWord("げんき", "genki", new string[] {"healthy", "energetic"}, "hiragana", "na", ""),
                new JapaneseWord("しずか", "shizuka", new string[] {"quiet"}, "hiragana", "na", ""),
                new JapaneseWord("すき", "suki", new string[] {"to like", "fond of"}, "hiragana", "na", ""),
                new JapaneseWord("だいきらい", "daikirai", new string[] {"to hate"}, "hiragana", "na", ""),
                new JapaneseWord("だいすき", "daisuki", new string[] {"to love", "very fond of"}, "hiragana", "na", ""),
                new JapaneseWord("にぎやか", "nigiyaka", new string[] {"lively"}, "hiragana", "na", ""),
                new JapaneseWord("ひま", "hima", new string[] {"not busy", "free"}, "hiragana", "na", ""),
                new JapaneseWord("およぐ", "oyogu", new string[] {"to swim"}, "hiragana", "", ""),
                new JapaneseWord("きく", "kiku", new string[] {"to ask"}, "hiragana", "", ""),
                new JapaneseWord("のる", "noru", new string[] {"to ride", "to board"}, "hiragana", "", ""),
                new JapaneseWord("やる", "yaru", new string[] {"to do", "to perform"}, "hiragana", "", ""),
                new JapaneseWord("でかける", "dekakeru", new string[] {"to go out"}, "hiragana", "", ""),
                new JapaneseWord("サーフィン", "saafin", new string[] {"surfing"}, "katakana", "", ""),
                new JapaneseWord("バス", "basu", new string[] {"bus"}, "katakana", "", "")
            };

            var chapter6 = new JapaneseWord[]
            {
                new JapaneseWord("おかね", "okane", new string[] {"money"}, "hiragana", "", ""),
                new JapaneseWord("おふろ", "ofuro", new string[] {"bath"}, "hiragana", "", ""),
                new JapaneseWord("かんじ", "kanji", new string[] {"kanji", "Chinese character"}, "hiragana", "", ""),
                new JapaneseWord("きょうかしょ", "kyoukasho", new string[] {"textbook"}, "hiragana", "", ""),
                new JapaneseWord("こんしゅう", "konshuu", new string[] {"this week"}, "hiragana", "", ""),
                new JapaneseWord("しんみんびょういん", "shiminbyouin", new string[] {"municipal hospital"}, "hiragana", "", ""),
                new JapaneseWord("つぎ", "tsugi", new string[] {"next"}, "hiragana", "", ""),
                new JapaneseWord("でんき", "denki", new string[] {"electricity"}, "hiragana", "", ""),
                new JapaneseWord("でんしゃ", "densha", new string[] {"train"}, "hiragana", "", ""),
                new JapaneseWord("にもつ", "nimotsu", new string[] {"baggage"}, "hiragana", "", ""),
                new JapaneseWord("まど", "mado", new string[] {"window"}, "hiragana", "", ""),
                new JapaneseWord("よる", "yoru", new string[] {"night"}, "hiragana", "", ""),
                new JapaneseWord("らいしゅう", "raishuu", new string[] {"next week"}, "hiragana", "", ""),
                new JapaneseWord("らいねん", "rainen", new string[] {"next year"}, "hiragana", "", ""),
                new JapaneseWord("たいへん", "taihen", new string[] {"tough"}, "hiragana", "na", ""),
                new JapaneseWord("あそぶ", "asobu", new string[] {"to play", "to spend time pleasantly"}, "hiragana", "", ""),
                new JapaneseWord("いそぐ", "isogu", new string[] {"to hurry"}, "hiragana", "", ""),
                new JapaneseWord("おふろにはいる", "ofuronihairu", new string[] {"to take a bath"}, "hiragana", "", ""),
                new JapaneseWord("かえす", "kaesu", new string[] {"to return"}, "hiragana", "", ""),
                new JapaneseWord("けす", "kesu", new string[] {"to turn off", "to erase"}, "hiragana", "", ""),
                new JapaneseWord("しぬ", "shinu", new string[] {"to die"}, "hiragana", "", ""),
                new JapaneseWord("すわる", "suwaru", new string[] {"to sit down"}, "hiragana", "", ""),
                new JapaneseWord("たつ", "tatsu", new string[] {"to stand up"}, "hiragana", "", ""),
                new JapaneseWord("たばこをすう", "tabakowosuu", new string[] {"to smoke"}, "hiragana", "", ""),
                new JapaneseWord("つかう", "tsukau", new string[] {"to use"}, "hiragana", "", ""),
                new JapaneseWord("てつだう", "tetsudau", new string[] {"to help"}, "hiragana", "", ""),
                new JapaneseWord("はいる", "hairu", new string[] {"to enter"}, "hiragana", "", ""),
                new JapaneseWord("もつ", "motsu", new string[] {"to carry", "to hold"}, "hiragana", "", ""),
                new JapaneseWord("やすむ", "yasumu", new string[] {"to be absent", "to rest"}, "hiragana", "", ""),
                new JapaneseWord("あける", "akeru", new string[] {"to open"}, "hiragana", "", ""),
                new JapaneseWord("おしえる", "oshieru", new string[] {"to teach", "to instruct"}, "hiragana", "", ""),
                new JapaneseWord("おりる", "oriru", new string[] {"to get off"}, "hiragana", "", ""),
                new JapaneseWord("かりる", "kariru", new string[] {"to borrow"}, "hiragana", "", ""),
                new JapaneseWord("しめる", "shimeru", new string[] {"to close"}, "hiragana", "", ""),
                new JapaneseWord("シャワーをあびる", "shawaawoabiru", new string[] {"to take a shower"}, "hiragana", "", ""),
                new JapaneseWord("つける", "tsukeru", new string[] {"to turn on"}, "hiragana", "", ""),
                new JapaneseWord("でんわをかける", "denwawokakeru", new string[] {"to make a phone call"}, "hiragana", "", ""),
                new JapaneseWord("わすれる", "wasureru", new string[] {"to forget", "to leave behind"}, "hiragana", "", ""),
                new JapaneseWord("つれてくる", "tsuretekuru", new string[] {"to bring (person)"}, "hiragana", "", ""),
                new JapaneseWord("もってくる", "mottekuru", new string[] {"to bring (thing)"}, "hiragana", "", ""),
                new JapaneseWord("シャワー", "shawaa", new string[] {"shower"}, "katakana", "", ""),
                new JapaneseWord("パソコン", "pasokon", new string[] {"computer"}, "katakana", "", ""),
                new JapaneseWord("ページ", "peeji", new string[] {"page"}, "katakana", "", "")
            };
            
            var chapter7 = new JapaneseWord[]
            {
                new JapaneseWord("あね", "ane", new string[]{"older sister"}, "hiragana", "", ""), 
                new JapaneseWord("いもうと", "imouto", new string[]{"younger sister"}, "hiragana", "", ""), 
                new JapaneseWord("うた", "uta", new string[]{"song"}, "hiragana", "", ""), 
                new JapaneseWord("おじいさん", "ojiisan", new string[]{"grandfather", "old man"}, "hiragana", "", ""), 
                new JapaneseWord("おとうと", "otouto", new string[]{"younger brother"}, "hiragana", "", ""), 
                new JapaneseWord("おとこのひと", "otokonohito", new string[]{"man"}, "hiragana", "", ""), 
                new JapaneseWord("おばあさん", "obaasan", new string[]{"grandmother", "old woman"}, "hiragana", "", ""), 
                new JapaneseWord("おんなのひと", "onnanohito", new string[]{"woman"}, "hiragana", "", ""), 
                new JapaneseWord("かいしゃ", "kaisha", new string[]{"company"}, "hiragana", "", ""), 
                new JapaneseWord("かぞく", "kazoku", new string[]{"family"}, "hiragana", "", ""), 
                new JapaneseWord("かみ", "kami", new string[]{"hair"}, "hiragana", "", ""), 
                new JapaneseWord("きょうだい", "kyoudai", new string[]{"siblings", "brothers and sisters"}, "hiragana", "", ""), 
                new JapaneseWord("くち", "kuchi", new string[]{"mouth"}, "hiragana", "", ""), 
                new JapaneseWord("くに", "kuni", new string[]{"country"}, "hiragana", "", ""), 
                new JapaneseWord("くるま", "kuruma", new string[]{"car"}, "hiragana", "", ""), 
                new JapaneseWord("しょくどう", "shokudou", new string[]{"cafeteria", "dining commons"}, "hiragana", "", ""), 
                new JapaneseWord("ちち", "chichi", new string[]{"father"}, "hiragana", "", ""), 
                new JapaneseWord("はは", "haha", new string[]{"mother"}, "hiragana", "", ""), 
                new JapaneseWord("め", "me", new string[]{"eye"}, "hiragana", "", ""), 
                new JapaneseWord("めがね", "megane", new string[]{"glasses"}, "hiragana", "", ""), 
                new JapaneseWord("あたまがいい", "atamagaii", new string[]{"smart", "bright", "clever"}, "hiragana", "i", ""), 
                new JapaneseWord("かわいい", "kawaii", new string[]{"cute"}, "hiragana", "i", ""), 
                new JapaneseWord("せがたかい", "segatakai", new string[]{"tall"}, "hiragana", "i", ""), 
                new JapaneseWord("せがひくい", "segahikui", new string[]{"short"}, "hiragana", "i", ""), 
                new JapaneseWord("ながい", "nagai", new string[]{"long"}, "hiragana", "i", ""), 
                new JapaneseWord("はやい", "hayai", new string[]{"fast"}, "hiragana", "i", ""), 
                new JapaneseWord("みじかい", "mijikai", new string[]{"short"}, "hiragana", "i", ""), 
                new JapaneseWord("しんせつ", "shinsetsu", new string[]{"kind"}, "hiragana", "na", ""), 
                new JapaneseWord("べんり", "benri", new string[]{"convenient"}, "hiragana", "na", ""), 
                new JapaneseWord("うたう", "utau", new string[]{"to sing"}, "hiragana", "", ""), 
                new JapaneseWord("かぶる", "kaburu", new string[]{"to put on (a hat)"}, "hiragana", "", ""), 
                new JapaneseWord("しる", "shiru", new string[]{"to know", "to get to know"}, "hiragana", "", ""), 
                new JapaneseWord("すむ", "sumu", new string[]{"to live"}, "hiragana", "", ""), 
                new JapaneseWord("はく", "haku", new string[]{"to put on (items below your waist)"}, "hiragana", "", ""), 
                new JapaneseWord("ふとる", "futoru", new string[]{"to gain weight"}, "hiragana", "", ""), 
                new JapaneseWord("めがねをかける", "meganewokakeru", new string[]{"to put on glasses"}, "hiragana", "", ""), 
                new JapaneseWord("きる", "kiru", new string[]{"to wear", "to put on (clothes above your waist)"}, "hiragana", "", ""), 
                new JapaneseWord("つとめる", "tsutomeru", new string[]{"to work for"}, "hiragana", "", ""), 
                new JapaneseWord("やせる", "yaseru", new string[]{"to lose weight"}, "hiragana", "", ""), 
                new JapaneseWord("けっこんする", "kekkonsuru", new string[]{"to get married"}, "hiragana", "", ""), 
                new JapaneseWord("アパート", "apaato", new string[]{"apartment"}, "katakana", "", ""), 
                new JapaneseWord("ゲーム", "geemu", new string[]{"game"}, "katakana", "", ""), 
                new JapaneseWord("コンビニ", "konbini", new string[]{"convenience store"}, "katakana", "", ""), 
                new JapaneseWord("サークル", "saakuru", new string[]{"club activity"}, "katakana", "", "")
            };
            
            var chapter8 = new JapaneseWord[]
            {
                new JapaneseWord("あさって", "asatte", new string[]{"the day after tomorrow"}, "hiragana", "", ""), 
                new JapaneseWord("あめ", "ame", new string[]{"rain"}, "hiragana", "", ""), 
                new JapaneseWord("かいしゃいん", "kaishain", new string[]{"office worker"}, "hiragana", "", ""), 
                new JapaneseWord("くうき", "kuuki", new string[]{"air"}, "hiragana", "", ""), 
                new JapaneseWord("けさ", "kesa", new string[]{"this morning"}, "hiragana", "", ""), 
                new JapaneseWord("こくばん", "kokuban", new string[]{"blackboard"}, "hiragana", "", ""), 
                new JapaneseWord("こんげつ", "kongetsu", new string[]{"this month"}, "hiragana", "", ""), 
                new JapaneseWord("しごと", "shigoto", new string[]{"job", "work", "occupation"}, "hiragana", "", ""), 
                new JapaneseWord("だいがくせい", "daigakusei", new string[]{"college student"}, "hiragana", "", ""), 
                new JapaneseWord("てんきよほう", "tenkiyohou", new string[]{"weather forecast"}, "hiragana", "", ""), 
                new JapaneseWord("ところ", "tokoro", new string[]{"place"}, "hiragana", "", ""), 
                new JapaneseWord("なつ", "natsu", new string[]{"summer"}, "hiragana", "", ""), 
                new JapaneseWord("なにか", "nanika", new string[]{"something"}, "hiragana", "", ""), 
                new JapaneseWord("はし", "hashi", new string[]{"chopsticks"}, "hiragana", "", ""), 
                new JapaneseWord("ふゆ", "fuyu", new string[]{"winter"}, "hiragana", "", ""), 
                new JapaneseWord("まいしゅう", "maishuu", new string[]{"every week"}, "hiragana", "", ""), 
                new JapaneseWord("らいげつ", "raigetsu", new string[]{"next month"}, "hiragana", "", ""), 
                new JapaneseWord("じょうず", "jouzu", new string[]{"good at...", "skillful"}, "hiragana", "na", ""), 
                new JapaneseWord("へた", "heta", new string[]{"poor at...", "clumsy"}, "hiragana", "na", ""), 
                new JapaneseWord("ゆうめい", "yuumei", new string[]{"famous"}, "hiragana", "na", ""), 
                new JapaneseWord("あめがふる", "amegafuru", new string[]{"it rains"}, "hiragana", "", ""), 
                new JapaneseWord("あらう", "arau", new string[]{"to wash"}, "hiragana", "", ""), 
                new JapaneseWord("いう", "iu", new string[]{"to say"}, "hiragana", "", ""), 
                new JapaneseWord("いる", "iru", new string[]{"to need"}, "hiragana", "", ""), 
                new JapaneseWord("おそくなる", "osokunaru", new string[]{"to be late"}, "hiragana", "", ""), 
                new JapaneseWord("おもう", "omou", new string[]{"to think"}, "hiragana", "", ""), 
                new JapaneseWord("きる", "kiru", new string[]{"to cut"}, "hiragana", "", ""), 
                new JapaneseWord("つくる", "tsukuru", new string[]{"to make"}, "hiragana", "", ""), 
                new JapaneseWord("もっていく", "motteiku", new string[]{"to take"}, "hiragana", "", ""), 
                new JapaneseWord("じろじろみる", "jirojiromiru", new string[]{"to stare (at...)"}, "hiragana", "", ""), 
                new JapaneseWord("すてる", "suteru", new string[]{"to throw away"}, "hiragana", "", ""), 
                new JapaneseWord("はじめる", "hajimeru", new string[]{"to begin"}, "hiragana", "", ""), 
                new JapaneseWord("うんてんする", "untensuru", new string[]{"to drive"}, "hiragana", "", ""), 
                new JapaneseWord("せんたくする", "sentakusuru", new string[]{"to do laundry"}, "hiragana", "", ""), 
                new JapaneseWord("そうじする", "soujisuru", new string[]{"to clean"}, "hiragana", "", ""), 
                new JapaneseWord("でんわする", "denwasuru", new string[]{"to call"}, "hiragana", "", ""), 
                new JapaneseWord("りょうりする", "ryourisuru", new string[]{"to cook"}, "hiragana", "", ""), 
                new JapaneseWord("カメラ", "kamera", new string[]{"camera"}, "katakana", "", ""), 
                new JapaneseWord("カラオケ", "karaoke", new string[]{"karaoke"}, "katakana", "", ""), 
                new JapaneseWord("トマト", "tomato", new string[]{"tomato"}, "katakana", "", ""), 
                new JapaneseWord("パーチー", "paatii", new string[]{"party"}, "katakana", "", ""), 
                new JapaneseWord("バーベキュー", "baabekyuu", new string[]{"barbecue"}, "katakana", "", ""), 
                new JapaneseWord("ホームステイ", "hoomusutei", new string[]{"homestay", "living with a local family"}, "katakana", "", "")
            };
            
            var chapter9 = new JapaneseWord[]
            {
                new JapaneseWord("いいこ", "iiko", new string[]{"good child"}, "hiragana", "", ""), 
                new JapaneseWord("いろ", "iro", new string[]{"color"}, "hiragana", "", ""), 
                new JapaneseWord("おべんとう", "obentou", new string[]{"boxed lunch"}, "hiragana", "", ""), 
                new JapaneseWord("かぶき", "kabuki", new string[]{"Kabuki", "traditional Japanese theatrical art"}, "hiragana", "", ""), 
                new JapaneseWord("きょねん", "kyonen", new string[]{"last year"}, "hiragana", "", ""), 
                new JapaneseWord("くすり", "kusuri", new string[]{"medicine"}, "hiragana", "", ""), 
                new JapaneseWord("こんど", "kondo", new string[]{"near future"}, "hiragana", "", ""), 
                new JapaneseWord("さくぶん", "sakubun", new string[]{"essay", "composition"}, "hiragana", "", ""), 
                new JapaneseWord("しけん", "shiken", new string[]{"exam"}, "hiragana", "", ""), 
                new JapaneseWord("せんげつ", "sengetsu", new string[]{"last month"}, "hiragana", "", ""), 
                new JapaneseWord("たんご", "tango", new string[]{"vocabulary", "word"}, "hiragana", "", ""), 
                new JapaneseWord("びょうき", "byouki", new string[]{"sickness", "illness"}, "hiragana", "", ""), 
                new JapaneseWord("あおい", "aoi", new string[]{"blue"}, "hiragana", "i", ""), 
                new JapaneseWord("あかい", "akai", new string[]{"red"}, "hiragana", "i", ""), 
                new JapaneseWord("くろい", "kuroi", new string[]{"black"}, "hiragana", "i", ""), 
                new JapaneseWord("しろい", "shiroi", new string[]{"white"}, "hiragana", "i", ""), 
                new JapaneseWord("わかい", "wakai", new string[]{"young"}, "hiragana", "i", ""), 
                new JapaneseWord("さびしい", "sabishii", new string[]{"lonely"}, "hiragana", "i", ""), 
                new JapaneseWord("いじわる", "ijiwaru", new string[]{"mean", "mean-spirited"}, "hiragana", "na", ""), 
                new JapaneseWord("おどる", "odoru", new string[]{"to dance"}, "hiragana", "", ""), 
                new JapaneseWord("おわる", "owaru", new string[]{"something ends"}, "hiragana", "", ""), 
                new JapaneseWord("にんきがある", "ninkigaaru", new string[]{"to be popular"}, "hiragana", "", ""), 
                new JapaneseWord("はじめる", "hajimaru", new string[]{"something begins"}, "hiragana", "", ""), 
                new JapaneseWord("ひく", "hiku", new string[]{"to play (a string instrument or piano)"}, "hiragana", "", ""), 
                new JapaneseWord("もらう", "morau", new string[]{"to receive", "to get (from somebody)"}, "hiragana", "", ""), 
                new JapaneseWord("おぼえる", "oboeru", new string[]{"to memorize"}, "hiragana", "", ""), 
                new JapaneseWord("でる", "deru", new string[]{"to appear", "to exit", "to attend"}, "hiragana", "", ""), 
                new JapaneseWord("うんどうする", "undousuru", new string[]{"to exercise"}, "hiragana", "", ""), 
                new JapaneseWord("さんぽする", "sanposuru", new string[]{"to take a walk"}, "hiragana", "", ""), 
                new JapaneseWord("ギター", "gitaa", new string[]{"guitar"}, "katakana", "", ""), 
                new JapaneseWord("コンサート", "konsaato", new string[]{"concert"}, "katakana", "", ""), 
                new JapaneseWord("スキー", "sukii", new string[]{"ski"}, "katakana", "", ""), 
                new JapaneseWord("ピアノ", "piano", new string[]{"piano"}, "katakana", "", ""), 
                new JapaneseWord("ピザ", "piza", new string[]{"pizza"}, "katakana", "", "")
            };
            
            var chapter10 = new JapaneseWord[]
            {
                new JapaneseWord("あき", "aki", new string[]{"fall"}, "hiragana", "", ""), 
                new JapaneseWord("えき", "eki", new string[]{"station"}, "hiragana", "", ""), 
                new JapaneseWord("おかねもち", "okanemochi", new string[]{"rich person"}, "hiragana", "", ""), 
                new JapaneseWord("かお", "kao", new string[]{"face"}, "hiragana", "", ""), 
                new JapaneseWord("きせつ", "kisetsu", new string[]{"season"}, "hiragana", "", ""), 
                new JapaneseWord("ぎゅうにゅう", "gyuunyuu", new string[]{"milk"}, "hiragana", "", ""), 
                new JapaneseWord("ことし", "kotoshi", new string[]{"this year"}, "hiragana", "", ""), 
                new JapaneseWord("しんかんせん", "shinkansen", new string[]{"bullet train", "Shinkansen"}, "hiragana", "", ""), 
                new JapaneseWord("すし", "sushi", new string[]{"sushi"}, "hiragana", "", ""), 
                new JapaneseWord("せいかつ", "seikatsu", new string[]{"life", "living"}, "hiragana", "", ""), 
                new JapaneseWord("せかい", "sekai", new string[]{"world"}, "hiragana", "", ""), 
                new JapaneseWord("ちかてつ", "chikatetsu", new string[]{"subway"}, "hiragana", "", ""), 
                new JapaneseWord("てぶくろ", "tebukuro", new string[]{"gloves"}, "hiragana", "", ""), 
                new JapaneseWord("てんぷら", "tenpura", new string[]{"tempura"}, "hiragana", "", ""), 
                new JapaneseWord("とこや", "tokoya", new string[]{"barber shop", "barber's"}, "hiragana", "", ""), 
                new JapaneseWord("はる", "haru", new string[]{"spring"}, "hiragana", "", ""), 
                new JapaneseWord("びよういん", "biyouin", new string[]{"beauty parlor"}, "hiragana", "", ""), 
                new JapaneseWord("びん", "bin", new string[]{"flight"}, "hiragana", "", ""), 
                new JapaneseWord("ふね", "fune", new string[]{"ship", "boat"}, "hiragana", "", ""), 
                new JapaneseWord("やきゅう", "yakyuu", new string[]{"baseball"}, "hiragana", "", ""), 
                new JapaneseWord("よやく", "yoyaku", new string[]{"reservation"}, "hiragana", "", ""), 
                new JapaneseWord("らいがっき", "raigakki", new string[]{"next semester"}, "hiragana", "", ""), 
                new JapaneseWord("りんご", "ringo", new string[]{"apple"}, "hiragana", "", ""), 
                new JapaneseWord("あたたかい", "atatakai", new string[]{"warm"}, "hiragana", "i", ""), 
                new JapaneseWord("おそい", "osoi", new string[]{"slow", "late"}, "hiragana", "i", ""), 
                new JapaneseWord("すずしい", "suzushii", new string[]{"cool (weather)"}, "hiragana", "i", ""), 
                new JapaneseWord("つめたい", "tsumetai", new string[]{"cold (things)", "cold personality"}, "hiragana", "i", ""), 
                new JapaneseWord("ねむい", "nemui", new string[]{"sleepy"}, "hiragana", "i", ""), 
                new JapaneseWord("かんたん", "kantan", new string[]{"simple", "easy"}, "hiragana", "na", ""), 
                new JapaneseWord("かかる", "kakaru", new string[]{"to take (time)", "to take (money)"}, "hiragana", "", ""), 
                new JapaneseWord("とまる", "tomaru", new string[]{"to stay"}, "hiragana", "", ""), 
                new JapaneseWord("なる", "naru", new string[]{"to become"}, "hiragana", "", ""), 
                new JapaneseWord("はらう", "harau", new string[]{"to pay"}, "hiragana", "", ""), 
                new JapaneseWord("きめる", "kimeru", new string[]{"to decide"}, "hiragana", "", ""), 
                new JapaneseWord("りょこうする", "ryokousuru", new string[]{"to travel"}, "hiragana", "", ""), 
                new JapaneseWord("れんしゅうする", "renshuusuru", new string[]{"to practice"}, "hiragana", "", ""), 
                new JapaneseWord("クレジットカード", "kurejittokaado", new string[]{"credit card"}, "katakana", "", ""), 
                new JapaneseWord("ケーキ", "keeki", new string[]{"cake"}, "katakana", "", ""), 
                new JapaneseWord("サッカー", "sakkaa", new string[]{"soccer"}, "katakana", "", ""), 
                new JapaneseWord("パンツ", "pantsu", new string[]{"pants"}, "katakana", "", "")
            };
            
            var chapter11 = new JapaneseWord[]
            {
                new JapaneseWord("おかし", "okashi", new string[]{"sweets", "snacks"}, "hiragana", "", ""),
                new JapaneseWord("おしょうがつ", "oshougatsu", new string[]{"New Year's"}, "hiragana", "", ""), 
                new JapaneseWord("おとこのこ", "otokonoko", new string[]{"boy"}, "hiragana", "", ""), 
                new JapaneseWord("おまつり", "omatsuri", new string[]{"festival"}, "hiragana", "", ""), 
                new JapaneseWord("おもちゃ", "omocha", new string[]{"toy"}, "hiragana", "", ""), 
                new JapaneseWord("おんせん", "onsen", new string[]{"hot spring", "spa"}, "hiragana", "", ""), 
                new JapaneseWord("おんなのこ", "onnanoko", new string[]{"girl"}, "hiragana", "", ""), 
                new JapaneseWord("がいこく", "gaikoku", new string[]{"foreign country"}, "hiragana", "", ""), 
                new JapaneseWord("かしゅ", "kashu", new string[]{"singer"}, "hiragana", "", ""), 
                new JapaneseWord("かわ", "kawa", new string[]{"river"}, "hiragana", "", ""), 
                new JapaneseWord("こちら", "kochira", new string[]{"this person (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("こんがっき", "kongakki", new string[]{"this semester"}, "hiragana", "", ""), 
                new JapaneseWord("しゃちょう", "shachou", new string[]{"president of a company"}, "hiragana", "", ""), 
                new JapaneseWord("じゅぎょう", "jugyou", new string[]{"class"}, "hiragana", "", ""), 
                new JapaneseWord("しょうらい", "shourai", new string[]{"future"}, "hiragana", "", ""), 
                new JapaneseWord("じんじゃ", "jinja", new string[]{"shrine"}, "hiragana", "", ""), 
                new JapaneseWord("つり", "tsuri", new string[]{"fishing"}, "hiragana", "", ""), 
                new JapaneseWord("びじゅつかん", "bijutsukan", new string[]{"art museum"}, "hiragana", "", ""), 
                new JapaneseWord("みずうみ", "mizuumi", new string[]{"lake"}, "hiragana", "", ""), 
                new JapaneseWord("っやま", "yama", new string[]{"mountain"}, "hiragana", "", ""), 
                new JapaneseWord("ゆめ", "yume", new string[]{"dream"}, "hiragana", "", ""), 
                new JapaneseWord("うそをつく", "usowotsuku", new string[]{"to lie", "to tell a lie"}, "hiragana", "", ""), 
                new JapaneseWord("おなかがすく", "onakagasuku", new string[]{"to become hungry"}, "hiragana", "", ""), 
                new JapaneseWord("かう", "kau", new string[]{"to own (a pet)"}, "hiragana", "", ""), 
                new JapaneseWord("ならう", "narau", new string[]{"to learn"}, "hiragana", "", ""), 
                new JapaneseWord("のぼる", "noboru", new string[]{"to climb"}, "hiragana", "", ""), 
                new JapaneseWord("はたらく", "hataraku", new string[]{"to work"}, "hiragana", "", ""), 
                new JapaneseWord("つかれる", "tsukareru", new string[]{"to get tired"}, "hiragana", "", ""), 
                new JapaneseWord("やめる", "yameru", new string[]{"to quit"}, "hiragana", "", ""), 
                new JapaneseWord("けんかする", "kenkasuru", new string[]{"to have a fight", "to quarrel"}, "hiragana", "", ""), 
                new JapaneseWord("しょうかいする", "shoukaisuru", new string[]{"to introduce"}, "hiragana", "", ""), 
                new JapaneseWord("ちこくする", "chikokusuru", new string[]{"to be late (for an appointment)"}, "hiragana", "", ""), 
                new JapaneseWord("りゅうがくする", "ryuugakusuru", new string[]{"to study abroad"}, "hiragana", "", ""), 
                new JapaneseWord("キャンプ", "kyanpu", new string[]{"camp"}, "katakana", "", ""), 
                new JapaneseWord("ドライブ", "doraibu", new string[]{"drive"}, "katakana", "", ""), 
                new JapaneseWord("ビール", "biiru", new string[]{"beer"}, "katakana", "", ""), 
                new JapaneseWord("ホストファミリー", "hosutofamirii", new string[]{"host family"}, "katakana", "", ""), 
                new JapaneseWord("ルームメート", "ruumumeeto", new string[]{"roommate"}, "katakana", "", ""), 
                new JapaneseWord("サボル", "saboru", new string[]{"to cut class", "to skip"}, "katakana", "", "")
            };
            
            var chapter12 = new JapaneseWord[]
            {
                new JapaneseWord("あし", "ashi", new string[]{"leg", "foot"}, "hiragana", "", ""), 
                new JapaneseWord("いみ", "imi", new string[]{"meaning"}, "hiragana", "", ""), 
                new JapaneseWord("おてあらい", "otearai", new string[]{"restroom"}, "hiragana", "", ""), 
                new JapaneseWord("おなか", "onaka", new string[]{"stomach"}, "hiragana", "", ""), 
                new JapaneseWord("かぜ", "kaze", new string[]{"cold"}, "hiragana", "", ""), 
                new JapaneseWord("かのじょ", "kanojo", new string[]{"girlfriend", "she"}, "hiragana", "", ""), 
                new JapaneseWord("かれ", "kare", new string[]{"boyfriend", "he"}, "hiragana", "", ""), 
                new JapaneseWord("きおん", "kion", new string[]{"temperature (of the weather)"}, "hiragana", "", ""), 
                new JapaneseWord("くもり", "kumori", new string[]{"cloudy weather"}, "hiragana", "", ""), 
                new JapaneseWord("しあい", "shiai", new string[]{"match", "game"}, "hiragana", "", ""), 
                new JapaneseWord("せいじ", "seiji", new string[]{"politics"}, "hiragana", "", ""), 
                new JapaneseWord("せいせき", "seiseki", new string[]{"grade"}, "hiragana", "", ""), 
                new JapaneseWord("せき", "seki", new string[]{"cough"}, "hiragana", "", ""), 
                new JapaneseWord("のど", "nodo", new string[]{"throat"}, "hiragana", "", ""), 
                new JapaneseWord("は", "ha", new string[]{"teeth"}, "hiragana", "", ""), 
                new JapaneseWord("はな", "hana", new string[]{"flower"}, "hiragana", "", ""), 
                new JapaneseWord("はれ", "hare", new string[]{"sunny weather"}, "hiragana", "", ""), 
                new JapaneseWord("ふく", "fuku", new string[]{"clothes"}, "hiragana", "", ""), 
                new JapaneseWord("ふつかよい", "futsukayoi", new string[]{"hangover"}, "hiragana", "", ""), 
                new JapaneseWord("もの", "mono", new string[]{"thing (concrete object)"}, "hiragana", "", ""), 
                new JapaneseWord("ゆき", "yuki", new string[]{"snow"}, "hiragana", "", ""), 
                new JapaneseWord("ようじ", "youji", new string[]{"business to take care of"}, "hiragana", "", ""), 
                new JapaneseWord("あまい", "amai", new string[]{"sweet"}, "hiragana", "i", ""), 
                new JapaneseWord("いたい", "itai", new string[]{"hurt", "painful"}, "hiragana", "i", ""), 
                new JapaneseWord("おおい", "ooi", new string[]{"many"}, "hiragana", "i", ""), 
                new JapaneseWord("せまい", "semai", new string[]{"narrow", "not spacious"}, "hiragana", "i", ""), 
                new JapaneseWord("つごうがわるい", "tsugougawarui", new string[]{ "inconvenient", "to have a scheduling conflict"}, "hiragana", "i", ""), 
                new JapaneseWord("わるい", "warui", new string[]{"bad"}, "hiragana", "i", ""), 
                new JapaneseWord("すてき", "suteki", new string[]{"nice"}, "hiragana", "na", ""), 
                new JapaneseWord("あるく", "aruku", new string[]{"to walk"}, "hiragana", "", ""), 
                new JapaneseWord("かぜをひく", "kazewohiku", new string[]{"to catch a cold"}, "hiragana", "", ""), 
                new JapaneseWord("きょうみがある", "kyoumigaaru", new string[]{"to be interested in"}, "hiragana", "", ""), 
                new JapaneseWord("なくす", "nakusu", new string[]{"to lose (something)"}, "hiragana", "", ""), 
                new JapaneseWord("ねつがある", "netsugaaru", new string[]{"to have a fever"}, "hiragana", "", ""), 
                new JapaneseWord("のどがかわく", "nodogakawaku", new string[]{"to become thirsty"}, "hiragana", "", ""), 
                new JapaneseWord("せきがでる", "sekigaderu", new string[]{"to cough"}, "hiragana", "", ""), 
                new JapaneseWord("わかれる", "wakareru", new string[]{"to break up", "to separate"}, "hiragana", "", ""), 
                new JapaneseWord("きんちょうする", "kinchousuru", new string[]{"to get nervous"}, "hiragana", "", ""), 
                new JapaneseWord("しんぱいする", "shinpaisuru", new string[]{"to worry"}, "hiragana", "", ""), 
                new JapaneseWord("ジュース", "juusu", new string[]{"juice"}, "katakana", "", ""), 
                new JapaneseWord("プレゼント", "purezento", new string[]{"present"}, "katakana", "", ""), 
                new JapaneseWord("ホームシック", "hoomushikku", new string[]{"homesick"}, "katakana", "", ""), 
                new JapaneseWord("マイナス", "mainasu", new string[]{"minus"}, "katakana", "", "")
            };
            
            var chapter13 = new JapaneseWord[]
            {
                new JapaneseWord("おたく", "otaku", new string[]{"(someone's) home"}, "hiragana", "", ""), 
                new JapaneseWord("おとな", "otona", new string[]{"adult"}, "hiragana", "", ""), 
                new JapaneseWord("がいこくご", "gaikokugo", new string[]{"foreign language"}, "hiragana", "", ""), 
                new JapaneseWord("がっき", "gakki", new string[]{"musical instrument"}, "hiragana", "", ""), 
                new JapaneseWord("からて", "karate", new string[]{"karate"}, "hiragana", "", ""), 
                new JapaneseWord("きもの", "kimono", new string[]{"kimono"}, "hiragana", "", ""), 
                new JapaneseWord("こうこく", "koukoku", new string[]{"advertisement"}, "hiragana", "", ""), 
                new JapaneseWord("ことば", "kotoba", new string[]{"language"}, "hiragana", "", ""), 
                new JapaneseWord("ぞう", "zou", new string[]{"elephant"}, "hiragana", "", ""), 
                new JapaneseWord("ぶっか", "bukka", new string[]{"(consumer) prices"}, "hiragana", "", ""), 
                new JapaneseWord("ぶんぽう", "bunpou", new string[]{"grammar"}, "hiragana", "", ""), 
                new JapaneseWord("ぼしゅう", "boshuu", new string[]{"recruitment"}, "hiragana", "", ""), 
                new JapaneseWord("みせ", "mise", new string[]{"shop", "store"}, "hiragana", "", ""), 
                new JapaneseWord("やくざ", "yakuza", new string[]{"yakuza", "gangster"}, "hiragana", "", ""), 
                new JapaneseWord("やくぞく", "yakusoku", new string[]{"to keep a promise"}, "hiragana", "", ""), 
                new JapaneseWord("わたくし", "watakushi", new string[]{"I (formal)"}, "hiragana", "", ""), 
                new JapaneseWord("うれしい", "ureshii", new string[]{"glad"}, "hiragana", "i", ""), 
                new JapaneseWord("かなしい", "kanashii", new string[]{"sad"}, "hiragana", "i", ""), 
                new JapaneseWord("からい", "karai", new string[]{"hot and spicy", "salty"}, "hiragana", "i", ""), 
                new JapaneseWord("すごい", "sugoi", new string[]{"awesome", "incredible"}, "hiragana", "i", ""), 
                new JapaneseWord("ちかい", "chikai", new string[]{"close", "near"}, "hiragana", "i", ""), 
                new JapaneseWord("いろいろ", "iroiro", new string[]{"various", "different kinds of"}, "hiragana", "na", ""), 
                new JapaneseWord("しあわせ", "shiawase", new string[]{"happy (lasting happiness)"}, "hiragana", "na", ""), 
                new JapaneseWord("だめ", "dame", new string[]{"no good"}, "hiragana", "na", ""), 
                new JapaneseWord("あむ", "amu", new string[]{"to knit"}, "hiragana", "", ""), 
                new JapaneseWord("かす", "kasu", new string[]{"to lend", "to rent"}, "hiragana", "", ""), 
                new JapaneseWord("がんばる", "ganbaru", new string[]{"to do one's best", "to try hard"}, "hiragana", "", ""), 
                new JapaneseWord("なく", "naku", new string[]{"to cry"}, "hiragana", "", ""), 
                new JapaneseWord("みがく", "migaku", new string[]{"to brush teeth", "to polish"}, "hiragana", "", ""), 
                new JapaneseWord("やくそくをまもる", "yakusokuwomamoru", new string[]{"to keep a promise"}, "hiragana", "", ""), 
                new JapaneseWord("かんどうする", "kandousuru", new string[]{"to be moved", "to be touched"}, "hiragana", "", ""), 
                new JapaneseWord("ウエイター", "ueitaa", new string[]{"waiter"}, "katakana", "", ""), 
                new JapaneseWord("カレー", "karee", new string[]{"curry"}, "katakana", "", ""), 
                new JapaneseWord("ゴルフ", "gorufu", new string[]{"golf"}, "katakana", "", ""), 
                new JapaneseWord("バイオリン", "baiorin", new string[]{"violin"}, "katakana", "", ""), 
                new JapaneseWord("バイク", "baiku", new string[]{"motorcycle"}, "katakana", "", ""), 
                new JapaneseWord("レポート", "repooto", new string[]{"(term) paper"}, "katakana", "", "")
            };
            
            var chapter14 = new JapaneseWord[]
            {
                new JapaneseWord("あに", "ani", new string[]{"older brother"}, "hiragana", "", ""), 
                new JapaneseWord("おおやさん", "ooyasan", new string[]{"landlord", "landlady"}, "hiragana", "", ""), 
                new JapaneseWord("おかえし", "okaeshi", new string[]{"return (as a token of gratitude)"}, "hiragana", "", ""), 
                new JapaneseWord("おくさん", "okusan", new string[]{"(your/his) wife"}, "hiragana", "", ""), 
                new JapaneseWord("おじさん", "ojisan", new string[]{"uncle", "middle-aged man"}, "hiragana", "", ""), 
                new JapaneseWord("おばさん", "obasan", new string[]{"aunt", "middle-aged woman"}, "hiragana", "", ""), 
                new JapaneseWord("ごしゅじん", "goshujin", new string[]{"(your/her) husband"}, "hiragana", "", ""), 
                new JapaneseWord("さら", "sara", new string[]{"plate", "dish"}, "hiragana", "", ""), 
                new JapaneseWord("じかん", "jikan", new string[]{"time"}, "hiragana", "", ""), 
                new JapaneseWord("ぬいぐるみ", "nuigurumi", new string[]{"stuffed animal"}, "hiragana", "", ""), 
                new JapaneseWord("ふうふ", "fuufu", new string[]{"married couple", "husband and wife"}, "hiragana", "", ""), 
                new JapaneseWord("まんが", "manga", new string[]{"comic book"}, "hiragana", "", ""), 
                new JapaneseWord("みかん", "mikan", new string[]{"mandarin", "orange"}, "hiragana", "", ""), 
                new JapaneseWord("みなさん", "minasan", new string[]{"everyone", "all of you"}, "hiragana", "", ""), 
                new JapaneseWord("ゆびわ", "yubiwa", new string[]{"ring"}, "hiragana", "", ""), 
                new JapaneseWord("りょうしん", "ryoushin", new string[]{"parents"}, "hiragana", "", ""), 
                new JapaneseWord("りれきしょ", "rirekisho", new string[]{"resume"}, "hiragana", "", ""), 
                new JapaneseWord("ほしい", "hoshii", new string[]{"to want"}, "hiragana", "i", ""), 
                new JapaneseWord("けち", "kechi", new string[]{"stingy", "cheap"}, "hiragana", "na", ""), 
                new JapaneseWord("おくる", "okuru", new string[]{"to send"}, "hiragana", "", ""), 
                new JapaneseWord("にあう", "niau", new string[]{"to look good (on somebody)"}, "hiragana", "", ""), 
                new JapaneseWord("あきらめる", "akirameru", new string[]{"to give up"}, "hiragana", "", ""), 
                new JapaneseWord("あげる", "ageru", new string[]{"to give (to others)"}, "hiragana", "", ""), 
                new JapaneseWord("くれる", "kureru", new string[]{"to give (me)"}, "hiragana", "", ""), 
                new JapaneseWord("できる", "dekiru", new string[]{"to come into existence", "to be made"}, "hiragana", "", ""), 
                new JapaneseWord("そうだんする", "soudansuru", new string[]{"to consult"}, "hiragana", "", ""), 
                new JapaneseWord("グラス", "gurasu", new string[]{"tumbler", "glass"}, "katakana", "", ""), 
                new JapaneseWord("クリスマス", "kurisumasu", new string[]{"Christmas"}, "katakana", "", ""), 
                new JapaneseWord("チケット", "chiketto", new string[]{"ticket"}, "katakana", "", ""), 
                new JapaneseWord("チョコレート", "chokoreeto", new string[]{"chocolate"}, "katakana", "", ""), 
                new JapaneseWord("トレーナー", "toreenaa", new string[]{"sweat shirt"}, "katakana", "", ""), 
                new JapaneseWord("ネクタイ", "nekutai", new string[]{"necktie"}, "katakana", "", ""), 
                new JapaneseWord("バレンタインデー", "barentaindee", new string[]{"st. Valentine's Day"}, "katakana", "", ""), 
                new JapaneseWord("ビデオカメラ", "bideokamera", new string[]{"camcorder"}, "katakana", "", ""), 
                new JapaneseWord("ホワイトデー", "howaitodee", new string[]{"White Day"}, "katakana", "", ""), 
                new JapaneseWord("マフラー", "mafuraa", new string[]{"winter scarf"}, "katakana", "", ""), 
                new JapaneseWord("マンション", "manshon", new string[]{"multistory apartment building", "condominium"}, "katakana", "", ""), 
                new JapaneseWord("ラジオ", "rajio", new string[]{"radio"}, "katakana", "", "")
            };
            
            var chapter15 = new JapaneseWord[]
            {
                new JapaneseWord("え", "e", new string[]{"painting", "picture", "drawing"}, "hiragana", "", ""), 
                new JapaneseWord("えいがかん", "eigakan", new string[]{"movie theater"}, "hiragana", "", ""), 
                new JapaneseWord("がいこくじん", "gaikokujin", new string[]{"foreigner"}, "hiragana", "", ""), 
                new JapaneseWord("かぐ", "kagu", new string[]{"furniture"}, "hiragana", "", ""), 
                new JapaneseWord("けいけん", "keiken", new string[]{"experience"}, "hiragana", "", ""), 
                new JapaneseWord("けっこんしき", "kekkonshiki", new string[]{"wedding"}, "hiragana", "", ""), 
                new JapaneseWord("じしん", "jishin", new string[]{"earthquake"}, "hiragana", "", ""), 
                new JapaneseWord("しめきり", "shimekiri", new string[]{"deadline"}, "hiragana", "", ""), 
                new JapaneseWord("しゅうかん", "shuukan", new string[]{"custom"}, "hiragana", "", ""), 
                new JapaneseWord("ざいきん", "zeikin", new string[]{"tax"}, "hiragana", "", ""), 
                new JapaneseWord("そつぎょうしき", "sotsugyoushiki", new string[]{"graduation ceremony"}, "hiragana", "", ""), 
                new JapaneseWord("そば", "soba", new string[]{"soba", "Japanese buckwheat noodle"}, "hiragana", "", ""), 
                new JapaneseWord("ちず", "chizu", new string[]{"map"}, "hiragana", "", ""), 
                new JapaneseWord("でんち", "denchi", new string[]{"battery"}, "hiragana", "", ""), 
                new JapaneseWord("にわ", "niwa", new string[]{"garden"}, "hiragana", "", ""), 
                new JapaneseWord("ばんぐみ", "bangumi", new string[]{"broadcast program"}, "hiragana", "", ""), 
                new JapaneseWord("はっぴょう", "happyou", new string[]{"presentation"}, "hiragana", "", ""), 
                new JapaneseWord("ほけん", "hoken", new string[]{"insurance"}, "hiragana", "", ""), 
                new JapaneseWord("よてい", "yotei", new string[]{"plan", "schedule"}, "hiragana", "", ""), 
                new JapaneseWord("りょかん", "ryokan", new string[]{"Japanese inn"}, "hiragana", "", ""), 
                new JapaneseWord("わりびきけん", "waribikiken", new string[]{"discount coupon"}, "hiragana", "", ""), 
                new JapaneseWord("ひろい", "hiroi", new string[]{"spacious", "wide"}, "hiragana", "i", ""), 
                new JapaneseWord("うる", "uru", new string[]{"to sell"}, "hiragana", "", ""), 
                new JapaneseWord("おろす", "orosu", new string[]{"to withdraw (money)"}, "hiragana", "", ""), 
                new JapaneseWord("さがす", "sagasu", new string[]{"to look for"}, "hiragana", "", ""), 
                new JapaneseWord("さそう", "sasou", new string[]{"to invite"}, "hiragana", "", ""), 
                new JapaneseWord("しゃべる", "shaberu", new string[]{"to chat"}, "hiragana", "", ""), 
                new JapaneseWord("つきあう", "tsukiau", new string[]{"to date (someone)", "to keep company"}, "hiragana", "", ""), 
                new JapaneseWord("つく", "tsuku", new string[]{"to arrive"}, "hiragana", "", ""), 
                new JapaneseWord("ほけんにはいる", "hokennihairu", new string[]{"to buy insurance"}, "hiragana", "", ""), 
                new JapaneseWord("きをつける", "kiwotsukeru", new string[]{"to be careful", "to be cautious"}, "hiragana", "", ""), 
                new JapaneseWord("しらべる", "shiraberu", new string[]{"to look into (a matter)"}, "hiragana", "", ""), 
                new JapaneseWord("みえる", "mieru", new string[]{"to be visible"}, "hiragana", "", ""), 
                new JapaneseWord("かんこうする", "kankousuru", new string[]{"to do sightseeing"}, "hiragana", "", ""), 
                new JapaneseWord("する", "suru", new string[]{"to decide on (an item)"}, "hiragana", "", ""), 
                new JapaneseWord("そつぎょうする", "sotsugyousuru", new string[]{"to graduate"}, "hiragana", "", ""), 
                new JapaneseWord("よやくする", "yoyakusuru", new string[]{"to reserve"}, "hiragana", "", ""), 
                new JapaneseWord("インターネット", "intaanetto", new string[]{"Internet"}, "katakana", "", ""), 
                new JapaneseWord("クラブ", "kurabu", new string[]{"night club"}, "katakana", "", ""), 
                new JapaneseWord("ジャケット", "jaketto", new string[]{"jacket"}, "katakana", "", ""), 
                new JapaneseWord("プール", "puuru", new string[]{"swimming pool"}, "katakana", "", ""), 
                new JapaneseWord("ペット", "petto", new string[]{"pet"}, "katakana", "", "")
            };
            
            var chapter16 = new JapaneseWord[]
            {
                new JapaneseWord("えきいん", "ekiin", new string[]{"station attendant"}, "hiragana", "", ""), 
                new JapaneseWord("おおきさ", "ookisa", new string[]{"size"}, "hiragana", "", ""), 
                new JapaneseWord("おや", "oya", new string[]{"parent"}, "hiragana", "", ""), 
                new JapaneseWord("きまつしけん", "kimatsushiken", new string[]{"final exam"}, "hiragana", "", ""), 
                new JapaneseWord("けんきゅう", "kenkyuu", new string[]{"research"}, "hiragana", "", ""), 
                new JapaneseWord("ごみ", "gomi", new string[]{"garbage"}, "hiragana", "", ""), 
                new JapaneseWord("さとう", "satou", new string[]{"sugar"}, "hiragana", "", ""), 
                new JapaneseWord("しょうがくきん", "shougakukin", new string[]{"scholarship"}, "hiragana", "", ""), 
                new JapaneseWord("しんせき", "shinseki", new string[]{"relatives"}, "hiragana", "", ""), 
                new JapaneseWord("すいせんじょう", "suisenjou", new string[]{"letter of recommendation"}, "hiragana", "", ""), 
                new JapaneseWord("だいがくいん", "daigakuin", new string[]{"graduate school"}, "hiragana", "", ""), 
                new JapaneseWord("たいふう", "taifuu", new string[]{"typhoon"}, "hiragana", "", ""), 
                new JapaneseWord("ひ", "hi", new string[]{"day"}, "hiragana", "", ""), 
                new JapaneseWord("みち", "michi", new string[]{"road", "way", "directions"}, "hiragana", "", ""), 
                new JapaneseWord("めざましどけい", "mezamashidokei", new string[]{"alarm clock"}, "hiragana", "", ""), 
                new JapaneseWord("きたない", "kitanai", new string[]{"dirty"}, "hiragana", "i", ""), 
                new JapaneseWord("おこす", "okosu", new string[]{"to wake (someone) up"}, "hiragana", "", ""), 
                new JapaneseWord("おごる", "ogoru", new string[]{"to treat (someone) to a meal"}, "hiragana", "", ""), 
                new JapaneseWord("おちこむ", "ochikomu", new string[]{"to get depressed"}, "hiragana", "", ""), 
                new JapaneseWord("こまる", "komaru", new string[]{"to have difficulty"}, "hiragana", "", ""), 
                new JapaneseWord("だす", "dasu", new string[]{"to hand in (something)", "to take (something) out"}, "hiragana", "", ""), 
                new JapaneseWord("つれていく", "tsureteiku", new string[]{"to take (someone) to (a place)"}, "hiragana", "", ""), 
                new JapaneseWord("なおす", "naosu", new string[]{"to correct", "to fix"}, "hiragana", "", ""), 
                new JapaneseWord("みちにまよう", "michinimayou", new string[]{"to become lost", "to lose one's way"}, "hiragana", "", ""), 
                new JapaneseWord("みつかる", "mitsukaru", new string[]{"to be found"}, "hiragana", "", ""), 
                new JapaneseWord("むかえにいく", "mukaeniiku", new string[]{"to go to pick up"}, "hiragana", "", ""), 
                new JapaneseWord("やくす", "yakusu", new string[]{"to translate"}, "hiragana", "", ""), 
                new JapaneseWord("わらう", "warau", new string[]{"to laugh"}, "hiragana", "", ""), 
                new JapaneseWord("アイロンをかける", "aironwokakeru", new string[]{"to iron (clothes)"}, "hiragana", "", ""), 
                new JapaneseWord("あつめる", "atsumeru", new string[]{"to collect"}, "hiragana", "", ""), 
                new JapaneseWord("いれる", "ireru", new string[]{"to put (something) in"}, "hiragana", "", ""), 
                new JapaneseWord("のりおくれる", "noriokureru", new string[]{"to miss (a train, bus, etc.)"}, "hiragana", "", ""), 
                new JapaneseWord("みせる", "miseru", new string[]{"to show"}, "hiragana", "", ""), 
                new JapaneseWord("あさねぼうする", "asanebousuru", new string[]{"to oversleep"}, "hiragana", "", ""), 
                new JapaneseWord("あんないする", "annaisuru", new string[]{"to show (someone) around"}, "hiragana", "", ""), 
                new JapaneseWord("せつめいする", "setsumeisuru", new string[]{"to explain"}, "hiragana", "", ""), 
                new JapaneseWord("むかえにいく", "mukaenikuru", new string[]{"to come to pick up"}, "hiragana", "", ""), 
                new JapaneseWord("ファイル", "fairu", new string[]{"file", "portfolio"}, "katakana", "", "")
            };
            
            var chapter17 = new JapaneseWord[]
            {
                new JapaneseWord("おきゃくさん", "okyakusan", new string[]{"guest", "visitor", "client", "customer"}, "hiragana", "", ""), 
                new JapaneseWord("おとこ", "otoko", new string[]{"man"}, "hiragana", "", ""), 
                new JapaneseWord("おゆ", "oyu", new string[]{"hot water"}, "hiragana", "", ""), 
                new JapaneseWord("おんな", "onna", new string[]{"woman"}, "hiragana", "", ""), 
                new JapaneseWord("かぎ", "kagi", new string[]{"lock", "key"}, "hiragana", "", ""), 
                new JapaneseWord("かじ", "kaji", new string[]{"fire"}, "hiragana", "", ""), 
                new JapaneseWord("かみ", "kami", new string[]{"paper"}, "hiragana", "", ""), 
                new JapaneseWord("きゅうりょう", "kyuuryou", new string[]{"salary"}, "hiragana", "", ""), 
                new JapaneseWord("さいてい", "saitei", new string[]{"the lowest", "the worst"}, "hiragana", "", ""), 
                new JapaneseWord("ざんぎょう", "zangyou", new string[]{"overtime work"}, "hiragana", "", ""), 
                new JapaneseWord("しゅしょう", "shushou", new string[]{"prime minister"}, "hiragana", "", ""), 
                new JapaneseWord("たからくじ", "takarakuji", new string[]{"lottery"}, "hiragana", "", ""), 
                new JapaneseWord("ちがい", "chigai", new string[]{"difference"}, "hiragana", "", ""), 
                new JapaneseWord("どうぶつえん", "doubutsuen", new string[]{"zoo"}, "hiragana", "", ""), 
                new JapaneseWord("ひげ", "hige", new string[]{"beard"}, "hiragana", "", ""), 
                new JapaneseWord("ひみつ", "himitsu", new string[]{"secret"}, "hiragana", "", ""), 
                new JapaneseWord("りょう", "ryou", new string[]{"dormitory"}, "hiragana", "", ""), 
                new JapaneseWord("りょこうがいしゃ", "ryokougaisha", new string[]{"travel agency"}, "hiragana", "", ""), 
                new JapaneseWord("あぶない", "abunai", new string[]{"dangerous"}, "hiragana", "i", ""), 
                new JapaneseWord("うらやましい", "urayamashii", new string[]{"envious"}, "hiragana", "i", ""), 
                new JapaneseWord("すくない", "sukunai", new string[]{"a little", "a few"}, "hiragana", "i", ""), 
                new JapaneseWord("つよい", "tsuyoi", new string[]{"strong"}, "hiragana", "i", ""), 
                new JapaneseWord("えらぶ", "erabu", new string[]{"to choose", "to select"}, "hiragana", "", ""), 
                new JapaneseWord("おゆをわかす", "oyuwowakasu", new string[]{"to boil water"}, "hiragana", "", ""), 
                new JapaneseWord("かみをとかす", "kamiwotokasu", new string[]{"to comb one's hair"}, "hiragana", "", ""), 
                new JapaneseWord("こむ", "komu", new string[]{"to get crowded"}, "hiragana", "", ""), 
                new JapaneseWord("たからくじにあたる", "takarakujiniataru", new string[]{"to win a lottery"}, "hiragana", "", ""), 
                new JapaneseWord("ぬぐ", "nugu", new string[]{"to take off (clothes)"}, "hiragana", "", ""), 
                new JapaneseWord("ひげをそる", "higewosoru", new string[]{"to shave one's beard"}, "hiragana", "", ""), 
                new JapaneseWord("いれる", "ireru", new string[]{"to make tea, coffee, etc."}, "hiragana", "", ""), 
                new JapaneseWord("うまれる", "umareru", new string[]{"to be born"}, "hiragana", "", ""), 
                new JapaneseWord("かぎをかける", "kagiwokakeru", new string[]{"to lock"}, "hiragana", "", ""), 
                new JapaneseWord("たりる", "tariru", new string[]{"to be sufficient", "to be enough"}, "hiragana", "", ""), 
                new JapaneseWord("なれる", "nareru", new string[]{"to get used to..."}, "hiragana", "", ""), 
                new JapaneseWord("おいのりする", "oinorisuru", new string[]{"to pray"}, "hiragana", "", ""), 
                new JapaneseWord("けしょうする", "keshousuru", new string[]{"to put makeup on"}, "hiragana", "", ""), 
                new JapaneseWord("しゅうしょくする", "shuushokusuru", new string[]{"to get a full-time job (at...)"}, "hiragana", "", ""), 
                new JapaneseWord("する", "suru", new string[]{"to wear small items (necktie, watch, etc.)"}, "hiragana", "", ""), 
                new JapaneseWord("りこんする", "rikonsuru", new string[]{"to get a divorce"}, "hiragana", "", ""), 
                new JapaneseWord("コンタクト", "kontakuto", new string[]{"contact lenses"}, "katakana", "", ""), 
                new JapaneseWord("サラリーマン", "sarariiman", new string[]{"salary man"}, "katakana", "", ""), 
                new JapaneseWord("ショッピングモール", "shoppingumooru", new string[]{"shopping mall"}, "katakana", "", ""), 
                new JapaneseWord("スプーン", "supuun", new string[]{"spoon"}, "katakana", "", ""), 
                new JapaneseWord("ニュース", "nyuusu", new string[]{"news"}, "katakana", "", ""), 
                new JapaneseWord("パンダ", "panda", new string[]{"panda"}, "katakana", "", ""), 
                new JapaneseWord("ブーツ", "buutsu", new string[]{"boots"}, "katakana", "", ""), 
                new JapaneseWord("ヒーター", "hiitaa", new string[]{"heater"}, "katakana", "", "")
            };
            
            var chapter18 = new JapaneseWord[]
            {
                new JapaneseWord("あと", "ato", new string[]{"the rest"}, "hiragana", "", ""), 
                new JapaneseWord("しょゆう", "shoyuu", new string[]{"soy sauce"}, "hiragana", "", ""), 
                new JapaneseWord("そと", "soto", new string[]{"outside"}, "hiragana", "", ""), 
                new JapaneseWord("にっき", "nikki", new string[]{"diary"}, "hiragana", "", ""), 
                new JapaneseWord("むし", "mushi", new string[]{"insect"}, "hiragana", "", ""), 
                new JapaneseWord("やちん", "yachin", new string[]{"rent"}, "hiragana", "", ""), 
                new JapaneseWord("ゆうがた", "yuugata", new string[]{"evening"}, "hiragana", "", ""), 
                new JapaneseWord("るすばんでんわ", "rusubandenwa", new string[]{"answering machine"}, "hiragana", "", ""), 
                new JapaneseWord("れいぞうこ", "reizouko", new string[]{"refrigerator"}, "hiragana", "", ""), 
                new JapaneseWord("ろうそく", "rousoku", new string[]{"candle"}, "hiragana", "", ""), 
                new JapaneseWord("あかるい", "akarui", new string[]{"bright"}, "hiragana", "i", ""), 
                new JapaneseWord("きぶんがわるい", "kibungawarui", new string[]{"to feel sick"}, "hiragana", "i", ""), 
                new JapaneseWord("くらい", "kurai", new string[]{"dark"}, "hiragana", "i", ""), 
                new JapaneseWord("はずかしい", "hazukashii", new string[]{"embarassing", "to feel embarassed"}, "hiragana", "i", ""), 
                new JapaneseWord("はく", "aku", new string[]{"(something) opens"}, "hiragana", "", ""), 
                new JapaneseWord("あやまる", "ayamaru", new string[]{"to apologize"}, "hiragana", "", ""), 
                new JapaneseWord("おす", "osu", new string[]{"to press", "to push"}, "hiragana", "", ""), 
                new JapaneseWord("おとす", "otosu", new string[]{"to drop (something)"}, "hiragana", "", ""), 
                new JapaneseWord("おゆがわく", "oyugawaku", new string[]{"water boils"}, "hiragana", "", ""), 
                new JapaneseWord("ころぶ", "korobu", new string[]{"to fall down"}, "hiragana", "", ""), 
                new JapaneseWord("こわす", "kowasu", new string[]{"to break (something)"}, "hiragana", "", ""), 
                new JapaneseWord("さく", "saku", new string[]{"to bloom"}, "hiragana", "", ""), 
                new JapaneseWord("しまる", "shimaru", new string[]{"(something) closes"}, "hiragana", "", ""), 
                new JapaneseWord("たすかる", "tasukaru", new string[]{"to be saved", "to be helped"}, "hiragana", "", ""), 
                new JapaneseWord("たのむ", "tanomu", new string[]{"to ask (a favor)"}, "hiragana", "", ""), 
                new JapaneseWord("つく", "tsuku", new string[]{"(something) turns on"}, "hiragana", "", ""), 
                new JapaneseWord("よごす", "yogosu", new string[]{"to make dirty"}, "hiragana", "", ""), 
                new JapaneseWord("おちる", "ochiru", new string[]{"(something) drops"}, "hiragana", "", ""), 
                new JapaneseWord("かたづける", "katadukeru", new string[]{"to tidy up"}, "hiragana", "", ""), 
                new JapaneseWord("かんがえる", "kangaeru", new string[]{"to think (about)", "to consider"}, "hiragana", "", ""), 
                new JapaneseWord("きえる", "kieru", new string[]{"(something) goes off", "(something) disappears"}, "hiragana", "", ""), 
                new JapaneseWord("こわれる", "kowareru", new string[]{"(something) breaks"}, "hiragana", "", ""), 
                new JapaneseWord("よごれる", "yogoreru", new string[]{"to become dirty"}, "hiragana", "", ""), 
                new JapaneseWord("ちゅうもんする", "chuumonsuru", new string[]{"to place an order"}, "hiragana", "", ""), 
                new JapaneseWord("エアコン", "eakon", new string[]{"air conditioner"}, "katakana", "", ""), 
                new JapaneseWord("カーチン", "kaatin", new string[]{"curtain"}, "katakana", "", ""), 
                new JapaneseWord("クッション", "kusshon", new string[]{"cushion"}, "katakana", "", ""), 
                new JapaneseWord("シャンプー", "shanpuu", new string[]{"shampoo"}, "katakana", "", ""), 
                new JapaneseWord("スイッチ", "suicchi", new string[]{"switch"}, "katakana", "", ""), 
                new JapaneseWord("スープ", "suupu", new string[]{"soup"}, "katakana", "", ""), 
                new JapaneseWord("スカート", "sukaato", new string[]{"skirt"}, "katakana", "", ""), 
                new JapaneseWord("ソファ", "sofa", new string[]{"sofa"}, "katakana", "", ""), 
                new JapaneseWord("タオル", "taoru", new string[]{"towel"}, "katakana", "", ""), 
                new JapaneseWord("ポップコーン", "poppukoon", new string[]{"popcorn"}, "katakana", "", "") 
            };
            
            var chapter19 = new JapaneseWord[]
            {
                new JapaneseWord("おくさま", "okusama", new string[]{"(your/his) wife"}, "hiragana", "", ""), 
                new JapaneseWord("おこさん", "okosan", new string[]{"(your/their) child"}, "hiragana", "", ""), 
                new JapaneseWord("おれい", "orei", new string[]{"expression of gratitude"}, "hiragana", "", ""), 
                new JapaneseWord("けいご", "keigo", new string[]{"honorific language"}, "hiragana", "", ""), 
                new JapaneseWord("こちら", "kochira", new string[]{"this way (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("しゅっちょう", "shucchou", new string[]{"business trip"}, "hiragana", "", ""), 
                new JapaneseWord("しゅるい", "shurui", new string[]{"a kind", "a sort"}, "hiragana", "", ""), 
                new JapaneseWord("せいかく", "seikaku", new string[]{"personality"}, "hiragana", "", ""), 
                new JapaneseWord("ちゅうがくせい", "chuugakusei", new string[]{"junior high school student"}, "hiragana", "", ""), 
                new JapaneseWord("どちら", "dochira", new string[]{"where (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("なまけもの", "namakemono", new string[]{"lazy person"}, "hiragana", "", ""), 
                new JapaneseWord("なやみ", "nayami", new string[]{"worry"}, "hiragana", "", ""), 
                new JapaneseWord("はずかしがりや", "hazukashigariya", new string[]{"shy person"}, "hiragana", "", ""), 
                new JapaneseWord("はなし", "hanashi", new string[]{"chat", "talk"}, "hiragana", "", ""), 
                new JapaneseWord("ぶちょう", "buchou", new string[]{"department manager"}, "hiragana", "", ""), 
                new JapaneseWord("ぶんか", "bunka", new string[]{"culture"}, "hiragana", "", ""), 
                new JapaneseWord("まちがい", "machigai", new string[]{"mistake"}, "hiragana", "", ""), 
                new JapaneseWord("なかがいい", "nakagaii", new string[]{"be on good terms", "to be close with", "to get along well"}, "hiragana", "i", ""), 
                new JapaneseWord("まじめ", "majime", new string[]{"serious", "sober", "diligent"}, "hiragana", "na", ""), 
                new JapaneseWord("いらっしゃる", "irassharu", new string[]{"honorific expression for iku, kuru, and iru"}, "hiragana", "", ""), 
                new JapaneseWord("おくる", "okuru", new string[]{"to walk/drive (someone)"}, "hiragana", "", ""), 
                new JapaneseWord("おこる", "okoru", new string[]{"to get angry"}, "hiragana", "", ""), 
                new JapaneseWord("おっしゃる", "ossharu", new string[]{"honorific expression for iu"}, "hiragana", "", ""), 
                new JapaneseWord("おやすみになる", "oyasumininaru", new string[]{"honorific expression for neru"}, "hiragana", "", ""), 
                new JapaneseWord("きまる", "kimaru", new string[]{"to be decided"}, "hiragana", "", ""), 
                new JapaneseWord("くださる", "kudasaru", new string[]{"honorific expression for kureru"}, "hiragana", "", ""), 
                new JapaneseWord("ごらんになる", "goranninaru", new string[]{"honorific expression for miru"}, "hiragana", "", ""), 
                new JapaneseWord("しりあう", "shiriau", new string[]{"to get acquainted with"}, "hiragana", "", ""), 
                new JapaneseWord("~ていらっしゃる", "~teirassharu", new string[]{"honoritic expression for ~teiru"}, "hiragana", "", ""), 
                new JapaneseWord("なさる", "nasaru", new string[]{"honorific expression for suru"}, "hiragana", "", ""), 
                new JapaneseWord("ひっこす", "hikkosu", new string[]{"to move (to another place to live)"}, "hiragana", "", ""), 
                new JapaneseWord("めしあがる", "meshiagaru", new string[]{"honorific expression for taberu and nomu"}, "hiragana", "", ""), 
                new JapaneseWord("よぶ", "yobu", new string[]{"to call (one's name)", "to invite"}, "hiragana", "", ""), 
                new JapaneseWord("よる", "yoru", new string[]{"to stop by"}, "hiragana", "", ""), 
                new JapaneseWord("おくれる", "okureru", new string[]{"to become late"}, "hiragana", "", ""), 
                new JapaneseWord("かける", "kakeru", new string[]{"to sit down"}, "hiragana", "", ""), 
                new JapaneseWord("はれる", "hareru", new string[]{"to become sunny"}, "hiragana", "", ""), 
                new JapaneseWord("もてる", "moteru", new string[]{"to be popular (in terms of romantic interest)"}, "hiragana", "", ""), 
                new JapaneseWord("えんりょする", "enryosuru", new string[]{"to hold back for the time being", "to refrain from"}, "hiragana", "", ""), 
                new JapaneseWord("ごちそうする", "gochisousuru", new string[]{"to treat/invite (someone) to a meal"}, "hiragana", "", ""), 
                new JapaneseWord("しょうたいする", "shoutaisuru", new string[]{"to invite someone (to an event/place)"}, "hiragana", "", ""), 
                new JapaneseWord("ちゅういする", "chuuisuru", new string[]{"to watch out", "to give warning"}, "hiragana", "", ""), 
                new JapaneseWord("はなしをする", "hanashiwosuru", new string[]{"to have a talk"}, "hiragana", "", "")
            };
            
            var chapter20 = new JapaneseWord[]
            {
                new JapaneseWord("あちら", "achira", new string[]{"that way (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("うちゅうじん", "uchuujin", new string[]{"space alien"}, "hiragana", "", ""), 
                new JapaneseWord("おと", "oto", new string[]{"sound"}, "hiragana", "", ""), 
                new JapaneseWord("おにぎり", "onigiri", new string[]{"rice ball"}, "hiragana", "", ""), 
                new JapaneseWord("かかりのもの", "kakarinomono", new string[]{"our person in charge"}, "hiragana", "", ""), 
                new JapaneseWord("かど", "kado", new string[]{"corner"}, "hiragana", "", ""), 
                new JapaneseWord("くうこう", "kuukou", new string[]{"airport"}, "hiragana", "", ""), 
                new JapaneseWord("じ", "ji", new string[]{"letter", "character"}, "hiragana", "", ""), 
                new JapaneseWord("してん", "shiten", new string[]{"branch office"}, "hiragana", "", ""), 
                new JapaneseWord("しゅみ", "shumi", new string[]{"hobby", "pastime"}, "hiragana", "", ""), 
                new JapaneseWord("しょうせつ", "shousetsu", new string[]{"novel"}, "hiragana", "", ""), 
                new JapaneseWord("しんごう", "shingou", new string[]{"traffic light"}, "hiragana", "", ""), 
                new JapaneseWord("せんす", "sensu", new string[]{"fan"}, "hiragana", "", ""), 
                new JapaneseWord("つき", "tsuki", new string[]{"moon"}, "hiragana", "", ""), 
                new JapaneseWord("でんしじしょ", "denshijisho", new string[]{"electronic dictionary"}, "hiragana", "", ""), 
                new JapaneseWord("~や", "~ya", new string[]{"~shop"}, "hiragana", "", ""), 
                new JapaneseWord("おもい", "omoi", new string[]{"heavy", "serious (illness)"}, "hiragana", "i", ""), 
                new JapaneseWord("かるい", "karui", new string[]{"light"}, "hiragana", "i", ""), 
                new JapaneseWord("いたす", "itasu", new string[]{"extra-modest expression for suru"}, "hiragana", "", ""), 
                new JapaneseWord("いただく", "itadaku", new string[]{"extra-modest expression for taberu and nomu"}, "hiragana", "", ""), 
                new JapaneseWord("いただく", "itadaku", new string[]{"humble expression for morau"}, "hiragana", "", ""), 
                new JapaneseWord("うかがう", "ukagau", new string[]{"to humbly visit", "to humbly ask"}, "hiragana", "", ""), 
                new JapaneseWord("おる", "oru", new string[]{"extra-modest expression for iru"}, "hiragana", "", ""), 
                new JapaneseWord("ござる", "gozaru", new string[]{"extra-modest expression for aru"}, "hiragana", "", ""), 
                new JapaneseWord("~ておる", "~teoru", new string[]{"extra-modest expression for ~teiru"}, "hiragana", "", ""), 
                new JapaneseWord("~でござる", "~degozaru", new string[]{"extra-modest expression for desu"}, "hiragana", "", ""), 
                new JapaneseWord("まいる", "mairu", new string[]{"extra-modest expression for iku and kuru"}, "hiragana", "", ""), 
                new JapaneseWord("まがる", "magaru", new string[]{"to turn (right/left)"}, "hiragana", "", ""), 
                new JapaneseWord("もうす", "mousu", new string[]{"extra-modest expression for iu"}, "hiragana", "", ""), 
                new JapaneseWord("もどる", "modoru", new string[]{"to return", "to come back"}, "hiragana", "", ""), 
                new JapaneseWord("きこえる", "kikoeru", new string[]{"to be audible"}, "hiragana", "", ""), 
                new JapaneseWord("さしあげる", "sashiageru", new string[]{"humble expression for ageru"}, "hiragana", "", ""), 
                new JapaneseWord("つたえる", "tsutaeru", new string[]{"to convey (message)"}, "hiragana", "", ""), 
                new JapaneseWord("またせる", "mataseru", new string[]{"to keep (someone) waiting"}, "hiragana", "", ""), 
                new JapaneseWord("こうかんする", "koukansuru", new string[]{"to exchange"}, "hiragana", "", ""), 
                new JapaneseWord("せいかつする", "seikatsusuru", new string[]{"to lead a life"}, "hiragana", "", ""), 
                new JapaneseWord("へんぴんする", "henpinsuru", new string[]{"to return (merchandise)"}, "hiragana", "", ""), 
                new JapaneseWord("アニメ", "anime", new string[]{"animation"}, "katakana", "", ""), 
                new JapaneseWord("スニーカー", "suniikaa", new string[]{"sneakers"}, "katakana", "", ""), 
                new JapaneseWord("ドイツ", "doitsu", new string[]{"Germany"}, "katakana", "", ""), 
                new JapaneseWord("ハイヒール", "haihiiru", new string[]{"high heels"}, "katakana", "", "")
            };

            genkiVocab.Add(1, chapter1);
            genkiVocab.Add(2, chapter2);
            genkiVocab.Add(3, chapter3);
            genkiVocab.Add(4, chapter4);
            genkiVocab.Add(5, chapter5);
            genkiVocab.Add(6, chapter6);
            genkiVocab.Add(7, chapter7);
            genkiVocab.Add(8, chapter8);
            genkiVocab.Add(9, chapter9);
            genkiVocab.Add(10, chapter10);
            genkiVocab.Add(11, chapter11);
            genkiVocab.Add(12, chapter12);
            genkiVocab.Add(13, chapter13);
            genkiVocab.Add(14, chapter14);
            genkiVocab.Add(15, chapter15);
            genkiVocab.Add(16, chapter16);
            genkiVocab.Add(17, chapter17);
            genkiVocab.Add(18, chapter18);
            genkiVocab.Add(19, chapter19);
            genkiVocab.Add(20, chapter20);

            return genkiVocab;
        }
    }
}
