using System;

namespace Japanese_Review
{
    /*
     * The Japanese Word class holds the following information:
     * japanese - the word written in japanese
     * romaji - conversion of the japanese word to latin
     * english - a list of english definitions of the word
     * writing - the syllabic writing for the word (hiragana or katakana)
     * kanji - how the word is represented with kanji, if I have learned it
     */
    public class JapaneseWord
    {
        private String japanese;
        private String romaji;
        private String[] english;
        private String writing;
        private String adjective;
        private String kanji;

        public JapaneseWord(String japanese, String romaji, String[] english, String writing, String adjective,
            String kanji)
        {
            this.japanese = japanese;
            this.romaji = romaji;
            this.english = english;
            this.writing = writing;
            this.adjective = adjective;
            this.kanji = kanji;
        }

        /*
         *  Initialize 20 chapters of vocab from the Genki I & II textbooks
         *
            var chapter = new JapaneseWord[]
            {
                new JapaneseWord("", new String[]{""}, "hiragana", "", ""), 
                new JapaneseWord("", new String[]{""}, "katakana", "", ""), 
            };
         */
        public static JapaneseWord[][] initGenki()
        {
            var genkiVocab = new JapaneseWord[20][];
            
            var chapter1 = new JapaneseWord[]
            {
                new JapaneseWord("あの", "ano", new String[] {"um..."}, "hiragana", "", ""),
                new JapaneseWord("いま", "ima", new String[] {"now"}, "hiragana", "", ""),
                new JapaneseWord("えいご", "eigo", new String[] {"English"}, "hiragana", "", ""),
                new JapaneseWord("ええ", "ee", new String[] {"yes"}, "hiragana", "", ""),
                new JapaneseWord("がくせい", "gakusei", new String[] {"student"}, "hiragana", "", ""),
                new JapaneseWord("~ご", "~go", new String[] {"language"}, "hiragana", "", ""),
                new JapaneseWord("こうこう", "koukou", new String[] {"high school"}, "hiragana", "", ""),
                new JapaneseWord("ごご", "gogo", new String[] {"P.M."}, "hiragana", "", ""),
                new JapaneseWord("ごぜん", "gozen", new String[] {"A.M"}, "hiragana", "", ""),
                new JapaneseWord("~さい", "~sai", new String[] {"~years old"}, "hiragana", "", ""),
                new JapaneseWord("~さん", "~san", new String[] {"Mr.", "Mrs."}, "hiragana", "", ""),
                new JapaneseWord("~じ", "~ji", new String[] {"o'clock"}, "hiragana", "", ""),
                new JapaneseWord("~じん", "~jin", new String[] {"~people"}, "hiragana", "", ""),
                new JapaneseWord("せんこう", "senkou", new String[] {"major"}, "hiragana", "", ""),
                new JapaneseWord("せんせい", "sensei", new String[] {"teacher", "professor"}, "hiragana", "", ""),
                new JapaneseWord("そうです", "sou desu", new String[] {"that's right"}, "hiragana", "", ""),
                new JapaneseWord("そうですか", "sou desu ka", new String[] {"I see", "is that so?"}, "hiragana", "", ""),
                new JapaneseWord("だいがく", "daigaku", new String[] {"college", "university"}, "hiragana", "", ""),
                new JapaneseWord("でんわ", "denwa", new String[] {"telephone"}, "hiragana", "", ""),
                new JapaneseWord("ともだち", "tomodachi", new String[] {"friend"}, "hiragana", "", ""),
                new JapaneseWord("まなえ", "namae", new String[] {"name"}, "hiragana", "", ""),
                new JapaneseWord("にほん", "nihon", new String[] {"Japan"}, "hiragana", "", ""),
                new JapaneseWord("~ねんせい", "~nensei", new String[] {"~year student"}, "hiragana", "", ""),
                new JapaneseWord("はい", "hai", new String[] {"yes"}, "hiragana", "", ""),
                new JapaneseWord("はん", "han", new String[] {"half"}, "hiragana", "", ""),
                new JapaneseWord("ばんごう", "bangou", new String[] {"number"}, "hiragana", "", ""),
                new JapaneseWord("りゅうがくせい", "ryuugakusei", new String[] {"international student"}, "hiragana", "", ""),
                new JapaneseWord("わたし", "watashi", new String[] {"I"}, "hiragana", "", ""),
                new JapaneseWord("ちゅうごく", "Chuugoku", new String[] {"China"}, "hiragana", "", ""),
                new JapaneseWord("かんこく", "Kankoku", new String[] {"Korea"}, "hiragana", "", ""),
                new JapaneseWord("かがく", "kagaku", new String[] {"science"}, "hiragana", "", ""),
                new JapaneseWord("けいざい", "keizai", new String[] {"economics"}, "hiragana", "", ""),
                new JapaneseWord("こくさいかんけい", "kokusaikankei", new String[] {"international relations"}, "hiragana", "", ""),
                new JapaneseWord("じんるいがく", "jinruigaku", new String[] {"anthropology"}, "hiragana", "", ""),
                new JapaneseWord("せいじ", "seeji", new String[] {"politics"}, "hiragana", "", ""),
                new JapaneseWord("ぶんがく", "bungaku", new String[] {"literature"}, "hiragana", "", ""),
                new JapaneseWord("れきし", "rekishi", new String[] {"history"}, "hiragana", "", ""),
                new JapaneseWord("しごと", "shigoto", new String[] {"job", "work", "occupation"}, "hiragana", "", ""),
                new JapaneseWord("いしゃ", "isha", new String[] {"doctor"}, "hiragana", "", ""),
                new JapaneseWord("かいしゃいん", "kaishain", new String[] {"office worker"}, "hiragana", "", ""),
                new JapaneseWord("こうこうせい", "koukousei", new String[] {"high school student"}, "hiragana", "", ""),
                new JapaneseWord("しゅふ", "shufu", new String[] {"housewife"}, "hiragana", "", ""),
                new JapaneseWord("だいがくいんせい", "daigakuinsei", new String[] {"graduate student"}, "hiragana", "", ""),
                new JapaneseWord("だいがくせい", "daigakusei", new String[] {"college student"}, "hiragana", "", ""),
                new JapaneseWord("べんごし", "bengoshi", new String[] {"lawyer"}, "hiragana", "", ""),
                new JapaneseWord("おかあさん", "okaasan", new String[] {"mother"}, "hiragana", "", ""),
                new JapaneseWord("おとうさん", "otousan", new String[] {"father"}, "hiragana", "", ""),
                new JapaneseWord("おねえさん", "oneesan", new String[] {"older sister"}, "hiragana", "", ""),
                new JapaneseWord("おにいさん", "oniisan", new String[] {"older brother"}, "hiragana", "", ""),
                new JapaneseWord("いもうと", "imouto", new String[] {"younger sister"}, "hiragana", "", ""),
                new JapaneseWord("おとうと", "otouto", new String[] {"younger brother"}, "hiragana", "", ""),
                new JapaneseWord("アメリカ", "Amerika", new String[] {"U.S.A."}, "katakana", "", ""),
                new JapaneseWord("イギリス", "Igirisu", new String[] {"Britain"}, "katakana", "", ""),
                new JapaneseWord("オーストラリア", "Oosutoraria", new String[] {"Australia"}, "katakana", "", ""),
                new JapaneseWord("スウェーデン", "Suweeden", new String[] {"Sweden"}, "katakana", "", ""),
                new JapaneseWord("コンピューター", "konpyuutaa", new String[] {"computer"}, "katakana", "", ""),
                new JapaneseWord("ビジネス", "bijinesu", new String[] {"business"}, "katakana", "", "")
            };

            var chapter2 = new JapaneseWord[]
            {
                new JapaneseWord("これ", "kore", new String[] {"this one"}, "hiragana", "", ""),
                new JapaneseWord("それ", "sore", new String[] {"that one"}, "hiragana", "", ""),
                new JapaneseWord("あれ", "are", new String[] {"that one over there"}, "hiragana", "", ""),
                new JapaneseWord("どれ", "dore", new String[] {"which one"}, "hiragana", "", ""),
                new JapaneseWord("この", "kono", new String[] {"this..."}, "hiragana", "", ""),
                new JapaneseWord("その", "sono", new String[] {"that..."}, "hiragana", "", ""),
                new JapaneseWord("あの", "ano", new String[] {"that... over there"}, "hiragana", "", ""),
                new JapaneseWord("どの", "dono", new String[] {"which..."}, "hiragana", "", ""),
                new JapaneseWord("ここ", "koko", new String[] {"here"}, "hiragana", "", ""),
                new JapaneseWord("そこ", "soko", new String[] {"there"}, "hiragana", "", ""),
                new JapaneseWord("あそこ", "asoko", new String[] {"over there"}, "hiragana", "", ""),
                new JapaneseWord("どこ", "doko", new String[] {"where"}, "hiragana", "", ""),
                new JapaneseWord("だれ", "dare", new String[] {"who"}, "hiragana", "", ""),
                new JapaneseWord("おいしい", "oishii", new String[] {"delicious"}, "hiragana", "i", ""),
                new JapaneseWord("さかな", "sakana", new String[] {"fish"}, "hiragana", "", ""),
                new JapaneseWord("とんかつ", "tonkatsu", new String[] {"pork cutlet"}, "hiragana", "", ""),
                new JapaneseWord("にく", "niku", new String[] {"meat"}, "hiragana", "", ""),
                new JapaneseWord("やさい", "yasai", new String[] {"vegetable"}, "hiragana", "", ""),
                new JapaneseWord("えんぴつ", "enpitsu", new String[] {"pencil"}, "hiragana", "", ""),
                new JapaneseWord("かさ", "kasa", new String[] {"umbrella"}, "hiragana", "", ""),
                new JapaneseWord("かばん", "kaban", new String[] {"bag"}, "hiragana", "", ""),
                new JapaneseWord("くつ", "kutsu", new String[] {"shoes"}, "hiragana", "", ""),
                new JapaneseWord("さいふ", "saifu", new String[] {"wallet"}, "hiragana", "", ""),
                new JapaneseWord("じしょ", "jisho", new String[] {"dictionary"}, "hiragana", "", ""),
                new JapaneseWord("じてんしゃ", "jitensha", new String[] {"bicycle"}, "hiragana", "", ""),
                new JapaneseWord("しんぶん", "shinbun", new String[] {"newspaper"}, "hiragana", "", ""),
                new JapaneseWord("とけい", "tokei", new String[] {"watch", "clock"}, "hiragana", "", ""),
                new JapaneseWord("ぼうし", "boushi", new String[] {"hat", "cap"}, "hiragana", "", ""),
                new JapaneseWord("ほん", "hon", new String[] {"book"}, "hiragana", "", ""),
                new JapaneseWord("きっさてん", "kissaten", new String[] {"cafe"}, "hiragana", "", ""),
                new JapaneseWord("ぎんこう", "ginkou", new String[] {"bank"}, "hiragana", "", ""),
                new JapaneseWord("としょかん", "toshokan", new String[] {"library"}, "hiragana", "", ""),
                new JapaneseWord("ゆうびんきょく", "yuubinkyoku", new String[] {"post office"}, "hiragana", "", ""),
                new JapaneseWord("いくら", "ikura", new String[] {"how much"}, "hiragana", "", ""),
                new JapaneseWord("~えん", "~en", new String[] {"~yen"}, "hiragana", "", ""),
                new JapaneseWord("たかい", "takai", new String[] {"expensive", "high"}, "hiragana", "i", ""),
                new JapaneseWord("メニュー", "menyuu", new String[] {"menu"}, "katakana", "", ""),
                new JapaneseWord("ジーンズ", "jiinzu", new String[] {"jeans"}, "katakana", "", ""),
                new JapaneseWord("Tシャツ", "tiishatsu", new String[] {"T-shirt"}, "katakana", "", ""),
                new JapaneseWord("ノート", "nooto", new String[] {"notebook"}, "katakana", "", ""),
                new JapaneseWord("ペン", "pen", new String[] {"pen"}, "katakana", "", ""),
                new JapaneseWord("トイレ", "toire", new String[] {"toilet", "restroom"}, "katakana", "", "")
            };

            var chapter3 = new JapaneseWord[]
            {
                new JapaneseWord("えいが", "eiga", new String[] {"movie"}, "hiragana", "", ""),
                new JapaneseWord("おんがく", "ongaku", new String[] {"music"}, "hiragana", "", ""),
                new JapaneseWord("ざっし", "zasshi", new String[] {"magazine"}, "hiragana", "", ""),
                new JapaneseWord("あさごはん", "asagohan", new String[] {"breakfast"}, "hiragana", "", ""),
                new JapaneseWord("おさけ", "osake", new String[] {"sake", "alcohol"}, "hiragana", "", ""),
                new JapaneseWord("おちゃ", "ocha", new String[] {"tea"}, "hiragana", "", ""),
                new JapaneseWord("ばんごはん", "bangohan", new String[] {"dinner"}, "hiragana", "", ""),
                new JapaneseWord("ひるごはん", "hirugohan", new String[] {"lunch"}, "hiragana", "", ""),
                new JapaneseWord("みず", "mizu", new String[] {"water"}, "hiragana", "", ""),
                new JapaneseWord("いえ", "ie", new String[] {"home", "house"}, "hiragana", "", ""),
                new JapaneseWord("うち", "uchi", new String[] {"home", "house", "my place"}, "hiragana", "", ""),
                new JapaneseWord("がっこう", "gakkou", new String[] {"school"}, "hiragana", "", ""),
                new JapaneseWord("あさ", "asa", new String[] {"morning"}, "hiragana", "", ""),
                new JapaneseWord("あした", "ashita", new String[] {"tomorrow"}, "hiragana", "", ""),
                new JapaneseWord("いつ", "itsu", new String[] {"when"}, "hiragana", "", ""),
                new JapaneseWord("きょう", "kyou", new String[] {"today"}, "hiragana", "", ""),
                new JapaneseWord("~ごろ", "~goro", new String[] {"at about..."}, "hiragana", "", ""),
                new JapaneseWord("こんばん", "konban", new String[] {"tonight"}, "hiragana", "", ""),
                new JapaneseWord("しゅうまつ", "shuumatsu", new String[] {"weekend"}, "hiragana", "", ""),
                new JapaneseWord("どようび", "doyoubi", new String[] {"Saturday"}, "hiragana", "", ""),
                new JapaneseWord("にちようび", "nichiyoubi", new String[] {"Sunday"}, "hiragana", "", ""),
                new JapaneseWord("まいにち", "mainichi", new String[] {"every day"}, "hiragana", "", ""),
                new JapaneseWord("まいばん", "maiban", new String[] {"every night"}, "hiragana", "", ""),
                new JapaneseWord("いく", "iku", new String[] {"to go"}, "hiragana", "", ""),
                new JapaneseWord("かえる", "kaeru", new String[] {"to go back", "to return"}, "hiragana", "", ""),
                new JapaneseWord("きく", "kiku", new String[] {"to listen", "to hear"}, "hiragana", "", ""),
                new JapaneseWord("のむ", "nomu", new String[] {"to drink"}, "hiragana", "", ""),
                new JapaneseWord("はなす", "hanasu", new String[] {"to speak", "to talk"}, "hiragana", "", ""),
                new JapaneseWord("よむ", "yomu", new String[] {"to read"}, "hiragana", "", ""),
                new JapaneseWord("おきる", "okiru", new String[] {"to get up"}, "hiragana", "", ""),
                new JapaneseWord("たべる", "taberu", new String[] {"to eat"}, "hiragana", "", ""),
                new JapaneseWord("ねる", "neru", new String[] {"to sleep", "to go to sleep"}, "hiragana", "", ""),
                new JapaneseWord("みる", "miru", new String[] {"to see", "to look at", "to watch"}, "hiragana", "", ""),
                new JapaneseWord("くる", "kuru", new String[] {"to come"}, "hiragana", "", ""),
                new JapaneseWord("する", "suru", new String[] {"to do"}, "hiragana", "", ""),
                new JapaneseWord("べんきょうする", "benkyousuru", new String[] {"to study"}, "hiragana", "", ""),
                new JapaneseWord("いい", "ii", new String[] {"good"}, "hiragana", "i", ""),
                new JapaneseWord("はやい", "hayai", new String[] {"early"}, "hiragana", "i", ""),
                new JapaneseWord("あまり", "amari", new String[] {"not much"}, "hiragana", "", ""),
                new JapaneseWord("ぜんぜん", "zenzen", new String[] {"not at all"}, "hiragana", "", ""),
                new JapaneseWord("たいてい", "taitei", new String[] {"usually"}, "hiragana", "", ""),
                new JapaneseWord("ちょっと", "chotto", new String[] {"a little"}, "hiragana", "", ""),
                new JapaneseWord("ときどき", "tokidoki", new String[] {"sometimes"}, "hiragana", "", ""),
                new JapaneseWord("よく", "yoku", new String[] {"often", "much"}, "hiragana", "", ""),
                new JapaneseWord("スポツ", "supotsu", new String[] {"sports"}, "katakana", "", ""),
                new JapaneseWord("デート", "deeto", new String[] {"date"}, "katakana", "", ""),
                new JapaneseWord("テニス", "tenisu", new String[] {"tennis"}, "katakana", "", ""),
                new JapaneseWord("テレビ", "terebi", new String[] {"TV"}, "katakana", "", ""),
                new JapaneseWord("アイスクレーム", "aisukureemu", new String[] {"ice cream"}, "katakana", "", ""),
                new JapaneseWord("コーヒー", "koohii", new String[] {"coffee"}, "katakana", "", ""),
                new JapaneseWord("ハンバーガー", "hanbaagaa", new String[] {"hamburger"}, "katakana", "", "")
            };

            var chapter4 = new JapaneseWord[]
            {
                new JapaneseWord("かいもの", "kaimono", new String[] {"shopping"}, "hiragana", "", ""),
                new JapaneseWord("あなた", "anata", new String[] {"you"}, "hiragana", "", ""),
                new JapaneseWord("いす", "isu", new String[] {"chair"}, "hiragana", "", ""),
                new JapaneseWord("いぬ", "inu", new String[] {"dog"}, "hiragana", "", ""),
                new JapaneseWord("おみやげ", "omiyage", new String[] {"souvenir"}, "hiragana", "", ""),
                new JapaneseWord("こども", "kodomo", new String[] {"child"}, "hiragana", "", ""),
                new JapaneseWord("ごはん", "gohan", new String[] {"rice", "meal"}, "hiragana", "", ""),
                new JapaneseWord("しゃしん", "shashin", new String[] {"picture", "photo", "photograph"}, "hiragana", "", ""),
                new JapaneseWord("つくえ", "tsukue", new String[] {"desk"}, "hiragana", "", ""),
                new JapaneseWord("てがみ", "tegami", new String[] {"letter"}, "hiragana", "", ""),
                new JapaneseWord("ねこ", "neko", new String[] {"cat"}, "hiragana", "", ""),
                new JapaneseWord("ひと", "hito", new String[] {"person"}, "hiragana", "", ""),
                new JapaneseWord("おてら", "otera", new String[] {"temple"}, "hiragana", "", ""),
                new JapaneseWord("こうえん", "kouen", new String[] {"park"}, "hiragana", "", ""),
                new JapaneseWord("びょういん", "byouin", new String[] {"hospital"}, "hiragana", "", ""),
                new JapaneseWord("ほんや", "honya", new String[] {"bookstore"}, "hiragana", "", ""),
                new JapaneseWord("まち", "machi", new String[] {"town", "city"}, "hiragana", "", ""),
                new JapaneseWord("きのう", "kinou", new String[] {"yesterday"}, "hiragana", "", ""),
                new JapaneseWord("~じかん", "~jikan", new String[] {"~hours"}, "hiragana", "", ""),
                new JapaneseWord("せんしゅう", "senshuu", new String[] {"last week"}, "hiragana", "", ""),
                new JapaneseWord("とき", "toki", new String[] {"when...", "at the time of..."}, "hiragana", "", ""),
                new JapaneseWord("げつようび", "getsuyoubi", new String[] {"Monday"}, "hiragana", "", ""),
                new JapaneseWord("かようび", "kayoubi", new String[] {"Tuesday"}, "hiragana", "", ""),
                new JapaneseWord("すいようび", "suiyoubi", new String[] {"Wednesday"}, "hiragana", "", ""),
                new JapaneseWord("もくようび", "mokuyoubi", new String[] {"Thursday"}, "hiragana", "", ""),
                new JapaneseWord("きにょうび", "kinyoubi", new String[] {"Friday"}, "hiragana", "", ""),
                new JapaneseWord("あう", "au", new String[] {"to meet", "to see a person"}, "hiragana", "", ""),
                new JapaneseWord("ある", "aru", new String[] {"to exist", "there is..."}, "hiragana", "", ""),
                new JapaneseWord("かう", "kau", new String[] {"to buy"}, "hiragana", "", ""),
                new JapaneseWord("かく", "kaku", new String[] {"to write", "to paint"}, "hiragana", "", ""),
                new JapaneseWord("とる", "toru", new String[] {"to take", "to get a grade"}, "hiragana", "", ""),
                new JapaneseWord("まつ", "matsu", new String[] {"to wait"}, "hiragana", "", ""),
                new JapaneseWord("わかる", "wakaru", new String[] {"to understand"}, "hiragana", "", ""),
                new JapaneseWord("いる", "iru", new String[] {"to exist", "is in...", "stays at..."}, "hiragana", "", ""),
                new JapaneseWord("あるばいと", "arubaito", new String[] {"part-time job"}, "katakana", "", ""),
                new JapaneseWord("クラス", "kurasu", new String[] {"class"}, "katakana", "", ""),
                new JapaneseWord("パン", "pan", new String[] {"bread"}, "katakana", "", ""),
                new JapaneseWord("メール", "meeru", new String[] {"e-mail"}, "katakana", "", ""),
                new JapaneseWord("スーパー", "suupaa", new String[] {"supermarket"}, "katakana", "", ""),
                new JapaneseWord("デパート", "depaato", new String[] {"department store"}, "katakana", "", ""),
                new JapaneseWord("バステイ", "basutei", new String[] {"bus stop"}, "katakana", "", ""),
                new JapaneseWord("ホテル", "hoteru", new String[] {"hotel"}, "katakana", "", ""),
                new JapaneseWord("レストラン", "resutoran", new String[] {"restaurant"}, "katakana", "", "")
            };

            var chapter5 = new JapaneseWord[]
            {
                new JapaneseWord("うみ", "umi", new String[] {"sea"}, "hiragana", "", ""),
                new JapaneseWord("きって", "kitte", new String[] {"postal stamps"}, "hiragana", "", ""),
                new JapaneseWord("きっぷ", "kippu", new String[] {"ticket"}, "hiragana", "", ""),
                new JapaneseWord("しゅくだい", "shukudai", new String[] {"homework"}, "hiragana", "", ""),
                new JapaneseWord("たべもの", "tabemono", new String[] {"food"}, "hiragana", "", ""),
                new JapaneseWord("たんじょうぶ", "tanjoubi", new String[] {"birthday"}, "hiragana", "", ""),
                new JapaneseWord("てんき", "tenki", new String[] {"weather"}, "hiragana", "", ""),
                new JapaneseWord("のみもの", "nomimono", new String[] {"drink"}, "hiragana", "", ""),
                new JapaneseWord("はがき", "hagaki", new String[] {"postcard"}, "hiragana", "", ""),
                new JapaneseWord("ひこうき", "hikouki", new String[] {"airplane"}, "hiragana", "", ""),
                new JapaneseWord("へや", "heya", new String[] {"room"}, "hiragana", "", ""),
                new JapaneseWord("ぼく", "boku", new String[] {"I"}, "hiragana", "", ""),
                new JapaneseWord("やすみ", "yasumi", new String[] {"holiday", "day off", "absence"}, "hiragana", "", ""),
                new JapaneseWord("りょこう", "ryokou", new String[] {"travel"}, "hiragana", "", ""),
                new JapaneseWord("あたらしい", "atarashii", new String[] {"new"}, "hiragana", "i", ""),
                new JapaneseWord("あつい", "atsui", new String[] {"hot"}, "hiragana", "i", ""),
                new JapaneseWord("いそがしい", "isogashii", new String[] {"busy"}, "hiragana", "i", ""),
                new JapaneseWord("おおきい", "ookii", new String[] {"large"}, "hiragana", "i", ""),
                new JapaneseWord("おもしろい", "omoshiroi", new String[] {"interesting", "funny"}, "hiragana", "i", ""),
                new JapaneseWord("かっこいい", "kakkoii", new String[] {"cool", "good-looking"}, "hiragana", "i", ""),
                new JapaneseWord("こわい", "kowai", new String[] {"frightening"}, "hiragana", "i", ""),
                new JapaneseWord("さむい", "samui", new String[] {"cold"}, "hiragana", "i", ""),
                new JapaneseWord("たのしい", "tanoshii", new String[] {"fun"}, "hiragana", "i", ""),
                new JapaneseWord("ちいさい", "chiisai", new String[] {"small"}, "hiragana", "i", ""),
                new JapaneseWord("つまらない", "tsumaranai", new String[] {"boring"}, "hiragana", "i", ""),
                new JapaneseWord("ふるい", "furui", new String[] {"old"}, "hiragana", "i", ""),
                new JapaneseWord("むずかしい", "muzukashii", new String[] {"difficult"}, "hiragana", "i", ""),
                new JapaneseWord("やさしい", "yasashii", new String[] {"easy", "kind"}, "hiragana", "i", ""),
                new JapaneseWord("やすい", "yasui", new String[] {"inexpensive", "cheap"}, "hiragana", "i", ""),
                new JapaneseWord("きらい", "kirai", new String[] {"to dislike", "disgusted with"}, "hiragana", "na", ""),
                new JapaneseWord("きれい", "kirei", new String[] {"beautiful", "clean"}, "hiragana", "na", ""),
                new JapaneseWord("げんき", "genki", new String[] {"healthy", "energetic"}, "hiragana", "na", ""),
                new JapaneseWord("しずか", "shizuka", new String[] {"quiet"}, "hiragana", "na", ""),
                new JapaneseWord("すき", "suki", new String[] {"to like", "fond of"}, "hiragana", "na", ""),
                new JapaneseWord("だいきらい", "daikirai", new String[] {"to hate"}, "hiragana", "na", ""),
                new JapaneseWord("だいすき", "daisuki", new String[] {"to love", "very fond of"}, "hiragana", "na", ""),
                new JapaneseWord("にぎやか", "nigiyaka", new String[] {"lively"}, "hiragana", "na", ""),
                new JapaneseWord("ひま", "hima", new String[] {"not busy", "free"}, "hiragana", "na", ""),
                new JapaneseWord("およぐ", "oyogu", new String[] {"to swim"}, "hiragana", "", ""),
                new JapaneseWord("きく", "kiku", new String[] {"to ask"}, "hiragana", "", ""),
                new JapaneseWord("のる", "noru", new String[] {"to ride", "to board"}, "hiragana", "", ""),
                new JapaneseWord("やる", "yaru", new String[] {"to do", "to perform"}, "hiragana", "", ""),
                new JapaneseWord("でかける", "dekakeru", new String[] {"to go out"}, "hiragana", "", ""),
                new JapaneseWord("サーフィン", "saafin", new String[] {"surfing"}, "katakana", "", ""),
                new JapaneseWord("バス", "basu", new String[] {"bus"}, "katakana", "", "")
            };

            var chapter6 = new JapaneseWord[]
            {
                new JapaneseWord("おかね", "okane", new String[] {"money"}, "hiragana", "", ""),
                new JapaneseWord("おふろ", "ofuro", new String[] {"bath"}, "hiragana", "", ""),
                new JapaneseWord("かんじ", "kanji", new String[] {"kanji", "Chinese character"}, "hiragana", "", ""),
                new JapaneseWord("きょうかしょ", "kyoukasho", new String[] {"textbook"}, "hiragana", "", ""),
                new JapaneseWord("こんしゅう", "konshuu", new String[] {"this week"}, "hiragana", "", ""),
                new JapaneseWord("しんみんびょういん", "shiminbyouin", new String[] {"municipal hospital"}, "hiragana", "", ""),
                new JapaneseWord("つぎ", "tsugi", new String[] {"next"}, "hiragana", "", ""),
                new JapaneseWord("でんき", "denki", new String[] {"electricity"}, "hiragana", "", ""),
                new JapaneseWord("でんしゃ", "densha", new String[] {"train"}, "hiragana", "", ""),
                new JapaneseWord("にもつ", "nimotsu", new String[] {"baggage"}, "hiragana", "", ""),
                new JapaneseWord("まど", "mado", new String[] {"window"}, "hiragana", "", ""),
                new JapaneseWord("よる", "yoru", new String[] {"night"}, "hiragana", "", ""),
                new JapaneseWord("らいしゅう", "raishuu", new String[] {"next week"}, "hiragana", "", ""),
                new JapaneseWord("らいねん", "rainen", new String[] {"next year"}, "hiragana", "", ""),
                new JapaneseWord("たいへん", "taihen", new String[] {"tough"}, "hiragana", "na", ""),
                new JapaneseWord("あそぶ", "asobu", new String[] {"to play", "to spend time pleasantly"}, "hiragana", "", ""),
                new JapaneseWord("いそぐ", "isogu", new String[] {"to hurry"}, "hiragana", "", ""),
                new JapaneseWord("おふろにはいる", "ofuronihairu", new String[] {"to take a bath"}, "hiragana", "", ""),
                new JapaneseWord("かえす", "kaesu", new String[] {"to return"}, "hiragana", "", ""),
                new JapaneseWord("けす", "kesu", new String[] {"to turn off", "to erase"}, "hiragana", "", ""),
                new JapaneseWord("しぬ", "shinu", new String[] {"to die"}, "hiragana", "", ""),
                new JapaneseWord("すわる", "suwaru", new String[] {"to sit down"}, "hiragana", "", ""),
                new JapaneseWord("たつ", "tatsu", new String[] {"to stand up"}, "hiragana", "", ""),
                new JapaneseWord("たばこをすう", "tabakowosuu", new String[] {"to smoke"}, "hiragana", "", ""),
                new JapaneseWord("つかう", "tsukau", new String[] {"to use"}, "hiragana", "", ""),
                new JapaneseWord("てつだう", "tetsudau", new String[] {"to help"}, "hiragana", "", ""),
                new JapaneseWord("はいる", "hairu", new String[] {"to enter"}, "hiragana", "", ""),
                new JapaneseWord("もつ", "motsu", new String[] {"to carry", "to hold"}, "hiragana", "", ""),
                new JapaneseWord("やすむ", "yasumu", new String[] {"to be absent", "to rest"}, "hiragana", "", ""),
                new JapaneseWord("あける", "akeru", new String[] {"to open"}, "hiragana", "", ""),
                new JapaneseWord("おしえる", "oshieru", new String[] {"to teach", "to instruct"}, "hiragana", "", ""),
                new JapaneseWord("おりる", "oriru", new String[] {"to get off"}, "hiragana", "", ""),
                new JapaneseWord("かりる", "kariru", new String[] {"to borrow"}, "hiragana", "", ""),
                new JapaneseWord("しめる", "shimeru", new String[] {"to close"}, "hiragana", "", ""),
                new JapaneseWord("シャワーをあびる", "shawaawoabiru", new String[] {"to take a shower"}, "hiragana", "", ""),
                new JapaneseWord("つける", "tsukeru", new String[] {"to turn on"}, "hiragana", "", ""),
                new JapaneseWord("でんわをかける", "denwawokakeru", new String[] {"to make a phone call"}, "hiragana", "", ""),
                new JapaneseWord("わすれる", "wasureru", new String[] {"to forget", "to leave behind"}, "hiragana", "", ""),
                new JapaneseWord("つれてくる", "tsuretekuru", new String[] {"to bring (person)"}, "hiragana", "", ""),
                new JapaneseWord("もってくる", "mottekuru", new String[] {"to bring (thing)"}, "hiragana", "", ""),
                new JapaneseWord("シャワー", "shawaa", new String[] {"shower"}, "katakana", "", ""),
                new JapaneseWord("パソコン", "pasokon", new String[] {"computer"}, "katakana", "", ""),
                new JapaneseWord("ページ", "peeji", new String[] {"page"}, "katakana", "", "")
            };
            
            var chapter7 = new JapaneseWord[]
            {
                new JapaneseWord("あね", "ane", new String[]{"older sister"}, "hiragana", "", ""), 
                new JapaneseWord("いもうと", "imouto", new String[]{"younger sister"}, "hiragana", "", ""), 
                new JapaneseWord("うた", "uta", new String[]{"song"}, "hiragana", "", ""), 
                new JapaneseWord("おじいさん", "ojiisan", new String[]{"grandfather", "old man"}, "hiragana", "", ""), 
                new JapaneseWord("おとうと", "otouto", new String[]{"younger brother"}, "hiragana", "", ""), 
                new JapaneseWord("おとこのひと", "otokonohito", new String[]{"man"}, "hiragana", "", ""), 
                new JapaneseWord("おばあさん", "obaasan", new String[]{"grandmother", "old woman"}, "hiragana", "", ""), 
                new JapaneseWord("おんなのひと", "onnanohito", new String[]{"woman"}, "hiragana", "", ""), 
                new JapaneseWord("かいしゃ", "kaisha", new String[]{"company"}, "hiragana", "", ""), 
                new JapaneseWord("かぞく", "kazoku", new String[]{"family"}, "hiragana", "", ""), 
                new JapaneseWord("かみ", "kami", new String[]{"hair"}, "hiragana", "", ""), 
                new JapaneseWord("きょうだい", "kyoudai", new String[]{"siblings", "brothers and sisters"}, "hiragana", "", ""), 
                new JapaneseWord("くち", "kuchi", new String[]{"mouth"}, "hiragana", "", ""), 
                new JapaneseWord("くに", "kuni", new String[]{"country"}, "hiragana", "", ""), 
                new JapaneseWord("くるま", "kuruma", new String[]{"car"}, "hiragana", "", ""), 
                new JapaneseWord("しょくどう", "shokudou", new String[]{"cafeteria", "dining commons"}, "hiragana", "", ""), 
                new JapaneseWord("ちち", "chichi", new String[]{"father"}, "hiragana", "", ""), 
                new JapaneseWord("はは", "haha", new String[]{"mother"}, "hiragana", "", ""), 
                new JapaneseWord("め", "me", new String[]{"eye"}, "hiragana", "", ""), 
                new JapaneseWord("めがね", "megane", new String[]{"glasses"}, "hiragana", "", ""), 
                new JapaneseWord("あたまがいい", "atamagaii", new String[]{"smart", "bright", "clever"}, "hiragana", "i", ""), 
                new JapaneseWord("かわいい", "kawaii", new String[]{"cute"}, "hiragana", "i", ""), 
                new JapaneseWord("せがたかい", "segatakai", new String[]{"tall"}, "hiragana", "i", ""), 
                new JapaneseWord("せがひくい", "segahikui", new String[]{"short"}, "hiragana", "i", ""), 
                new JapaneseWord("ながい", "nagai", new String[]{"long"}, "hiragana", "i", ""), 
                new JapaneseWord("はやい", "hayai", new String[]{"fast"}, "hiragana", "i", ""), 
                new JapaneseWord("みじかい", "mijikai", new String[]{"short"}, "hiragana", "i", ""), 
                new JapaneseWord("しんせつ", "shinsetsu", new String[]{"kind"}, "hiragana", "na", ""), 
                new JapaneseWord("べんり", "benri", new String[]{"convenient"}, "hiragana", "na", ""), 
                new JapaneseWord("うたう", "utau", new String[]{"to sing"}, "hiragana", "", ""), 
                new JapaneseWord("かぶる", "kaburu", new String[]{"to put on (a hat)"}, "hiragana", "", ""), 
                new JapaneseWord("しる", "shiru", new String[]{"to know", "to get to know"}, "hiragana", "", ""), 
                new JapaneseWord("すむ", "sumu", new String[]{"to live"}, "hiragana", "", ""), 
                new JapaneseWord("はく", "haku", new String[]{"to put on (items below your waist)"}, "hiragana", "", ""), 
                new JapaneseWord("ふとる", "futoru", new String[]{"to gain weight"}, "hiragana", "", ""), 
                new JapaneseWord("めがねをかける", "meganewokakeru", new String[]{"to put on glasses"}, "hiragana", "", ""), 
                new JapaneseWord("きる", "kiru", new String[]{"to wear", "to put on (clothes above your waist)"}, "hiragana", "", ""), 
                new JapaneseWord("つとめる", "tsutomeru", new String[]{"to work for"}, "hiragana", "", ""), 
                new JapaneseWord("やせる", "yaseru", new String[]{"to lose weight"}, "hiragana", "", ""), 
                new JapaneseWord("けっこんする", "kekkonsuru", new String[]{"to get married"}, "hiragana", "", ""), 
                new JapaneseWord("アパート", "apaato", new String[]{"apartment"}, "katakana", "", ""), 
                new JapaneseWord("ゲーム", "geemu", new String[]{"game"}, "katakana", "", ""), 
                new JapaneseWord("コンビニ", "konbini", new String[]{"convenience store"}, "katakana", "", ""), 
                new JapaneseWord("サークル", "saakuru", new String[]{"club activity"}, "katakana", "", "")
            };
            
            var chapter8 = new JapaneseWord[]
            {
                new JapaneseWord("あさって", "asatte", new String[]{"the day after tomorrow"}, "hiragana", "", ""), 
                new JapaneseWord("あめ", "ame", new String[]{"rain"}, "hiragana", "", ""), 
                new JapaneseWord("かいしゃいん", "kaishain", new String[]{"office worker"}, "hiragana", "", ""), 
                new JapaneseWord("くうき", "kuuki", new String[]{"air"}, "hiragana", "", ""), 
                new JapaneseWord("けさ", "kesa", new String[]{"this morning"}, "hiragana", "", ""), 
                new JapaneseWord("こくばん", "kokuban", new String[]{"blackboard"}, "hiragana", "", ""), 
                new JapaneseWord("こんげつ", "kongetsu", new String[]{"this month"}, "hiragana", "", ""), 
                new JapaneseWord("しごと", "shigoto", new String[]{"job", "work", "occupation"}, "hiragana", "", ""), 
                new JapaneseWord("だいがくせい", "daigakusei", new String[]{"college student"}, "hiragana", "", ""), 
                new JapaneseWord("てんきよほう", "tenkiyohou", new String[]{"weather forecast"}, "hiragana", "", ""), 
                new JapaneseWord("ところ", "tokoro", new String[]{"place"}, "hiragana", "", ""), 
                new JapaneseWord("なつ", "natsu", new String[]{"summer"}, "hiragana", "", ""), 
                new JapaneseWord("なにか", "nanika", new String[]{"something"}, "hiragana", "", ""), 
                new JapaneseWord("はし", "hashi", new String[]{"chopsticks"}, "hiragana", "", ""), 
                new JapaneseWord("ふゆ", "fuyu", new String[]{"winter"}, "hiragana", "", ""), 
                new JapaneseWord("まいしゅう", "maishuu", new String[]{"every week"}, "hiragana", "", ""), 
                new JapaneseWord("らいげつ", "raigetsu", new String[]{"next month"}, "hiragana", "", ""), 
                new JapaneseWord("じょうず", "jouzu", new String[]{"good at...", "skillful"}, "hiragana", "na", ""), 
                new JapaneseWord("へた", "heta", new String[]{"poor at...", "clumsy"}, "hiragana", "na", ""), 
                new JapaneseWord("ゆうめい", "yuumei", new String[]{"famous"}, "hiragana", "na", ""), 
                new JapaneseWord("あめがふる", "amegafuru", new String[]{"it rains"}, "hiragana", "", ""), 
                new JapaneseWord("あらう", "arau", new String[]{"to wash"}, "hiragana", "", ""), 
                new JapaneseWord("いう", "iu", new String[]{"to say"}, "hiragana", "", ""), 
                new JapaneseWord("いる", "iru", new String[]{"to need"}, "hiragana", "", ""), 
                new JapaneseWord("おそくなる", "osokunaru", new String[]{"to be late"}, "hiragana", "", ""), 
                new JapaneseWord("おもう", "omou", new String[]{"to think"}, "hiragana", "", ""), 
                new JapaneseWord("きる", "kiru", new String[]{"to cut"}, "hiragana", "", ""), 
                new JapaneseWord("つくる", "tsukuru", new String[]{"to make"}, "hiragana", "", ""), 
                new JapaneseWord("もっていく", "motteiku", new String[]{"to take"}, "hiragana", "", ""), 
                new JapaneseWord("じろじろみる", "jirojiromiru", new String[]{"to stare (at...)"}, "hiragana", "", ""), 
                new JapaneseWord("すてる", "suteru", new String[]{"to throw away"}, "hiragana", "", ""), 
                new JapaneseWord("はじめる", "hajimeru", new String[]{"to begin"}, "hiragana", "", ""), 
                new JapaneseWord("うんてんする", "untensuru", new String[]{"to drive"}, "hiragana", "", ""), 
                new JapaneseWord("せんたくする", "sentakusuru", new String[]{"to do laundry"}, "hiragana", "", ""), 
                new JapaneseWord("そうじする", "soujisuru", new String[]{"to clean"}, "hiragana", "", ""), 
                new JapaneseWord("でんわする", "denwasuru", new String[]{"to call"}, "hiragana", "", ""), 
                new JapaneseWord("りょうりする", "ryourisuru", new String[]{"to cook"}, "hiragana", "", ""), 
                new JapaneseWord("カメラ", "kamera", new String[]{"camera"}, "katakana", "", ""), 
                new JapaneseWord("カラオケ", "karaoke", new String[]{"karaoke"}, "katakana", "", ""), 
                new JapaneseWord("トマト", "tomato", new String[]{"tomato"}, "katakana", "", ""), 
                new JapaneseWord("パーチー", "paatii", new String[]{"party"}, "katakana", "", ""), 
                new JapaneseWord("バーベキュー", "baabekyuu", new String[]{"barbecue"}, "katakana", "", ""), 
                new JapaneseWord("ホームステイ", "hoomusutei", new String[]{"homestay", "living with a local family"}, "katakana", "", "")
            };
            
            var chapter9 = new JapaneseWord[]
            {
                new JapaneseWord("いいこ", "iiko", new String[]{"good child"}, "hiragana", "", ""), 
                new JapaneseWord("いろ", "iro", new String[]{"color"}, "hiragana", "", ""), 
                new JapaneseWord("おべんとう", "obentou", new String[]{"boxed lunch"}, "hiragana", "", ""), 
                new JapaneseWord("かぶき", "kabuki", new String[]{"Kabuki", "traditional Japanese theatrical art"}, "hiragana", "", ""), 
                new JapaneseWord("きょねん", "kyonen", new String[]{"last year"}, "hiragana", "", ""), 
                new JapaneseWord("くすり", "kusuri", new String[]{"medicine"}, "hiragana", "", ""), 
                new JapaneseWord("こんど", "kondo", new String[]{"near future"}, "hiragana", "", ""), 
                new JapaneseWord("さくぶん", "sakubun", new String[]{"essay", "composition"}, "hiragana", "", ""), 
                new JapaneseWord("しけん", "shiken", new String[]{"exam"}, "hiragana", "", ""), 
                new JapaneseWord("せんげつ", "sengetsu", new String[]{"last month"}, "hiragana", "", ""), 
                new JapaneseWord("たんご", "tango", new String[]{"vocabulary", "word"}, "hiragana", "", ""), 
                new JapaneseWord("びょうき", "byouki", new String[]{"sickness", "illness"}, "hiragana", "", ""), 
                new JapaneseWord("あおい", "aoi", new String[]{"blue"}, "hiragana", "i", ""), 
                new JapaneseWord("あかい", "akai", new String[]{"red"}, "hiragana", "i", ""), 
                new JapaneseWord("くろい", "kuroi", new String[]{"black"}, "hiragana", "i", ""), 
                new JapaneseWord("しろい", "shiroi", new String[]{"white"}, "hiragana", "i", ""), 
                new JapaneseWord("わかい", "wakai", new String[]{"young"}, "hiragana", "i", ""), 
                new JapaneseWord("さびしい", "sabishii", new String[]{"lonely"}, "hiragana", "i", ""), 
                new JapaneseWord("いじわる", "ijiwaru", new String[]{"mean", "mean-spirited"}, "hiragana", "na", ""), 
                new JapaneseWord("おどる", "odoru", new String[]{"to dance"}, "hiragana", "", ""), 
                new JapaneseWord("おわる", "owaru", new String[]{"something ends"}, "hiragana", "", ""), 
                new JapaneseWord("にんきがある", "ninkigaaru", new String[]{"to be popular"}, "hiragana", "", ""), 
                new JapaneseWord("はじめる", "hajimaru", new String[]{"something begins"}, "hiragana", "", ""), 
                new JapaneseWord("ひく", "hiku", new String[]{"to play (a string instrument or piano)"}, "hiragana", "", ""), 
                new JapaneseWord("もらう", "morau", new String[]{"to receive", "to get (from somebody)"}, "hiragana", "", ""), 
                new JapaneseWord("おぼえる", "oboeru", new String[]{"to memorize"}, "hiragana", "", ""), 
                new JapaneseWord("でる", "deru", new String[]{"to appear", "to exit", "to attend"}, "hiragana", "", ""), 
                new JapaneseWord("うんどうする", "undousuru", new String[]{"to exercise"}, "hiragana", "", ""), 
                new JapaneseWord("さんぽする", "sanposuru", new String[]{"to take a walk"}, "hiragana", "", ""), 
                new JapaneseWord("ギター", "gitaa", new String[]{"guitar"}, "katakana", "", ""), 
                new JapaneseWord("コンサート", "konsaato", new String[]{"concert"}, "katakana", "", ""), 
                new JapaneseWord("スキー", "sukii", new String[]{"ski"}, "katakana", "", ""), 
                new JapaneseWord("ピアノ", "piano", new String[]{"piano"}, "katakana", "", ""), 
                new JapaneseWord("ピザ", "piza", new String[]{"pizza"}, "katakana", "", "")
            };
            
            var chapter10 = new JapaneseWord[]
            {
                new JapaneseWord("あき", "aki", new String[]{"fall"}, "hiragana", "", ""), 
                new JapaneseWord("えき", "eki", new String[]{"station"}, "hiragana", "", ""), 
                new JapaneseWord("おかねもち", "okanemochi", new String[]{"rich person"}, "hiragana", "", ""), 
                new JapaneseWord("かお", "kao", new String[]{"face"}, "hiragana", "", ""), 
                new JapaneseWord("きせつ", "kisetsu", new String[]{"season"}, "hiragana", "", ""), 
                new JapaneseWord("ぎゅうにゅう", "gyuunyuu", new String[]{"milk"}, "hiragana", "", ""), 
                new JapaneseWord("ことし", "kotoshi", new String[]{"this year"}, "hiragana", "", ""), 
                new JapaneseWord("しんかんせん", "shinkansen", new String[]{"bullet train", "Shinkansen"}, "hiragana", "", ""), 
                new JapaneseWord("すし", "sushi", new String[]{"sushi"}, "hiragana", "", ""), 
                new JapaneseWord("せいかつ", "seikatsu", new String[]{"life", "living"}, "hiragana", "", ""), 
                new JapaneseWord("せかい", "sekai", new String[]{"world"}, "hiragana", "", ""), 
                new JapaneseWord("ちかてつ", "chikatetsu", new String[]{"subway"}, "hiragana", "", ""), 
                new JapaneseWord("てぶくろ", "tebukuro", new String[]{"gloves"}, "hiragana", "", ""), 
                new JapaneseWord("てんぷら", "tenpura", new String[]{"tempura"}, "hiragana", "", ""), 
                new JapaneseWord("とこや", "tokoya", new String[]{"barber shop", "barber's"}, "hiragana", "", ""), 
                new JapaneseWord("はる", "haru", new String[]{"spring"}, "hiragana", "", ""), 
                new JapaneseWord("びよういん", "biyouin", new String[]{"beauty parlor"}, "hiragana", "", ""), 
                new JapaneseWord("びん", "bin", new String[]{"flight"}, "hiragana", "", ""), 
                new JapaneseWord("ふね", "fune", new String[]{"ship", "boat"}, "hiragana", "", ""), 
                new JapaneseWord("やきゅう", "yakyuu", new String[]{"baseball"}, "hiragana", "", ""), 
                new JapaneseWord("よやく", "yoyaku", new String[]{"reservation"}, "hiragana", "", ""), 
                new JapaneseWord("らいがっき", "raigakki", new String[]{"next semester"}, "hiragana", "", ""), 
                new JapaneseWord("りんご", "ringo", new String[]{"apple"}, "hiragana", "", ""), 
                new JapaneseWord("あたたかい", "atatakai", new String[]{"warm"}, "hiragana", "i", ""), 
                new JapaneseWord("おそい", "osoi", new String[]{"slow", "late"}, "hiragana", "i", ""), 
                new JapaneseWord("すずしい", "suzushii", new String[]{"cool (weather)"}, "hiragana", "i", ""), 
                new JapaneseWord("つめたい", "tsumetai", new String[]{"cold (things)", "cold personality"}, "hiragana", "i", ""), 
                new JapaneseWord("ねむい", "nemui", new String[]{"sleepy"}, "hiragana", "i", ""), 
                new JapaneseWord("かんたん", "kantan", new String[]{"simple", "easy"}, "hiragana", "na", ""), 
                new JapaneseWord("かかる", "kakaru", new String[]{"to take (time)", "to take (money)"}, "hiragana", "", ""), 
                new JapaneseWord("とまる", "tomaru", new String[]{"to stay"}, "hiragana", "", ""), 
                new JapaneseWord("なる", "naru", new String[]{"to become"}, "hiragana", "", ""), 
                new JapaneseWord("はらう", "harau", new String[]{"to pay"}, "hiragana", "", ""), 
                new JapaneseWord("きめる", "kimeru", new String[]{"to decide"}, "hiragana", "", ""), 
                new JapaneseWord("りょこうする", "ryokousuru", new String[]{"to travel"}, "hiragana", "", ""), 
                new JapaneseWord("れんしゅうする", "renshuusuru", new String[]{"to practice"}, "hiragana", "", ""), 
                new JapaneseWord("クレジットカード", "kurejittokaado", new String[]{"credit card"}, "katakana", "", ""), 
                new JapaneseWord("ケーキ", "keeki", new String[]{"cake"}, "katakana", "", ""), 
                new JapaneseWord("サッカー", "sakkaa", new String[]{"soccer"}, "katakana", "", ""), 
                new JapaneseWord("パンツ", "pantsu", new String[]{"pants"}, "katakana", "", "")
            };
            
            var chapter11 = new JapaneseWord[]
            {
                new JapaneseWord("おかし", "okashi", new String[]{"sweets", "snacks"}, "hiragana", "", ""),
                new JapaneseWord("おしょうがつ", "oshougatsu", new String[]{"New Year's"}, "hiragana", "", ""), 
                new JapaneseWord("おとこのこ", "otokonoko", new String[]{"boy"}, "hiragana", "", ""), 
                new JapaneseWord("おまつり", "omatsuri", new String[]{"festival"}, "hiragana", "", ""), 
                new JapaneseWord("おもちゃ", "omocha", new String[]{"toy"}, "hiragana", "", ""), 
                new JapaneseWord("おんせん", "onsen", new String[]{"hot spring", "spa"}, "hiragana", "", ""), 
                new JapaneseWord("おんなのこ", "onnanoko", new String[]{"girl"}, "hiragana", "", ""), 
                new JapaneseWord("がいこく", "gaikoku", new String[]{"foreign country"}, "hiragana", "", ""), 
                new JapaneseWord("かしゅ", "kashu", new String[]{"singer"}, "hiragana", "", ""), 
                new JapaneseWord("かわ", "kawa", new String[]{"river"}, "hiragana", "", ""), 
                new JapaneseWord("こちら", "kochira", new String[]{"this person (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("こんがっき", "kongakki", new String[]{"this semester"}, "hiragana", "", ""), 
                new JapaneseWord("しゃちょう", "shachou", new String[]{"president of a company"}, "hiragana", "", ""), 
                new JapaneseWord("じゅぎょう", "jugyou", new String[]{"class"}, "hiragana", "", ""), 
                new JapaneseWord("しょうらい", "shourai", new String[]{"future"}, "hiragana", "", ""), 
                new JapaneseWord("じんじゃ", "jinja", new String[]{"shrine"}, "hiragana", "", ""), 
                new JapaneseWord("つり", "tsuri", new String[]{"fishing"}, "hiragana", "", ""), 
                new JapaneseWord("びじゅつかん", "bijutsukan", new String[]{"art museum"}, "hiragana", "", ""), 
                new JapaneseWord("みずうみ", "mizuumi", new String[]{"lake"}, "hiragana", "", ""), 
                new JapaneseWord("っやま", "yama", new String[]{"mountain"}, "hiragana", "", ""), 
                new JapaneseWord("ゆめ", "yume", new String[]{"dream"}, "hiragana", "", ""), 
                new JapaneseWord("うそをつく", "usowotsuku", new String[]{"to lie", "to tell a lie"}, "hiragana", "", ""), 
                new JapaneseWord("おなかがすく", "onakagasuku", new String[]{"to become hungry"}, "hiragana", "", ""), 
                new JapaneseWord("かう", "kau", new String[]{"to own (a pet)"}, "hiragana", "", ""), 
                new JapaneseWord("ならう", "narau", new String[]{"to learn"}, "hiragana", "", ""), 
                new JapaneseWord("のぼる", "noboru", new String[]{"to climb"}, "hiragana", "", ""), 
                new JapaneseWord("はたらく", "hataraku", new String[]{"to work"}, "hiragana", "", ""), 
                new JapaneseWord("つかれる", "tsukareru", new String[]{"to get tired"}, "hiragana", "", ""), 
                new JapaneseWord("やめる", "yameru", new String[]{"to quit"}, "hiragana", "", ""), 
                new JapaneseWord("けんかする", "kenkasuru", new String[]{"to have a fight", "to quarrel"}, "hiragana", "", ""), 
                new JapaneseWord("しょうかいする", "shoukaisuru", new String[]{"to introduce"}, "hiragana", "", ""), 
                new JapaneseWord("ちこくする", "chikokusuru", new String[]{"to be late (for an appointment)"}, "hiragana", "", ""), 
                new JapaneseWord("りゅうがくする", "ryuugakusuru", new String[]{"to study abroad"}, "hiragana", "", ""), 
                new JapaneseWord("キャンプ", "kyanpu", new String[]{"camp"}, "katakana", "", ""), 
                new JapaneseWord("ドライブ", "doraibu", new String[]{"drive"}, "katakana", "", ""), 
                new JapaneseWord("ビール", "biiru", new String[]{"beer"}, "katakana", "", ""), 
                new JapaneseWord("ホストファミリー", "hosutofamirii", new String[]{"host family"}, "katakana", "", ""), 
                new JapaneseWord("ルームメート", "ruumumeeto", new String[]{"roommate"}, "katakana", "", ""), 
                new JapaneseWord("サボル", "saboru", new String[]{"to cut class", "to skip"}, "katakana", "", "")
            };
            
            var chapter12 = new JapaneseWord[]
            {
                new JapaneseWord("あし", "ashi", new String[]{"leg", "foot"}, "hiragana", "", ""), 
                new JapaneseWord("いみ", "imi", new String[]{"meaning"}, "hiragana", "", ""), 
                new JapaneseWord("おてあらい", "otearai", new String[]{"restroom"}, "hiragana", "", ""), 
                new JapaneseWord("おなか", "onaka", new String[]{"stomach"}, "hiragana", "", ""), 
                new JapaneseWord("かぜ", "kaze", new String[]{"cold"}, "hiragana", "", ""), 
                new JapaneseWord("かのじょ", "kanojo", new String[]{"girlfriend", "she"}, "hiragana", "", ""), 
                new JapaneseWord("かれ", "kare", new String[]{"boyfriend", "he"}, "hiragana", "", ""), 
                new JapaneseWord("きおん", "kion", new String[]{"temperature (of the weather)"}, "hiragana", "", ""), 
                new JapaneseWord("くもり", "kumori", new String[]{"cloudy weather"}, "hiragana", "", ""), 
                new JapaneseWord("しあい", "shiai", new String[]{"match", "game"}, "hiragana", "", ""), 
                new JapaneseWord("せいじ", "seiji", new String[]{"politics"}, "hiragana", "", ""), 
                new JapaneseWord("せいせき", "seiseki", new String[]{"grade"}, "hiragana", "", ""), 
                new JapaneseWord("せき", "seki", new String[]{"cough"}, "hiragana", "", ""), 
                new JapaneseWord("のど", "nodo", new String[]{"throat"}, "hiragana", "", ""), 
                new JapaneseWord("は", "ha", new String[]{"teeth"}, "hiragana", "", ""), 
                new JapaneseWord("はな", "hana", new String[]{"flower"}, "hiragana", "", ""), 
                new JapaneseWord("はれ", "hare", new String[]{"sunny weather"}, "hiragana", "", ""), 
                new JapaneseWord("ふく", "fuku", new String[]{"clothes"}, "hiragana", "", ""), 
                new JapaneseWord("ふつかよい", "futsukayoi", new String[]{"hangover"}, "hiragana", "", ""), 
                new JapaneseWord("もの", "mono", new String[]{"thing (concrete object)"}, "hiragana", "", ""), 
                new JapaneseWord("ゆき", "yuki", new String[]{"snow"}, "hiragana", "", ""), 
                new JapaneseWord("ようじ", "youji", new String[]{"business to take care of"}, "hiragana", "", ""), 
                new JapaneseWord("あまい", "amai", new String[]{"sweet"}, "hiragana", "i", ""), 
                new JapaneseWord("いたい", "itai", new String[]{"hurt", "painful"}, "hiragana", "i", ""), 
                new JapaneseWord("おおい", "ooi", new String[]{"many"}, "hiragana", "i", ""), 
                new JapaneseWord("せまい", "semai", new String[]{"narrow", "not spacious"}, "hiragana", "i", ""), 
                new JapaneseWord("つごうがわるい", "tsugougawarui", new String[]{ "inconvenient", "to have a scheduling conflict"}, "hiragana", "i", ""), 
                new JapaneseWord("わるい", "warui", new String[]{"bad"}, "hiragana", "i", ""), 
                new JapaneseWord("すてき", "suteki", new String[]{"nice"}, "hiragana", "na", ""), 
                new JapaneseWord("あるく", "aruku", new String[]{"to walk"}, "hiragana", "", ""), 
                new JapaneseWord("かぜをひく", "kazewohiku", new String[]{"to catch a cold"}, "hiragana", "", ""), 
                new JapaneseWord("きょうみがある", "kyoumigaaru", new String[]{"to be interested in"}, "hiragana", "", ""), 
                new JapaneseWord("なくす", "nakusu", new String[]{"to lose (something)"}, "hiragana", "", ""), 
                new JapaneseWord("ねつがある", "netsugaaru", new String[]{"to have a fever"}, "hiragana", "", ""), 
                new JapaneseWord("のどがかわく", "nodogakawaku", new String[]{"to become thirsty"}, "hiragana", "", ""), 
                new JapaneseWord("せきがでる", "sekigaderu", new String[]{"to cough"}, "hiragana", "", ""), 
                new JapaneseWord("わかれる", "wakareru", new String[]{"to break up", "to separate"}, "hiragana", "", ""), 
                new JapaneseWord("きんちょうする", "kinchousuru", new String[]{"to get nervous"}, "hiragana", "", ""), 
                new JapaneseWord("しんぱいする", "shinpaisuru", new String[]{"to worry"}, "hiragana", "", ""), 
                new JapaneseWord("ジュース", "juusu", new String[]{"juice"}, "katakana", "", ""), 
                new JapaneseWord("プレゼント", "purezento", new String[]{"present"}, "katakana", "", ""), 
                new JapaneseWord("ホームシック", "hoomushikku", new String[]{"homesick"}, "katakana", "", ""), 
                new JapaneseWord("マイナス", "mainasu", new String[]{"minus"}, "katakana", "", "")
            };
            
            var chapter13 = new JapaneseWord[]
            {
                new JapaneseWord("おたく", "otaku", new String[]{"(someone's) home"}, "hiragana", "", ""), 
                new JapaneseWord("おとな", "otona", new String[]{"adult"}, "hiragana", "", ""), 
                new JapaneseWord("がいこくご", "gaikokugo", new String[]{"foreign language"}, "hiragana", "", ""), 
                new JapaneseWord("がっき", "gakki", new String[]{"musical instrument"}, "hiragana", "", ""), 
                new JapaneseWord("からて", "karate", new String[]{"karate"}, "hiragana", "", ""), 
                new JapaneseWord("きもの", "kimono", new String[]{"kimono"}, "hiragana", "", ""), 
                new JapaneseWord("こうこく", "koukoku", new String[]{"advertisement"}, "hiragana", "", ""), 
                new JapaneseWord("ことば", "kotoba", new String[]{"language"}, "hiragana", "", ""), 
                new JapaneseWord("ぞう", "zou", new String[]{"elephant"}, "hiragana", "", ""), 
                new JapaneseWord("ぶっか", "bukka", new String[]{"(consumer) prices"}, "hiragana", "", ""), 
                new JapaneseWord("ぶんぽう", "bunpou", new String[]{"grammar"}, "hiragana", "", ""), 
                new JapaneseWord("ぼしゅう", "boshuu", new String[]{"recruitment"}, "hiragana", "", ""), 
                new JapaneseWord("みせ", "mise", new String[]{"shop", "store"}, "hiragana", "", ""), 
                new JapaneseWord("やくざ", "yakuza", new String[]{"yakuza", "gangster"}, "hiragana", "", ""), 
                new JapaneseWord("やくぞく", "yakusoku", new String[]{"to keep a promise"}, "hiragana", "", ""), 
                new JapaneseWord("わたくし", "watakushi", new String[]{"I (formal)"}, "hiragana", "", ""), 
                new JapaneseWord("うれしい", "ureshii", new String[]{"glad"}, "hiragana", "i", ""), 
                new JapaneseWord("かなしい", "kanashii", new String[]{"sad"}, "hiragana", "i", ""), 
                new JapaneseWord("からい", "karai", new String[]{"hot and spicy", "salty"}, "hiragana", "i", ""), 
                new JapaneseWord("すごい", "sugoi", new String[]{"awesome", "incredible"}, "hiragana", "i", ""), 
                new JapaneseWord("ちかい", "chikai", new String[]{"close", "near"}, "hiragana", "i", ""), 
                new JapaneseWord("いろいろ", "iroiro", new String[]{"various", "different kinds of"}, "hiragana", "na", ""), 
                new JapaneseWord("しあわせ", "shiawase", new String[]{"happy (lasting happiness)"}, "hiragana", "na", ""), 
                new JapaneseWord("だめ", "dame", new String[]{"no good"}, "hiragana", "na", ""), 
                new JapaneseWord("あむ", "amu", new String[]{"to knit"}, "hiragana", "", ""), 
                new JapaneseWord("かす", "kasu", new String[]{"to lend", "to rent"}, "hiragana", "", ""), 
                new JapaneseWord("がんばる", "ganbaru", new String[]{"to do one's best", "to try hard"}, "hiragana", "", ""), 
                new JapaneseWord("なく", "naku", new String[]{"to cry"}, "hiragana", "", ""), 
                new JapaneseWord("みがく", "migaku", new String[]{"to brush teeth", "to polish"}, "hiragana", "", ""), 
                new JapaneseWord("やくそくをまもる", "yakusokuwomamoru", new String[]{"to keep a promise"}, "hiragana", "", ""), 
                new JapaneseWord("かんどうする", "kandousuru", new String[]{"to be moved", "to be touched"}, "hiragana", "", ""), 
                new JapaneseWord("ウエイター", "ueitaa", new String[]{"waiter"}, "katakana", "", ""), 
                new JapaneseWord("カレー", "karee", new String[]{"curry"}, "katakana", "", ""), 
                new JapaneseWord("ゴルフ", "gorufu", new String[]{"golf"}, "katakana", "", ""), 
                new JapaneseWord("バイオリン", "baiorin", new String[]{"violin"}, "katakana", "", ""), 
                new JapaneseWord("バイク", "baiku", new String[]{"motorcycle"}, "katakana", "", ""), 
                new JapaneseWord("レポート", "repooto", new String[]{"(term) paper"}, "katakana", "", "")
            };
            
            var chapter14 = new JapaneseWord[]
            {
                new JapaneseWord("あに", "ani", new String[]{"older brother"}, "hiragana", "", ""), 
                new JapaneseWord("おおやさん", "ooyasan", new String[]{"landlord", "landlady"}, "hiragana", "", ""), 
                new JapaneseWord("おかえし", "okaeshi", new String[]{"return (as a token of gratitude)"}, "hiragana", "", ""), 
                new JapaneseWord("おくさん", "okusan", new String[]{"(your/his) wife"}, "hiragana", "", ""), 
                new JapaneseWord("おじさん", "ojisan", new String[]{"uncle", "middle-aged man"}, "hiragana", "", ""), 
                new JapaneseWord("おばさん", "obasan", new String[]{"aunt", "middle-aged woman"}, "hiragana", "", ""), 
                new JapaneseWord("ごしゅじん", "goshujin", new String[]{"(your/her) husband"}, "hiragana", "", ""), 
                new JapaneseWord("さら", "sara", new String[]{"plate", "dish"}, "hiragana", "", ""), 
                new JapaneseWord("じかん", "jikan", new String[]{"time"}, "hiragana", "", ""), 
                new JapaneseWord("ぬいぐるみ", "nuigurumi", new String[]{"stuffed animal"}, "hiragana", "", ""), 
                new JapaneseWord("ふうふ", "fuufu", new String[]{"married couple", "husband and wife"}, "hiragana", "", ""), 
                new JapaneseWord("まんが", "manga", new String[]{"comic book"}, "hiragana", "", ""), 
                new JapaneseWord("みかん", "mikan", new String[]{"mandarin", "orange"}, "hiragana", "", ""), 
                new JapaneseWord("みなさん", "minasan", new String[]{"everyone", "all of you"}, "hiragana", "", ""), 
                new JapaneseWord("ゆびわ", "yubiwa", new String[]{"ring"}, "hiragana", "", ""), 
                new JapaneseWord("りょうしん", "ryoushin", new String[]{"parents"}, "hiragana", "", ""), 
                new JapaneseWord("りれきしょ", "rirekisho", new String[]{"resume"}, "hiragana", "", ""), 
                new JapaneseWord("ほしい", "hoshii", new String[]{"to want"}, "hiragana", "i", ""), 
                new JapaneseWord("けち", "kechi", new String[]{"stingy", "cheap"}, "hiragana", "na", ""), 
                new JapaneseWord("おくる", "okuru", new String[]{"to send"}, "hiragana", "", ""), 
                new JapaneseWord("にあう", "niau", new String[]{"to look good (on somebody)"}, "hiragana", "", ""), 
                new JapaneseWord("あきらめる", "akirameru", new String[]{"to give up"}, "hiragana", "", ""), 
                new JapaneseWord("あげる", "ageru", new String[]{"to give (to others)"}, "hiragana", "", ""), 
                new JapaneseWord("くれる", "kureru", new String[]{"to give (me)"}, "hiragana", "", ""), 
                new JapaneseWord("できる", "dekiru", new String[]{"to come into existence", "to be made"}, "hiragana", "", ""), 
                new JapaneseWord("そうだんする", "soudansuru", new String[]{"to consult"}, "hiragana", "", ""), 
                new JapaneseWord("グラス", "gurasu", new String[]{"tumbler", "glass"}, "katakana", "", ""), 
                new JapaneseWord("クリスマス", "kurisumasu", new String[]{"Christmas"}, "katakana", "", ""), 
                new JapaneseWord("チケット", "chiketto", new String[]{"ticket"}, "katakana", "", ""), 
                new JapaneseWord("チョコレート", "chokoreeto", new String[]{"chocolate"}, "katakana", "", ""), 
                new JapaneseWord("トレーナー", "toreenaa", new String[]{"sweat shirt"}, "katakana", "", ""), 
                new JapaneseWord("ネクタイ", "nekutai", new String[]{"necktie"}, "katakana", "", ""), 
                new JapaneseWord("バレンタインデー", "barentaindee", new String[]{"st. Valentine's Day"}, "katakana", "", ""), 
                new JapaneseWord("ビデオカメラ", "bideokamera", new String[]{"camcorder"}, "katakana", "", ""), 
                new JapaneseWord("ホワイトデー", "howaitodee", new String[]{"White Day"}, "katakana", "", ""), 
                new JapaneseWord("マフラー", "mafuraa", new String[]{"winter scarf"}, "katakana", "", ""), 
                new JapaneseWord("マンション", "manshon", new String[]{"multistory apartment building", "condominium"}, "katakana", "", ""), 
                new JapaneseWord("ラジオ", "rajio", new String[]{"radio"}, "katakana", "", "")
            };
            
            var chapter15 = new JapaneseWord[]
            {
                new JapaneseWord("え", "e", new String[]{"painting", "picture", "drawing"}, "hiragana", "", ""), 
                new JapaneseWord("えいがかん", "eigakan", new String[]{"movie theater"}, "hiragana", "", ""), 
                new JapaneseWord("がいこくじん", "gaikokujin", new String[]{"foreigner"}, "hiragana", "", ""), 
                new JapaneseWord("かぐ", "kagu", new String[]{"furniture"}, "hiragana", "", ""), 
                new JapaneseWord("けいけん", "keiken", new String[]{"experience"}, "hiragana", "", ""), 
                new JapaneseWord("けっこんしき", "kekkonshiki", new String[]{"wedding"}, "hiragana", "", ""), 
                new JapaneseWord("じしん", "jishin", new String[]{"earthquake"}, "hiragana", "", ""), 
                new JapaneseWord("しめきり", "shimekiri", new String[]{"deadline"}, "hiragana", "", ""), 
                new JapaneseWord("しゅうかん", "shuukan", new String[]{"custom"}, "hiragana", "", ""), 
                new JapaneseWord("ざいきん", "zeikin", new String[]{"tax"}, "hiragana", "", ""), 
                new JapaneseWord("そつぎょうしき", "sotsugyoushiki", new String[]{"graduation ceremony"}, "hiragana", "", ""), 
                new JapaneseWord("そば", "soba", new String[]{"soba", "Japanese buckwheat noodle"}, "hiragana", "", ""), 
                new JapaneseWord("ちず", "chizu", new String[]{"map"}, "hiragana", "", ""), 
                new JapaneseWord("でんち", "denchi", new String[]{"battery"}, "hiragana", "", ""), 
                new JapaneseWord("にわ", "niwa", new String[]{"garden"}, "hiragana", "", ""), 
                new JapaneseWord("ばんぐみ", "bangumi", new String[]{"broadcast program"}, "hiragana", "", ""), 
                new JapaneseWord("はっぴょう", "happyou", new String[]{"presentation"}, "hiragana", "", ""), 
                new JapaneseWord("ほけん", "hoken", new String[]{"insurance"}, "hiragana", "", ""), 
                new JapaneseWord("よてい", "yotei", new String[]{"yotei"}, "hiragana", "", ""), 
                new JapaneseWord("りょかん", "ryokan", new String[]{"Japanese inn"}, "hiragana", "", ""), 
                new JapaneseWord("わりびきけん", "waribikiken", new String[]{"discount coupon"}, "hiragana", "", ""), 
                new JapaneseWord("ひろい", "hiroi", new String[]{"spacious", "wide"}, "hiragana", "i", ""), 
                new JapaneseWord("うる", "uru", new String[]{"to sell"}, "hiragana", "", ""), 
                new JapaneseWord("おろす", "orosu", new String[]{"to withdraw (money)"}, "hiragana", "", ""), 
                new JapaneseWord("さがす", "sagasu", new String[]{"to look for"}, "hiragana", "", ""), 
                new JapaneseWord("さそう", "sasou", new String[]{"to invite"}, "hiragana", "", ""), 
                new JapaneseWord("しゃべる", "shaberu", new String[]{"to chat"}, "hiragana", "", ""), 
                new JapaneseWord("つきあう", "tsukiau", new String[]{"to date (someone)", "to keep company"}, "hiragana", "", ""), 
                new JapaneseWord("つく", "tsuku", new String[]{"to arrive"}, "hiragana", "", ""), 
                new JapaneseWord("ほけんにはいる", "hokennihairu", new String[]{"to buy insurance"}, "hiragana", "", ""), 
                new JapaneseWord("きをつける", "kiwotsukeru", new String[]{"to be careful", "to be cautious"}, "hiragana", "", ""), 
                new JapaneseWord("しらべる", "shiraberu", new String[]{"to look into (a matter)"}, "hiragana", "", ""), 
                new JapaneseWord("みえる", "mieru", new String[]{"to be visible"}, "hiragana", "", ""), 
                new JapaneseWord("かんこうする", "kankousuru", new String[]{"to do sightseeing"}, "hiragana", "", ""), 
                new JapaneseWord("する", "suru", new String[]{"to decide on (an item)"}, "hiragana", "", ""), 
                new JapaneseWord("そつぎょうする", "sotsugyousuru", new String[]{"to graduate"}, "hiragana", "", ""), 
                new JapaneseWord("よやくする", "yoyakusuru", new String[]{"to reserve"}, "hiragana", "", ""), 
                new JapaneseWord("インターネット", "intaanetto", new String[]{"Internet"}, "katakana", "", ""), 
                new JapaneseWord("クラブ", "kurabu", new String[]{"night club"}, "katakana", "", ""), 
                new JapaneseWord("ジャケット", "jaketto", new String[]{"jacket"}, "katakana", "", ""), 
                new JapaneseWord("プール", "puuru", new String[]{"swimming pool"}, "katakana", "", ""), 
                new JapaneseWord("ペット", "petto", new String[]{"pet"}, "katakana", "", "")
            };
            
            var chapter16 = new JapaneseWord[]
            {
                new JapaneseWord("えきいん", "ekiin", new String[]{"station attendant"}, "hiragana", "", ""), 
                new JapaneseWord("おおきさ", "ookisa", new String[]{"size"}, "hiragana", "", ""), 
                new JapaneseWord("おや", "oya", new String[]{"parent"}, "hiragana", "", ""), 
                new JapaneseWord("きまつしけん", "kimatsushiken", new String[]{"final exam"}, "hiragana", "", ""), 
                new JapaneseWord("けんきゅう", "kenkyuu", new String[]{"research"}, "hiragana", "", ""), 
                new JapaneseWord("ごみ", "gomi", new String[]{"garbage"}, "hiragana", "", ""), 
                new JapaneseWord("さとう", "satou", new String[]{"sugar"}, "hiragana", "", ""), 
                new JapaneseWord("しょうがくきん", "shougakukin", new String[]{"scholarship"}, "hiragana", "", ""), 
                new JapaneseWord("しんせき", "shinseki", new String[]{"relatives"}, "hiragana", "", ""), 
                new JapaneseWord("すいせんじょう", "suisenjou", new String[]{"letter of recommendation"}, "hiragana", "", ""), 
                new JapaneseWord("だいがくいん", "daigakuin", new String[]{"graduate school"}, "hiragana", "", ""), 
                new JapaneseWord("たいふう", "taifuu", new String[]{"typhoon"}, "hiragana", "", ""), 
                new JapaneseWord("ひ", "hi", new String[]{"day"}, "hiragana", "", ""), 
                new JapaneseWord("みち", "michi", new String[]{"road", "way", "directions"}, "hiragana", "", ""), 
                new JapaneseWord("めざましどけい", "mezamashidokei", new String[]{"alarm clock"}, "hiragana", "", ""), 
                new JapaneseWord("きたない", "kitanai", new String[]{"dirty"}, "hiragana", "i", ""), 
                new JapaneseWord("おこす", "okosu", new String[]{"to wake (someone) up"}, "hiragana", "", ""), 
                new JapaneseWord("おごる", "ogoru", new String[]{"to treat (someone) to a meal"}, "hiragana", "", ""), 
                new JapaneseWord("おちこむ", "ochikomu", new String[]{"to get depressed"}, "hiragana", "", ""), 
                new JapaneseWord("こまる", "komaru", new String[]{"to have difficulty"}, "hiragana", "", ""), 
                new JapaneseWord("だす", "dasu", new String[]{"to hand in (something)", "to take (something) out"}, "hiragana", "", ""), 
                new JapaneseWord("つれていく", "tsureteiku", new String[]{"to take (someone) to (a place)"}, "hiragana", "", ""), 
                new JapaneseWord("なおす", "naosu", new String[]{"to correct", "to fix"}, "hiragana", "", ""), 
                new JapaneseWord("みちにまよう", "michinimayou", new String[]{"to become lost", "to lose one's way"}, "hiragana", "", ""), 
                new JapaneseWord("みつかる", "mitsukaru", new String[]{"to be found"}, "hiragana", "", ""), 
                new JapaneseWord("むかえにいく", "mukaeniiku", new String[]{"to go to pick up"}, "hiragana", "", ""), 
                new JapaneseWord("やくす", "yakusu", new String[]{"to translate"}, "hiragana", "", ""), 
                new JapaneseWord("わらう", "warau", new String[]{"to laugh"}, "hiragana", "", ""), 
                new JapaneseWord("アイロンをかける", "aironwokakeru", new String[]{"to iron (clothes)"}, "hiragana", "", ""), 
                new JapaneseWord("あつめる", "atsumeru", new String[]{"to collect"}, "hiragana", "", ""), 
                new JapaneseWord("いれる", "ireru", new String[]{"to put (something) in"}, "hiragana", "", ""), 
                new JapaneseWord("のりおくれる", "noriokureru", new String[]{"to miss (a train, bus, etc.)"}, "hiragana", "", ""), 
                new JapaneseWord("みせる", "miseru", new String[]{"to show"}, "hiragana", "", ""), 
                new JapaneseWord("あさねぼうする", "asanebousuru", new String[]{"to oversleep"}, "hiragana", "", ""), 
                new JapaneseWord("あんないする", "annaisuru", new String[]{"to show (someone) around"}, "hiragana", "", ""), 
                new JapaneseWord("せつめいする", "setsumeisuru", new String[]{"to explain"}, "hiragana", "", ""), 
                new JapaneseWord("むかえにいく", "mukaenikuru", new String[]{"to come to pick up"}, "hiragana", "", ""), 
                new JapaneseWord("ファイル", "fairu", new String[]{"file", "portfolio"}, "katakana", "", "")
            };
            
            var chapter17 = new JapaneseWord[]
            {
                new JapaneseWord("おきゃくさん", "okyakusan", new String[]{"guest", "visitor", "client", "customer"}, "hiragana", "", ""), 
                new JapaneseWord("おとこ", "otoko", new String[]{"man"}, "hiragana", "", ""), 
                new JapaneseWord("おゆ", "oyu", new String[]{"hot water"}, "hiragana", "", ""), 
                new JapaneseWord("おんな", "onna", new String[]{"woman"}, "hiragana", "", ""), 
                new JapaneseWord("かぎ", "kagi", new String[]{"lock", "key"}, "hiragana", "", ""), 
                new JapaneseWord("かじ", "kaji", new String[]{"fire"}, "hiragana", "", ""), 
                new JapaneseWord("かみ", "kami", new String[]{"paper"}, "hiragana", "", ""), 
                new JapaneseWord("きゅうりょう", "kyuuryou", new String[]{"salary"}, "hiragana", "", ""), 
                new JapaneseWord("さいてい", "saitei", new String[]{"the lowest", "the worst"}, "hiragana", "", ""), 
                new JapaneseWord("ざんぎょう", "zangyou", new String[]{"overtime work"}, "hiragana", "", ""), 
                new JapaneseWord("しゅしょう", "shushou", new String[]{"prime minister"}, "hiragana", "", ""), 
                new JapaneseWord("たからくじ", "takarakuji", new String[]{"lottery"}, "hiragana", "", ""), 
                new JapaneseWord("ちがい", "chigai", new String[]{"difference"}, "hiragana", "", ""), 
                new JapaneseWord("どうぶつえん", "doubutsuen", new String[]{"zoo"}, "hiragana", "", ""), 
                new JapaneseWord("ひげ", "hige", new String[]{"beard"}, "hiragana", "", ""), 
                new JapaneseWord("ひみつ", "himitsu", new String[]{"secret"}, "hiragana", "", ""), 
                new JapaneseWord("りょう", "ryou", new String[]{"dormitory"}, "hiragana", "", ""), 
                new JapaneseWord("りょこうがいしゃ", "ryokougaisha", new String[]{"travel agency"}, "hiragana", "", ""), 
                new JapaneseWord("あぶない", "abunai", new String[]{"dangerous"}, "hiragana", "i", ""), 
                new JapaneseWord("うらやましい", "urayamashii", new String[]{"envious"}, "hiragana", "i", ""), 
                new JapaneseWord("すくない", "sukunai", new String[]{"a little", "a few"}, "hiragana", "i", ""), 
                new JapaneseWord("つよい", "tsuyoi", new String[]{"strong"}, "hiragana", "i", ""), 
                new JapaneseWord("えらぶ", "erabu", new String[]{"to choose", "to select"}, "hiragana", "", ""), 
                new JapaneseWord("おゆをわかす", "oyuwowakasu", new String[]{"to boil water"}, "hiragana", "", ""), 
                new JapaneseWord("かみをとかす", "kamiwotokasu", new String[]{"to comb one's hair"}, "hiragana", "", ""), 
                new JapaneseWord("こむ", "komu", new String[]{"to get crowded"}, "hiragana", "", ""), 
                new JapaneseWord("たからくじにあたる", "takarakujiniataru", new String[]{"to win a lottery"}, "hiragana", "", ""), 
                new JapaneseWord("ぬぐ", "nugu", new String[]{"to take off (clothes)"}, "hiragana", "", ""), 
                new JapaneseWord("ひげをそる", "higewosoru", new String[]{"to shave one's beard"}, "hiragana", "", ""), 
                new JapaneseWord("いれる", "ireru", new String[]{"to make tea, coffee, etc."}, "hiragana", "", ""), 
                new JapaneseWord("うまれる", "umareru", new String[]{"to be born"}, "hiragana", "", ""), 
                new JapaneseWord("かぎをかける", "kagiwokakeru", new String[]{"to lock"}, "hiragana", "", ""), 
                new JapaneseWord("たりる", "tariru", new String[]{"to be sufficient", "to be enough"}, "hiragana", "", ""), 
                new JapaneseWord("なれる", "nareru", new String[]{"to get used to..."}, "hiragana", "", ""), 
                new JapaneseWord("おいのりする", "oinorisuru", new String[]{"to pray"}, "hiragana", "", ""), 
                new JapaneseWord("けしょうする", "keshousuru", new String[]{"to put makeup on"}, "hiragana", "", ""), 
                new JapaneseWord("しゅうしょくする", "shuushokusuru", new String[]{"to get a full-time job (at...)"}, "hiragana", "", ""), 
                new JapaneseWord("する", "suru", new String[]{"to wear small items (necktie, watch, etc.)"}, "hiragana", "", ""), 
                new JapaneseWord("りこんする", "rikonsuru", new String[]{"to get a divorce"}, "hiragana", "", ""), 
                new JapaneseWord("コンタクト", "kontakuto", new String[]{"contact lenses"}, "katakana", "", ""), 
                new JapaneseWord("サラリーマン", "sarariiman", new String[]{"salary man"}, "katakana", "", ""), 
                new JapaneseWord("ショッピングモール", "shoppingumooru", new String[]{"shopping mall"}, "katakana", "", ""), 
                new JapaneseWord("スプーン", "supuun", new String[]{"spoon"}, "katakana", "", ""), 
                new JapaneseWord("ニュース", "nyuusu", new String[]{"news"}, "katakana", "", ""), 
                new JapaneseWord("パンダ", "panda", new String[]{"panda"}, "katakana", "", ""), 
                new JapaneseWord("ブーツ", "buutsu", new String[]{"boots"}, "katakana", "", ""), 
                new JapaneseWord("ヒーター", "hiitaa", new String[]{"heater"}, "katakana", "", "")
            };
            
            var chapter18 = new JapaneseWord[]
            {
                new JapaneseWord("あと", "ato", new String[]{"the rest"}, "hiragana", "", ""), 
                new JapaneseWord("しょゆう", "shoyuu", new String[]{"soy sauce"}, "hiragana", "", ""), 
                new JapaneseWord("そと", "soto", new String[]{"outside"}, "hiragana", "", ""), 
                new JapaneseWord("にっき", "nikki", new String[]{"diary"}, "hiragana", "", ""), 
                new JapaneseWord("むし", "mushi", new String[]{"insect"}, "hiragana", "", ""), 
                new JapaneseWord("やちん", "yachin", new String[]{"rent"}, "hiragana", "", ""), 
                new JapaneseWord("ゆうがた", "yuugata", new String[]{"evening"}, "hiragana", "", ""), 
                new JapaneseWord("るすばんでんわ", "rusubandenwa", new String[]{"answering machine"}, "hiragana", "", ""), 
                new JapaneseWord("れいぞうこ", "reizouko", new String[]{"refrigerator"}, "hiragana", "", ""), 
                new JapaneseWord("ろうそく", "rousoku", new String[]{"candle"}, "hiragana", "", ""), 
                new JapaneseWord("あかるい", "akarui", new String[]{"bright"}, "hiragana", "i", ""), 
                new JapaneseWord("きぶんがわるい", "kibungawarui", new String[]{"to feel sick"}, "hiragana", "i", ""), 
                new JapaneseWord("くらい", "kurai", new String[]{"dark"}, "hiragana", "i", ""), 
                new JapaneseWord("はずかしい", "hazukashii", new String[]{"embarassing", "to feel embarassed"}, "hiragana", "i", ""), 
                new JapaneseWord("はく", "aku", new String[]{"(something) opens"}, "hiragana", "", ""), 
                new JapaneseWord("あやまる", "ayamaru", new String[]{"to apologize"}, "hiragana", "", ""), 
                new JapaneseWord("おす", "osu", new String[]{"to press", "to push"}, "hiragana", "", ""), 
                new JapaneseWord("おとす", "otosu", new String[]{"to drop (something)"}, "hiragana", "", ""), 
                new JapaneseWord("おゆがわく", "oyugawaku", new String[]{"water boils"}, "hiragana", "", ""), 
                new JapaneseWord("ころぶ", "korobu", new String[]{"to fall down"}, "hiragana", "", ""), 
                new JapaneseWord("こわす", "kowasu", new String[]{"to break (something)"}, "hiragana", "", ""), 
                new JapaneseWord("さく", "saku", new String[]{"to bloom"}, "hiragana", "", ""), 
                new JapaneseWord("しまる", "shimaru", new String[]{"(something) closes"}, "hiragana", "", ""), 
                new JapaneseWord("たすかる", "tasukaru", new String[]{"to be saved", "to be helped"}, "hiragana", "", ""), 
                new JapaneseWord("たのむ", "tanomu", new String[]{"to ask (a favor)"}, "hiragana", "", ""), 
                new JapaneseWord("つく", "tsuku", new String[]{"(something) turns on"}, "hiragana", "", ""), 
                new JapaneseWord("よごす", "yogosu", new String[]{"to make dirty"}, "hiragana", "", ""), 
                new JapaneseWord("おちる", "ochiru", new String[]{"(something) drops"}, "hiragana", "", ""), 
                new JapaneseWord("かたづける", "katadukeru", new String[]{"to tidy up"}, "hiragana", "", ""), 
                new JapaneseWord("かんがえる", "kangaeru", new String[]{"to think (about)", "to consider"}, "hiragana", "", ""), 
                new JapaneseWord("きえる", "kieru", new String[]{"(something) goes off", "(something) disappears"}, "hiragana", "", ""), 
                new JapaneseWord("こわれる", "kowareru", new String[]{"(something) breaks"}, "hiragana", "", ""), 
                new JapaneseWord("よごれる", "yogoreru", new String[]{"to become dirty"}, "hiragana", "", ""), 
                new JapaneseWord("ちゅうもんする", "chuumonsuru", new String[]{"to place an order"}, "hiragana", "", ""), 
                new JapaneseWord("エアコン", "eakon", new String[]{"air conditioner"}, "katakana", "", ""), 
                new JapaneseWord("カーチン", "kaatin", new String[]{"curtain"}, "katakana", "", ""), 
                new JapaneseWord("クッション", "kusshon", new String[]{"cushion"}, "katakana", "", ""), 
                new JapaneseWord("シャンプー", "shanpuu", new String[]{"shampoo"}, "katakana", "", ""), 
                new JapaneseWord("スイッチ", "suicchi", new String[]{"switch"}, "katakana", "", ""), 
                new JapaneseWord("スープ", "suupu", new String[]{"soup"}, "katakana", "", ""), 
                new JapaneseWord("スカート", "sukaato", new String[]{"skirt"}, "katakana", "", ""), 
                new JapaneseWord("ソファ", "sofa", new String[]{"sofa"}, "katakana", "", ""), 
                new JapaneseWord("タオル", "taoru", new String[]{"towel"}, "katakana", "", ""), 
                new JapaneseWord("ポップコーン", "poppukoon", new String[]{"popcorn"}, "katakana", "", "") 
            };
            
            var chapter19 = new JapaneseWord[]
            {
                new JapaneseWord("おくさま", "okusama", new String[]{"(your/his) wife"}, "hiragana", "", ""), 
                new JapaneseWord("おこさん", "okosan", new String[]{"(your/their) child"}, "hiragana", "", ""), 
                new JapaneseWord("おれい", "orei", new String[]{"expression of gratitude"}, "hiragana", "", ""), 
                new JapaneseWord("けいご", "keigo", new String[]{"honorific language"}, "hiragana", "", ""), 
                new JapaneseWord("こちら", "kochira", new String[]{"this way (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("しゅっちょう", "shucchou", new String[]{"business trip"}, "hiragana", "", ""), 
                new JapaneseWord("しゅるい", "shurui", new String[]{"a kind", "a sort"}, "hiragana", "", ""), 
                new JapaneseWord("せいかく", "seikaku", new String[]{"personality"}, "hiragana", "", ""), 
                new JapaneseWord("ちゅうがくせい", "chuugakusei", new String[]{"junior high school student"}, "hiragana", "", ""), 
                new JapaneseWord("どちら", "dochira", new String[]{"where (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("なまけもの", "namakemono", new String[]{"lazy person"}, "hiragana", "", ""), 
                new JapaneseWord("なやみ", "nayami", new String[]{"worry"}, "hiragana", "", ""), 
                new JapaneseWord("はずかしがりや", "hazukashigariya", new String[]{"shy person"}, "hiragana", "", ""), 
                new JapaneseWord("はなし", "hanashi", new String[]{"chat", "talk"}, "hiragana", "", ""), 
                new JapaneseWord("ぶちょう", "buchou", new String[]{"department manager"}, "hiragana", "", ""), 
                new JapaneseWord("ぶんか", "bunka", new String[]{"culture"}, "hiragana", "", ""), 
                new JapaneseWord("まちがい", "machigai", new String[]{"mistake"}, "hiragana", "", ""), 
                new JapaneseWord("なかがいい", "nakagaii", new String[]{"be on good terms", "to be close with", "to get along well"}, "hiragana", "i", ""), 
                new JapaneseWord("まじめ", "majime", new String[]{"serious", "sober", "diligent"}, "hiragana", "na", ""), 
                new JapaneseWord("いらっしゃる", "irassharu", new String[]{"honorific expression for iku, kuru, and iru"}, "hiragana", "", ""), 
                new JapaneseWord("おくる", "okuru", new String[]{"to walk/drive (someone)"}, "hiragana", "", ""), 
                new JapaneseWord("おこる", "okoru", new String[]{"to get angry"}, "hiragana", "", ""), 
                new JapaneseWord("おっしゃる", "ossharu", new String[]{"honorific expression for iu"}, "hiragana", "", ""), 
                new JapaneseWord("おやすみになる", "oyasumininaru", new String[]{"honorific expression for neru"}, "hiragana", "", ""), 
                new JapaneseWord("きまる", "kimaru", new String[]{"to be decided"}, "hiragana", "", ""), 
                new JapaneseWord("くださる", "kudasaru", new String[]{"honorific expression for kureru"}, "hiragana", "", ""), 
                new JapaneseWord("ごらんになる", "goranninaru", new String[]{"honorific expression for miru"}, "hiragana", "", ""), 
                new JapaneseWord("しりあう", "shiriau", new String[]{"to get acquainted with"}, "hiragana", "", ""), 
                new JapaneseWord("~ていらっしゃる", "~teirassharu", new String[]{"honoritic expression for ~teiru"}, "hiragana", "", ""), 
                new JapaneseWord("なさる", "nasaru", new String[]{"honorific expression for suru"}, "hiragana", "", ""), 
                new JapaneseWord("ひっこす", "hikkosu", new String[]{"to move (to another place to live)"}, "hiragana", "", ""), 
                new JapaneseWord("めしあがる", "meshiagaru", new String[]{"honorific expression for taberu and nomu"}, "hiragana", "", ""), 
                new JapaneseWord("よぶ", "yobu", new String[]{"to call (one's name)", "to invite"}, "hiragana", "", ""), 
                new JapaneseWord("よる", "yoru", new String[]{"to stop by"}, "hiragana", "", ""), 
                new JapaneseWord("おくれる", "okureru", new String[]{"to become late"}, "hiragana", "", ""), 
                new JapaneseWord("かける", "kakeru", new String[]{"to sit down"}, "hiragana", "", ""), 
                new JapaneseWord("はれる", "hareru", new String[]{"to become sunny"}, "hiragana", "", ""), 
                new JapaneseWord("もてる", "moteru", new String[]{"to be popular (in terms of romantic interest)"}, "hiragana", "", ""), 
                new JapaneseWord("えんりょする", "enryosuru", new String[]{"to hold back for the time being", "to refrain from"}, "hiragana", "", ""), 
                new JapaneseWord("ごちそうする", "gochisousuru", new String[]{"to treat/invite (someone) to a meal"}, "hiragana", "", ""), 
                new JapaneseWord("しょうたいする", "shoutaisuru", new String[]{"to invite someone (to an event/place)"}, "hiragana", "", ""), 
                new JapaneseWord("ちゅういする", "chuuisuru", new String[]{"to watch out", "to give warning"}, "hiragana", "", ""), 
                new JapaneseWord("はなしをする", "hanashiwosuru", new String[]{"to have a talk"}, "hiragana", "", "")
            };
            
            var chapter20 = new JapaneseWord[]
            {
                new JapaneseWord("あちら", "achira", new String[]{"that way (polite)"}, "hiragana", "", ""), 
                new JapaneseWord("うちゅうじん", "uchuujin", new String[]{"space alien"}, "hiragana", "", ""), 
                new JapaneseWord("おと", "oto", new String[]{"sound"}, "hiragana", "", ""), 
                new JapaneseWord("おにぎり", "onigiri", new String[]{"rice ball"}, "hiragana", "", ""), 
                new JapaneseWord("かかりのもの", "kakarinomono", new String[]{"our person in charge"}, "hiragana", "", ""), 
                new JapaneseWord("かど", "kado", new String[]{"corner"}, "hiragana", "", ""), 
                new JapaneseWord("くうこう", "kuukou", new String[]{"airport"}, "hiragana", "", ""), 
                new JapaneseWord("じ", "ji", new String[]{"letter", "character"}, "hiragana", "", ""), 
                new JapaneseWord("してん", "shiten", new String[]{"branch office"}, "hiragana", "", ""), 
                new JapaneseWord("しゅみ", "shumi", new String[]{"hobby", "pastime"}, "hiragana", "", ""), 
                new JapaneseWord("しょうせつ", "shousetsu", new String[]{"novel"}, "hiragana", "", ""), 
                new JapaneseWord("しんごう", "shingou", new String[]{"traffic light"}, "hiragana", "", ""), 
                new JapaneseWord("せんす", "sensu", new String[]{"fan"}, "hiragana", "", ""), 
                new JapaneseWord("つき", "tsuki", new String[]{"moon"}, "hiragana", "", ""), 
                new JapaneseWord("でんしじしょ", "denshijisho", new String[]{"electronic dictionary"}, "hiragana", "", ""), 
                new JapaneseWord("~や", "~ya", new String[]{"~shop"}, "hiragana", "", ""), 
                new JapaneseWord("おもい", "omoi", new String[]{"heavy", "serious (illness)"}, "hiragana", "i", ""), 
                new JapaneseWord("かるい", "karui", new String[]{"light"}, "hiragana", "i", ""), 
                new JapaneseWord("いたす", "itasu", new String[]{"extra-modest expression for suru"}, "hiragana", "", ""), 
                new JapaneseWord("いただく", "itadaku", new String[]{"extra-modest expression for taberu and nomu"}, "hiragana", "", ""), 
                new JapaneseWord("いただく", "itadaku", new String[]{"humble expression for morau"}, "hiragana", "", ""), 
                new JapaneseWord("うかがう", "ukagau", new String[]{"to humbly visit", "to humbly ask"}, "hiragana", "", ""), 
                new JapaneseWord("おる", "oru", new String[]{"extra-modest expression for iru"}, "hiragana", "", ""), 
                new JapaneseWord("ござる", "gozaru", new String[]{"extra-modest expression for aru"}, "hiragana", "", ""), 
                new JapaneseWord("~ておる", "~teoru", new String[]{"extra-modest expression for ~teiru"}, "hiragana", "", ""), 
                new JapaneseWord("~でござる", "~degozaru", new String[]{"extra-modest expression for desu"}, "hiragana", "", ""), 
                new JapaneseWord("まいる", "mairu", new String[]{"extra-modest expression for iku and kuru"}, "hiragana", "", ""), 
                new JapaneseWord("まがる", "magaru", new String[]{"to turn (right/left)"}, "hiragana", "", ""), 
                new JapaneseWord("もうす", "mousu", new String[]{"extra-modest expression for iu"}, "hiragana", "", ""), 
                new JapaneseWord("もどる", "modoru", new String[]{"to return", "to come back"}, "hiragana", "", ""), 
                new JapaneseWord("きこえる", "kikoeru", new String[]{"to be audible"}, "hiragana", "", ""), 
                new JapaneseWord("さしあげる", "sashiageru", new String[]{"humble expression for ageru"}, "hiragana", "", ""), 
                new JapaneseWord("つたえる", "tsutaeru", new String[]{"to convey (message)"}, "hiragana", "", ""), 
                new JapaneseWord("またせる", "mataseru", new String[]{"to keep (someone) waiting"}, "hiragana", "", ""), 
                new JapaneseWord("こうかんする", "koukansuru", new String[]{"to exchange"}, "hiragana", "", ""), 
                new JapaneseWord("せいかつする", "seikatsusuru", new String[]{"to lead a life"}, "hiragana", "", ""), 
                new JapaneseWord("へんぴんする", "henpinsuru", new String[]{"to return (merchandise)"}, "hiragana", "", ""), 
                new JapaneseWord("アニメ", "anime", new String[]{"animation"}, "katakana", "", ""), 
                new JapaneseWord("スニーカー", "suniikaa", new String[]{"sneakers"}, "katakana", "", ""), 
                new JapaneseWord("ドイツ", "doitsu", new String[]{"Germany"}, "katakana", "", ""), 
                new JapaneseWord("ハイヒール", "haihiiru", new String[]{"high heels"}, "katakana", "", "")
            };

            genkiVocab[0] = chapter1;
            genkiVocab[1] = chapter2;
            genkiVocab[2] = chapter3;
            genkiVocab[3] = chapter4;
            genkiVocab[4] = chapter5;
            genkiVocab[5] = chapter6;
            genkiVocab[6] = chapter7;
            genkiVocab[7] = chapter8;
            genkiVocab[8] = chapter9;
            genkiVocab[9] = chapter10;
            genkiVocab[10] = chapter11;
            genkiVocab[11] = chapter12;
            genkiVocab[12] = chapter13;
            genkiVocab[13] = chapter14;
            genkiVocab[14] = chapter15;
            genkiVocab[15] = chapter16;
            genkiVocab[16] = chapter17;
            genkiVocab[17] = chapter18;
            genkiVocab[18] = chapter19;
            genkiVocab[19] = chapter20;

            return genkiVocab;
        }
    }
}
